Basic 신지원 sprint2
codeit-sprint-fullstack/2-Sprint-Mission-FE pull request #10
Opened 2024-08-06 06:48 UTC by shinji530

## 요구사항

### 기본

- [x] “판다마켓" 로고 클릭 시 루트 페이지(“/”)로 이동합니다.
- [x] 로그인 페이지, 회원가입 페이지 모두 로고 위 상단 여백이 동일합니다.
- [x] SNS 아이콘들은 클릭 시 각각 “https://www.google.com/”, “https://www.kakaocorp.com/page/” 으로 이동합니다.
- [x] input 요소에 focus in 일 때, 테두리 색상은 ##3692FF입니다.
- [x] input 요소에 focus out 일 때, 테두리는 없습니다.
- [x] “회원가입”버튼 클릭 시 “/signup” 페이지로 이동합니다.
- [x] “로그인”버튼 클릭 시 “/login” 페이지로 이동합니다

### 심화

- [x] palette에 있는 color값들을 css 변수로 등록해서 사용합니다.
- [ ] 구글 애널리틱스로 방문자 수 확인하기 할 수 있도록 설정합니다.
- [x] 비밀번호, 비밀번호 확인 input 요소 오른쪽에 비밀번호를 확인할 수 있는 눈 모양 아이콘을 추가합니다.

## 스크린샷

<a href="https://ibb.co/wMDVk9Q"><img src="https://i.ibb.co/D53hJxM/2024-08-06-154529.png" alt="2024-08-06-154529" border="0"></a>

<a href="https://ibb.co/r5wZ1qx"><img src="https://i.ibb.co/h2mKtrB/2024-08-06-154544.png" alt="2024-08-06-154544" border="0"></a>

## 멘토에게

- 코드가 지저분하진 않은지 확인해주세요

## Netlify 주소
https://lambent-piroshki-8db3f8.netlify.app/

2024-08-06 12:19 UTC, MCprotein commented on login.html
> +                    <input class="input-area" placeholder="이메일을 입력해주세요" type="email"></input>
@shinji530 지원님! input 태그를 그냥 사용하셨는데, MDN 문서를 보면 label 태그와 함께 사용하면 더 범용적이고 확장성있게 개발 할 수 있네요 ㅎㅎ

- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#labels
- https://developer.mozilla.org/ko/docs/Web/HTML/Element/label

그리고 <input></input> 열린태그와 닫힌태그 사이에 아무것도 없으면 <input/> 으로 줄여쓰는것도 좋을거같아요!

2024-08-06 12:35 UTC, MCprotein commented on login.html
> +                    });
@shinji530 이부분은 아직 안배운내용이지만 자바스크립트로 구현 해주셨네요! 
이렇게 하셔도 되고, 더 간단하고 안전하게 하는 방법도 있어요! 
- Object.freeze: immutable object 생성 (typescript의 enum과 같은 역할 가능) [MDN참고](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze)
- type을 password와 text로 하드코딩해서 직접 사용하기보다는 enum같은것을 만들어서 사용하는게 유지보수에 더 좋아요! 
```js
document.addEventListener('DOMContentLoaded', function() {
    const passwordField = document.getElementById('password-field');
    const toggle = document.getElementById('toggle');
    const passwordTypeSwitch = Object.freeze({
        password: 'text',
        text: 'password'
    })

    toggle.addEventListener('click', () => {
        passwordField.type = passwordTypeSwitch[passwordField.type];
    })
});
```

2024-08-06 12:39 UTC, MCprotein commented
@shinji530 이 PR 코드에 미션1 코드도 같이 있는데, 미션 1 PR 닫고 내용을 여기에 추가해주실 수 있으실까요?

2024-08-06 12:56 UTC, MCprotein commented on signin.html
이쪽 파일도 login 파일과 동일한 피드백 드립니다~

2024-08-06 12:58 UTC, MCprotein requested changes

2024-08-06 12:58 UTC, MCprotein commented on signin.html
> +                    <input id="password-field" class="input-area" placeholder="비밀번호를 다시 한 번 입력해주세요" type="password"></input>
@shinji530 
password-field id가 중복돼서 비밀번호 확인쪽 눈동자 아이콘은 작동하지않네요!

2024-08-07 00:44 UTC, shinji530 commented on signin.html
> +                    <input id="password-field" class="input-area" placeholder="비밀번호를 다시 한 번 입력해주세요" type="password"></input>
수정했습니다!

2024-08-07 01:01 UTC, shinji530 commented on login.html
> +                    <input class="input-area" placeholder="이메일을 입력해주세요" type="email"></input>
p 태그 label 태그로 변경하고 <input/>으로 줄였습니다

2024-08-07 01:04 UTC, shinji530 commented on login.html
> +                    });
Object.freeze 오 이런게 있는지 몰랐어요,,! 이렇게 고쳐서 커밋하겠습니다

2024-08-07 03:20 UTC, MCprotein commented on signin.html
> +                        <img id="toggle" class="eye" src="/assets/img/login/btn_visibility_on.png"></img>
@shinji530 이미지 태그도 전체적으로 보면 태그 내부에 내용이 없어서 <img/>로 써도 될거같네요! 
다만 코드 스타일과 관련된 내용이기때문에 이번에 수정하지 않아도 괜찮습니다!

2024-08-07 03:21 UTC, MCprotein commented
@shinji530 수정분이 아직 배포되지 않은거같은데 확인부탁드릴게요!

2024-08-07 04:43 UTC, MCprotein commented
@shinji530 
> 사용자의 브라우저 설정에 따라 기본 폰트 크기 설정이 변화함에 따라서 페이지의 요소 간 간격, 요소의 크기, font-size 등 모든 크기와 관련된 값이 크고 작아지도록 설정해 주세요.

이 요구사항에 체크가 되어있는데, css 파일 보면 일부분에만 적용이 되어있는거같아요! 확인한번부탁드려요!

2024-08-07 06:09 UTC, shinji530 commented on signin.html
> +                        <img id="toggle" class="eye" src="/assets/img/login/btn_visibility_on.png"></img>
img 태그 어떤 건 <img>만 쓰고 어떤 건 <img></img>로 써놔서 변경 후 커밋하고 배포 했습니다!

2024-08-08 11:56 UTC, MCprotein commented
@shinji530 https://lambent-piroshki-8db3f8.netlify.app/ 접속이 안되는데 혹시 의도하신걸까요?

2024-08-09 08:54 UTC, shinji530 commented
> @shinji530 https://lambent-piroshki-8db3f8.netlify.app/ 접속이 안되는데 혹시 의도하신걸까요?

제가 주소를 변경하고 업데이트를 안해놨네요,,! 다시 업데이트 해놨습니다!
https://pandamarket-sprint.netlify.app/

2024-08-09 10:20 UTC, MCprotein requested changes

2024-08-09 10:20 UTC, MCprotein commented on index.html
> +    </body>
@shinji530 <body> 여는태그가 없네요!

2024-08-09 10:20 UTC, MCprotein commented on login.html
> +                    <input id="password-field" class="input-area" placeholder="비밀번호를 입력해주세요" type="password"/>
@shinji530 label  안에 있는 input 태그에서 id는 label의 for과 같아야해요!

> The following is an example of how to associate the <label> with an <input> element in the above style. You need to give the <input> an id attribute. The <label> then needs a for attribute whose value is the same as the input's id.

```html
<label for="peas">Do you like peas?</label>
<input type="checkbox" name="peas" id="peas" />
```


Ref: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#accessibility_concerns

2024-08-09 10:20 UTC, MCprotein commented on main.css
> +    padding: 16px auto;
@shinji530 여기 다시 확인해주시겠어요??

Ref: https://velog.io/@losnah5h/padding%EC%97%90%EB%8A%94-auto%EA%B0%80-%EC%9C%A0%ED%9A%A8%ED%95%9C-%EA%B0%92%EC%9D%B4-%EC%95%84%EB%8B%88%EB%8B%A4

2024-08-11 10:00 UTC, shinji530 commented on index.html
> +    </body>
수정했습니다!

2024-08-11 10:01 UTC, shinji530 commented on login.html
> +                    <input id="password-field" class="input-area" placeholder="비밀번호를 입력해주세요" type="password"/>
변경했습니다!

2024-08-11 10:04 UTC, shinji530 commented on main.css
> +    padding: 16px auto;
헉,, 새로 알아갑니다.. 수정했습니다!

2024-08-11 10:59 UTC, MCprotein commented
@shinji530 지원님! 고생하셨습니다!

2024-08-11 10:59 UTC, merged