[신지원] Sprint5
codeit-sprint-fullstack/2-Sprint-Mission-FE pull request #100
Opened 2024-09-03 06:17 UTC by shinji530

# 요구사항
## 기본 요구사항
### 공통

- [ ] Github에 스프린트 미션 PR을 만들어 주세요.
- [ ] React를 사용해 진행합니다.

### 중고마켓 페이지

- [ ]  PC, Tablet, Mobile 디자인에 해당하는 중고마켓 페이지를 만들어 주세요.

- [ ]  중고마켓 페이지 url path는 별도로 설정하지 않고, ‘/’에 보이도록 합니다.

- [ ]  상품 데이터는 [https://panda-market-api.vercel.app/docs/](https://panda-market-api.vercel.app/docs/#/)에 명세된 GET 메소드 “/products” 를 사용해주세요.

- [ ]  상단 네비게이션 바, 푸터는 랜딩 페이지와 동일한 스타일과 규칙으로 만들어주세요.

- [ ]  상품 데이터는 [https://panda-market-api.vercel.app/docs/](https://panda-market-api.vercel.app/docs/#/)에 명세된 GET 메소드 “/products” 를 활용해주세요.

- [ ] 상품 목록 페이지네이션 기능을 구현합니다.
- [ ] 드롭 다운으로 “최신 순” 또는 “좋아요 순”을 선택해서 정렬을 구현하세요.
- [ ] 상품 목록 검색 기능을 구현합니다.
- [ ]  베스트 상품 데이터는 [https://panda-market-api.vercel.app/docs/](https://panda-market-api.vercel.app/docs/#/)에 명세된 GET 메소드 “/products”의 정렬 기준 favorite을 사용해주세요.

## 심화 요구사항
### 공통

- [ ] 커스텀 hook을 만들어 필요한 곳에 활용해 보세요.
중고마켓 페이지

- [ ] 중고 마켓의 카드 컴포넌트 반응형 기준은 다음과 같습니다.
- 베스트 상품
   - Desktop : 4열
   - Tablet : 2열
   - Mobile : 1열

- 전체 상품
   - Desktop : 5열
   - Tablet : 3열
   - Mobile : 2열

- [ ] 반응형에 따른 페이지 네이션 기능을 구현합니다.
- [ ] 반응형으로 보여지는 물품들의 개수를 다르게 설정할때 서버에 보내는 pageSize값을 적절하게 설정합니다.

## 주요 변경사항

## 스크린샷

## 멘토에게

- 쓸데없는 코드가 있는지 확인바랍니다.
- 효율적인 코딩 방법이 있다면 알려주세요
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2024-09-10 10:53 UTC, junguksim requested changes
전반적으로 잘 짜셨습니다!
리액트가 처음이었을텐데 기능적인 구현을 잘해주셔서 다행입니다.
props, state 잘 활용해서 구현 잘 해주셨습니다.

다만 literal numbers ( 상수들) 을 변수로 설정해주는 것, 한번씩 난해한 코드, useEffect 적용 가능해보이는 부분 등이 있어보여 코멘트 남겼습니다!

2024-09-10 10:53 UTC, junguksim commented on src/component/App.js
> +        setPageSize(4);
숫자를 4, 6 처럼 그대로 쓰기 보다는 constant 변수로 할당해주시면 값이 바뀌어도 무슨 의미의 값이었는지 기억하기가 쉽습니다!

setPagesSize(MOBILE_PAGE_SIZE)
setBestItemSize(MOBILE_BEST_ITEM_SIZE)

이런 식으로요!

2024-09-10 10:53 UTC, junguksim commented on src/component/App.js
> +        setPageSize(4);
+ 협업하거나, 코드 베이스가 커졌을 때 검색으로 찾기도 용이해집니다.

2024-09-10 10:53 UTC, junguksim commented on src/component/App.js
> +        setPageSize(4);
743, 1199 도 마찬가지로 설정해보세요!

MOBILE_WIDTH, TABLET_WIDTH 이런식으로요

2024-09-10 10:53 UTC, junguksim commented on src/component/App.js
> +  const sortedProducts = products.sort((a, b) => a[order] - b[order]);
얘가 실질적으로 렌더링 되는 부분이므로, products 가 변화할 때마다 sort 가 되어야 할 것으로 보이는데요.
useEffect 를 써봐야할 것 같습니다!

2024-09-10 10:53 UTC, junguksim commented on src/component/App.js
> +    setProducts(productList);
여기서 sort를 하는게 더 좋아보이네요!
(handleGetProductList 가 order 나 keyword 등에 따라서 다시 fetch 하게끔 하는 것이므로)

2024-09-10 10:53 UTC, junguksim commented on src/component/BestItem.js
> +  // const [products, setProducts] = useState([]);
필요없는 코드는 지워주세요!

2024-09-10 10:53 UTC, junguksim commented on src/component/ItemList.js
> +	// const [products, setProducts] = useState([]);
필요없는 코드는 지워주세요!

2024-09-10 10:53 UTC, junguksim commented on src/component/Nav.js
> +import logo from '../assets/img/판다 얼굴.png';
이미지 이름은 영어가 좋습니다! (배포 시에 문제가 발생할 여지가 있어요)

2024-09-10 10:53 UTC, junguksim commented on src/component/Pagination.js
> +    const startPage = (pageGroup - 1) * pageLimit + 1;
이 부분 코드가 한눈에 파악하기 어려운 것 같아요.
길어져도 되니까 로직을 개선해봐도 될 거 같고, 혹은 주석을 달아주는 것도 좋아보입니다.

2024-09-10 13:57 UTC, junguksim requested changes

2024-09-10 13:57 UTC, junguksim commented on src/api/ProductService.js
> +  export async function createProduct(productData) {
productData 나 id 처럼 입력값에 대한 검증이 들어가면 좋겠습니다!

2024-09-11 09:00 UTC, junguksim approved these changes
Approve 로 리뷰를 끝내라고 하셔서 바꿉니다!

2024-09-15 14:53 UTC, shinji530 commented on src/api/ProductService.js
> +  export async function createProduct(productData) {
제가 너무 늦게 확인해서 이미 sprint6를 진행해버렸는데 sprint5 브랜치에서 리뷰해주신 부분 수정하면 sprint6랑 충돌이 날 거 같아서 혹시 sprint 6에서 반영해도 될까요? 다음부터는 빨리 확인하겠습니다 죄송합니다ㅠㅠ

2024-09-19 11:07 UTC, merged