[방신철]sprint5
codeit-sprint-fullstack/2-Sprint-Mission-FE pull request #103
Opened 2024-09-03 09:04 UTC by bangsinchur

## 요구사항

### 기본

- [x]
- []
- []

### 심화

- [x]
- []

## 주요 변경사항

-
-

## 스크린샷

![image](이미지url)

## 멘토에게

-
-
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2024-09-09 22:07 UTC, bangsinchur commented
https://tranquil-taffy-4a4dbd.netlify.app/ 넷리파이 배포주소 입니다.~

2024-09-10 13:51 UTC, junguksim requested changes
전반적으로 잘 짜주셨습니다.
미션4에서 했던 입력값 검증이나, 리터럴 넘버 상수화 , 그외 변수/함수 명 등에서 리뷰 남겼습니다!

+ index.html, items.html 같은 코드들은 옛날 코드 같은데,( 미션 1~3 코드들) 포함되지 않는 편이 좋을 거 같네요~

2024-09-10 13:51 UTC, junguksim commented on API/ProductService.js
> +    const paramsDefault ={page:1,pageSize:100,keyword:''};
default value 는 함수의 인자 부분에 바로 설정할 수도 있는데 이렇게 하신 이유가 있나요??
(실제로 빈 오브젝트를 넣어서 이미 설정해두신 걸로 보이는데요!)

잘 모르고 하신거라면 이 페이지를 참고해보세요!
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters

2024-09-10 13:51 UTC, junguksim commented on API/ProductService.js
> +    const paramsFinal ={...paramsDefault,...params};
만약에 인자 부분에 paramsDefault 값들을 넣었다면 이렇게 할 필요 없이 그냥 params 만 써도 되겠죠!
(params 인자가 들어왔을 경우 그걸 쓸거고, 아닐 경우 paramsDefault 를 쓸테니)

2024-09-10 13:51 UTC, junguksim commented on API/ProductService.js
> +    return data;
이 함수는 에러 처리가 안되어있네요!

2024-09-10 13:51 UTC, junguksim commented on API/ProductService.js
> +    try{
서버 호출 전에 에러 검증을 해줘도 좋겠습니다.
id 가 들어오지 않았다면 (`if (!id)`) 에러를 발생시키면 되겠죠?

2024-09-10 13:51 UTC, junguksim commented on API/ProductService.js
> +        headers:{
헤더가 계속 반복되네요! axios 의 instance 로 만들어서 해도 좋겠습니다.

2024-09-10 13:51 UTC, junguksim commented on API/ProductService.js
> +export async function createProduct(productData){
productData 에 대한 검증 코드도 추가되면 좋겠네요!
name, description 등이 있는지

2024-09-10 13:51 UTC, junguksim commented on API/ProductService.js
> +export async function patchProduct(id,productData){
입력값 검증이 추가되면 좋겠습니다~

2024-09-10 13:51 UTC, junguksim commented on src/App.js
> +      if (width <= 743) {
ITEMS_PER_PAGE 처럼, 이런 값들도 모두 상수 처리 해주면 좋겠습니다!

2024-09-10 13:51 UTC, junguksim commented on src/App.js
> +    const updatePageSize = () => {
이벤트 리스너로 쓰이는 함수의 경우 
onPageWidthUpdate 처럼 앞에 on 을 붙이면 명시적입니다!

2024-09-10 13:51 UTC, junguksim commented on src/PageButton.js
> +  const startPage =
이런 수식이 들어가는 경우 한눈에 보기에 무슨 값이 나올지 예상이 잘 안됩니다!
이런 경우 주석을 추가해주시면 좋겠네요~

2024-09-10 13:51 UTC, junguksim commented on src/ProductList.js
> +  const [selectedOrder, setSelectedOrder] = useState("최신순");
value 는 최신순 같은 한글보다는 "new", "favorites" 같은 게 좋겠네요!

2024-09-11 07:59 UTC, closed without merging