[김태연] Spirnt5
codeit-sprint-fullstack/2-Sprint-Mission-FE pull request #115
Opened 2024-09-08 12:24 UTC by taeyeonkim94

## 요구사항

### 기본
- [x] Github에 스프린트 미션 PR을 만들어 주세요.
- [x] React를 사용해 진행합니다.
중고마켓 페이지

- [x] PC, Tablet, Mobile 디자인에 해당하는 중고마켓 페이지를 만들어 주세요.

- [x] 중고마켓 페이지 url path는 별도로 설정하지 않고, ‘/’에 보이도록 합니다.

- [x] 상품 데이터는 https://panda-market-api.vercel.app/docs/에 명세된 GET 메소드 “/products” 를 사용해주세요.

- [x] 상단 네비게이션 바, 푸터는 랜딩 페이지와 동일한 스타일과 규칙으로 만들어주세요.

- [x] 상품 데이터는 https://panda-market-api.vercel.app/docs/에 명세된 GET 메소드 “/products” 를 활용해주세요.

- [x] 상품 목록 페이지네이션 기능을 구현합니다.
- [x] 드롭 다운으로 “최신 순” 또는 “좋아요 순”을 선택해서 정렬을 구현하세요.
- [x] 상품 목록 검색 기능을 구현합니다.
- [x] 베스트 상품 데이터는 https://panda-market-api.vercel.app/docs/에 명세된 GET 메소드 “/products”의 정렬 기준 favorite을 사용해주세요.

심화 요구사항
공통

- [ ] 커스텀 hook을 만들어 필요한 곳에 활용해 보세요.
중고마켓 페이지

- [ ] 중고 마켓의 카드 컴포넌트 반응형 기준은 다음과 같습니다.
베스트 상품
Desktop : 4열
Tablet : 2열
Mobile : 1열
전체 상품
Desktop : 5열
Tablet : 3열
Mobile : 2열
반응형에 따른 페이지 네이션 기능을 구현합니다.
반응형으로 보여지는 물품들의 개수를 다르게 설정할때 서버에 보내는 pageSize값을 적절하게 설정합니다.

## 주요 변경사항
- 창크기에 따라 불러오는 데이터의 개수 변화까지는 완료했지만 css가 아직입니다.
- netlify가 없습니다
-  데이터 리퀘스트 함수 test를 새로 만들었습니다.
- API 명세서 : https://panda-market-api.vercel.app/docs/
## 스크린샷

![image](이미지url)

## 멘토에게

-
![오류뜨는이유](https://github.com/user-attachments/assets/ca416307-b661-49e0-b323-7c41c1f41641)

test 함수에서 orderBy, 를 이용해 리퀘스트를 하면 리퀘스트 실패가 떠서 저렇게 나눠놨습니다 이유를 잘모르겠어요
css를 뒤집어 까는중입니다
-
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2024-09-10 01:22 UTC, taeyeonkim94 commented
https://secondpandamarket.netlify.app/
netlify 주소입니다

2024-09-10 14:24 UTC, taeyeonkim94 commented
창크기에 따른 반응형도 구현해둔 상태입니다

2024-09-11 01:33 UTC, junguksim requested changes
전반적으로 잘 짜주셨습니다!
props 잘 활용해서 컴포넌트 분리 잘 해주셨습니다.
styled 적용도 잘 하셨네요!

몇가지 아쉬운 점만 적어놨습니다.

2024-09-11 01:33 UTC, junguksim commented on public/faq.html
> +    <title>FAQ</title>
public 에 faq.html 이나 privacy.html 등은 들어갈 필요가 없습니다.
React 는 SPA 이므로 index.html 의 root 밖에 안쓰기 때문입니다!

2024-09-11 01:33 UTC, junguksim commented on src/api/ArticleService.js
> +export async function getArticleList(Params) {
Params 는 변수이므로 첫 글자 대문자로 쓰지 말아주세요~
(대문자는 Class나 나중에 타입스크립트 배우면 그 떄 쓰입니다)

2024-09-11 01:33 UTC, junguksim commented on src/api/ArticleService.js
> +  const { page = 1, pageSize = 10, keyword = "" } = Params || {};
default 값을 이렇게 잡을 거라면
`getArticleList(params={page:1, pageSize=10, keyword=""})`
이렇게 argument 에 붙일 수도 있습니다

2024-09-11 01:33 UTC, junguksim commented on src/components/App.js
> +    if (width > 1200)
1200 이나 744, 4, 10 처럼 의미가 있는 숫자들은 숫자 그대로 표현하기 보다, 상수로 표현해주면 좋습니다.

`const TABLET_WIDTH=1200`
으로 선언하고 `TABLET_WIDTH` 로 쓰게 되면, 코드리뷰나 협업하는 사람들도 알아보기 편하고, 숫자가 바뀐다고 해도 의미는 바뀌지 않아서 좋습니다.

2024-09-11 01:33 UTC, junguksim commented on src/components/App.js
> +  const handleChangePageSize = () => {};
없어도 되는 함수겠네요!

2024-09-11 01:33 UTC, junguksim commented on src/components/App.js
> +    const handleReSize = () => {
저는 이벤트 리스너의 콜백함수 이름으로 onResize 처럼 앞에 on 을 붙이는 걸 선호합니다!
Resize 가 일어났을 때 -> 뭔가를 하겠다 라는 의미가 잘 보여서 좋은 것 같습니다.

2024-09-11 01:33 UTC, junguksim commented on src/components/App.js
> +    const { list, totalCount } = await test(options);
test 함수를 그대로 쓸거라면 이름도 바꿔주세요!

2024-09-11 01:37 UTC, junguksim requested changes

2024-09-11 01:37 UTC, junguksim commented on src/components/App.js
> +  const handleChangePage = async (pageValue) => {
여기서 페이지 이동을 할때, products API 를 두번 콜하고 난 뒤 
example.com 에 GET 호출이 한번 더 되어서 404가 뜹니다.

API 콜링 로직에 이상이 있는 것 같은데 고쳐주세요!

2024-09-11 09:01 UTC, junguksim approved these changes
Approve 로 리뷰를 끝내라고 하셔서 바꿉니다!

2024-09-19 11:07 UTC, merged