[이예린]Sprint8
codeit-sprint-fullstack/2-Sprint-Mission-FE pull request #146
Opened 2024-10-20 14:44 UTC by annylee0723

## 요구사항

### 기본

- [x]
- []
- []

### 심화

- [x]
- []

## 주요 변경사항

-
-

## 스크린샷

![image](이미지url)

## 멘토에게

-
-
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2024-10-20 15:15 UTC, MCprotein requested changes

2024-10-20 15:15 UTC, MCprotein commented on .DS_Store
@annylee0723 예린님! .DS_Store 파일은 맥OS에서만 사용되는 파일이고, 코드와는 무관하니 .gitignore에 넣어주세요! 

참고: https://velog.io/@junr_65535/.DSstore%EA%B0%80-%EB%AD%90%EC%97%AC-%EB%82%9C-%EC%9D%B4%EB%9F%B0%EA%B1%B0-%EC%93%B4%EC%A0%81-%EC%97%86%EB%8A%94%EB%94%94

2024-10-20 15:15 UTC, MCprotein commented on sprint8/.gitignore
@annylee0723 이 파일 내용은 next.js init할때 자동생성된 내용인가요?

2024-10-20 15:15 UTC, MCprotein commented on sprint8/components/Nav.js
> +                pathname === '/free-board' ? style.active : ''
@annylee0723 이 삼항연산자 코드는 아래에도 중복으로 사용되는데, 함수로 빼보면 어떨까요? Nav에 더 많은 링크 버튼이 생기는 경우를 염두하면 중복코드를 제거하는게 좋을거같아요! 

예시코드 드립니다! 제가 작명센스가 없어서 함수이름은 참고만 해주세요 ㅎㅎ
```js
function getButtonActiveStyle(endpoint) {
  const { pathname } = router;
  return endpoint === pathname ? style.active: ''
}

className={`${style.menu} ${getClassStyle('/free-board')}`}
```

2024-10-20 15:18 UTC, MCprotein commented
@annylee0723 커밋로그가 굉장히많은데 브랜치를 어떤 방법으로 어느 브랜치를 base로 해서 만드신건가요?

2024-10-21 10:56 UTC, annylee0723 commented
> @annylee0723 커밋로그가 굉장히많은데 브랜치를 어떤 방법으로 어느 브랜치를 base로 해서 만드신건가요?

Git 브랜치와 GitHub 사용이 미숙할 때, React 스프린트 미션을 진행하면서 [코드잇 가이드](https://www.codeit.kr/topics/sprint-fs-ot/lessons/9016?topicVersion=2&lessonVersion=2)를 따르다 잘못 설정한 것 같습니다. 이 이후 PR 올릴 때 마다 sprint 미션1 때 커밋부터 모두 잡혀서 올라가더라구요.. 원래 그런건줄 알아서 이슈인줄 몰랐습니다ㅠㅠ 이전 커밋들을 삭제할까요?

2024-10-21 11:21 UTC, MCprotein commented
> > @annylee0723 커밋로그가 굉장히많은데 브랜치를 어떤 방법으로 어느 브랜치를 base로 해서 만드신건가요?
> 
> Git 브랜치와 GitHub 사용이 미숙할 때, React 스프린트 미션을 진행하면서 [코드잇 가이드](https://www.codeit.kr/topics/sprint-fs-ot/lessons/9016?topicVersion=2&lessonVersion=2)를 따르다 잘못 설정한 것 같습니다. 이 이후 PR 올릴 때 마다 sprint 미션1 때 커밋부터 모두 잡혀서 올라가더라구요.. 원래 그런건줄 알아서 이슈인줄 몰랐습니다ㅠㅠ 이전 커밋들을 삭제할까요?

base 브랜치를 잘못하신거같은데, upstream의 next-이예린을 base로 해서 새로 만들면 아무코드도 없을거에요
그상태에서 next 설치하고 첨부터 코드 작성하셔야돼요

2024-10-21 11:23 UTC, MCprotein requested changes

2024-10-21 11:23 UTC, MCprotein commented on .DS_Store
@annylee0723 이미 올라간 파일은 gitignore에 추가한다고해서 바로 없어지지않아요
이거 검색해서 해결해보시고 모르겠으면 말씀해주세요

2024-10-21 12:22 UTC, closed without merging

2024-10-21 12:23 UTC, annylee0723 commented
in need of recreating a new pr