[김영은] Sprint 8
codeit-sprint-fullstack/2-Sprint-Mission-FE pull request #147
Opened 2024-10-20 15:37 UTC by Maybeiley

## 요구사항

### 기본

`공통`

- [x] Github에 스프린트 미션 PR을 만들어 주세요.
- [x] Next.js를 사용해 진행합니다.

`자유 게시판 페이지`

- [] 게시글 목록에서 드롭다운을 사용하여 "최신 순"으로 정렬할 수 있도록 합니다.
- [] 본인이 이전 미션에서 생성한 게시글 목록 조회 API를 활용해 GET 메서드로 데이터를 가져옵니다.
- [] 게시글 제목에 검색어가 일부 포함되면 해당 게시글을 검색할 수 있도록 합니다.
- [] 이미지는 디폴트 이미지로 프론트엔드에서 처리해 주세요.
- [] 게시글 닉네임 및 좋아요 개수 역시 임의값으로 프론트엔드에서 처리해주세요.
- [] 베스트 게시글은 최신순 3개 게시글을 요청으로 데이터를 가져와 구현해주세요.
- [] 자유게시판 페이지에서 특정 게시글을 클릭하면 해당 게시물의 상세 페이지로 이동합니다.

`게시글 등록 & 수정 페이지`

- [x] 각 input 필드에 정확한 placeholder 값을 입력합니다.
- [] 모든 input 필드에 값을 입력하면 '등록' 버튼이 활성화됩니다.
- [] 본인이 이전 미션에서 생성한 게시글 생성 API를 활용해 POST 메서드로 게시글을 등록합니다.
- [] '등록' 버튼을 누르면 해당 게시물 상세 페이지로 이동합니다.
- [] 게시글 수정 페이지 UI는 게시글 등록 페이지와 동일합니다.
- [] 본인이 이전 미션에서 생성한 게시글 상세 API의 PATCH 메소드를 사용하여 게시물을 수정합니다.

`게시글 상세 페이지`

- [] 본인이 이전 미션에서 생성한 게시글 상세 API의 GET 메소드를 사용하여 데이터를 가져옵니다.
- [] 본인이 이전 미션에서 생성한 게시글 상세 API의 DELETE 메소드를 사용하여 게시물을 삭제합니다.
- [] 댓글 input에 값을 입력하면 '등록' 버튼이 활성화됩니다.
- [] 본인이 이전 미션에서 생성한 댓글 생성 API를 활용해 POST 메소드로 댓글을 등록합니다.
- [] 본인이 이전 미션에서 생성한 댓글 생성 API를 활용해 PATCH 메소드로 댓글을 수정합니다.
- [] 본인이 이전 미션에서 생성한 댓글 생성 API를 활용해 DELETE 메소드로 댓글을 삭제합니다.

### 심화

`공통`

- [x] 디자인 시안에 따라 반응형 디자인을 구현합니다.

## 주요 변경사항

- 아직 GNB, footer, 게시글 등록 페이지 내용만 작성한 상태입니다.
-

## 스크린샷

<img width="1360" alt="Screenshot 2024-10-21 at 12 33 24 AM" src="https://github.com/user-attachments/assets/c2b3f082-d7d4-430f-9db1-0e880f73bdd7">

## 멘토에게

- next.js 구조나 현재까지의 코드 내용 중 조언해 주실 내용 있으시면 남겨주세요!

2024-10-21 14:11 UTC, json9512 requested changes
코멘트 남겼습니다!

2024-10-21 14:11 UTC, json9512 commented on components/Button.js
> +export default function createButton({ style }) {
오 HOC를 쓰셨군요 👍
다만, 어차피 style에 `btn_small_40` 하나만 쓸거라면 굳이 HOC까지 만들 필요는 없다고 느껴지기도 합니다!

당연히 코드를 짤 때는 어떤 식으로 짜야 유지 보수하기 좋은지 고민하는 것도 필요하지만, 너무 먼 미래를 예상하고 미리 코드 구조를 필요 이상으로 복잡하게 짜는 것도 유의하는게 좋아요.

(이번 미션에서는 굳이 수정 안하셔도 될 것 같습니다!)

2024-10-21 14:11 UTC, json9512 commented on components/Button.js
> +export default function createButton({ style }) {
@Maybeiley

2024-10-21 14:11 UTC, json9512 commented on components/GNB.js
> +import Image from 'next/image';
@Maybeiley 안쓰는 import는 제거해주세요!

2024-10-21 14:11 UTC, json9512 commented on components/GNB.js
> +              style={{ getLinkStyle }}
@Maybeiley getLinkStyle을 그냥 이렇게 넘겨줘도 잘 동작하나요??

2024-10-21 14:11 UTC, json9512 commented on components/GNB.module.css
> +.menu a:hover {
@Maybeiley 여기 hover로 넣어두신 CSS가 없으면 getLinkStyle이 동작하지 않을 것 같습니다!

2024-10-21 14:11 UTC, json9512 commented on components/GNB.js
> +              style={{ getLinkStyle }}
getLinkStyle을 선언하신 것을 보면, isActive를 넘겨줘야 color가 반영된 스타일 객체를 반환해주는데 - 현재는 getLinkStyle 함수 자체를 넘겨주고 있어서 아무런 동작을 하지 않을 것 같습니다

2024-10-22 00:05 UTC, Maybeiley commented on components/Button.js
> +export default function createButton({ style }) {
게시글 등록 페이지에 버튼 모양이 조금 다른 게 하나 더 있어서 버튼 컴포넌트를 썼습니다 ㅎㅎ 코드잇 예시들(실습 등)을 보면서, 한 페이지에 코드가 너무 길어지면 컴포넌트로 나누려고 하는 편인데 말씀을 듣고 보니 재사용성이 없다면 컴포넌트로 나누지 않는 게 맞는지 궁금해졌어요. 예를 들면 어제 밤에 올린 코드 보시면 게시판에 들어갈 리스트를 컴포넌트로 빼놨거든요. 보시구 이것도 불필요한지, 컴포넌트는 어떨 때 나누는 게 맞는지(?) 알려주시면 좋겠습니다 :)

2024-10-22 00:07 UTC, Maybeiley commented on components/GNB.js
> +              style={{ getLinkStyle }}
사실 이전 스프린트 미션 때 리액트에 만들어뒀던 GNB를 그대로 가져와서 넣었는데 작동하지 않더라고요 ㅠㅠ 수정 표시했어야 했는데 깜빡했습니다.. 수정해서 올리겠습니다! 확인 감사합니다

2024-10-28 15:35 UTC, json9512 approved these changes
@Maybeiley 좋습니다! 전체적으로 깔끔하네요. 비동기 에러 처리 부분만 한번 고민해보시면 좋을 것 같습니다 🙇

2024-10-28 15:35 UTC, json9512 commented on pages/board/[id]/edit.js
> +export async function getServerSideProps(content) {
@Maybeiley SSR 함수에서 따로 에러 처리는 필요 없을까요?? 🤔

2024-10-28 15:35 UTC, json9512 commented on pages/board/index.js
> +    console.log('new: ', newKeyword, 'set: ', keyword);
@Maybeiley 불필요한 console.log는 제거해주세요!

2024-10-28 15:35 UTC, json9512 commented on pages/board/newArticle.js
> +    const res = await axios.post('/articles/', data);
@Maybeiley 여긴 따로 에러 처리 필요 없나요?

2024-10-28 15:35 UTC, merged

2024-10-28 15:45 UTC, json9512 commented on components/Button.js
> +export default function createButton({ style }) {
음, 지금은 HOC를 사용해서 버튼 생성 함수를 만드셨는데 - 단순하게 <Button /> 컴포넌트 하나 선언해서 사용하셔도 무방할 것 같긴해요!

HTML button의 prop을 외부에서 주입 받을 수 있게 커스텀 Button 컴포넌트를 만드시면, 굳이 createButton이라는 함수로 래핑 안해도 되지 않을까 싶습니다. 

예를 들면, "등록" 버튼과 "로그인" 버튼이라고 했을 때 이런식으로 짜도 충분할 것 같아서요!
```tsx
function Button({
  children,
  onClick = () => {},
  className,
  disabled = false,
  buttonType = null,
}) {
  if (buttonType === "Primary") {
    return (
      <button
        className={`${styles.btn_primary} ${className}`}
        onClick={onClick}
        disabled={disabled}
      >
        {children}
      </button>
    );
  }

  if (buttonType === "Secondary") {
    return (
      <button
        className={`${styles.btn_secondary} ${className}`}
        onClick={onClick}
        disabled={disabled}
      >
        {children}
      </button>
    );
  }

  return (
    <button
      className={`${styles.btn_default}`}
      onClick={onClick}
      disabled={disabled}
    >
      {children}
    </button>
  );
}

// 사용 하는 곳
// 로그인
import Button from "@/components/Button";

<Button buttonType="Primary">로그인</Button>

<Button buttonType="Secondary">삭제</Button>

<Button>등록</Button>

// css for button
// btn_primary
{
  background-color: gray;
  color: black;
}
// btn_secondary
{
  background-color: red;
  color: white;
}
// btn_default
{
  background-color: blue;
  color: white;
}
```

2024-10-28 15:47 UTC, json9512 commented on components/Button.js
> +export default function createButton({ style }) {
컴포넌트를 나누는 기준은 다양해요!
- 중복되는 코드를 함수로 추상화 하기도 하고
- 비즈니스적으로 너무 강한 결합도가 우려되어서 중복 코드를 일부러 생성하기도 하고
- UI 적으로 나누기도 하고

그때 그때 상황에 따라 다르긴합니다.

2024-10-28 23:48 UTC, Maybeiley commented on components/Button.js
> +export default function createButton({ style }) {
'너무 강한 결합도'라는 게 예를 들면 어떤 건지 궁금하네요!

2024-10-29 11:45 UTC, json9512 commented on components/Button.js
> +export default function createButton({ style }) {
음.. 예를 들면, 사용자에게 여러 권한이 있는 앱이라고 가정해볼게요.
매니저, 회원, 비회원, 슈퍼 관리자 등 이렇게 권한이 부여되어 있고 하나의 동일한 화면을 보여주지만 권한에 따라 화면에서 취할 수 있는 상호작용의 로직이 바뀐다고 생각했을때, 컴포넌트 구조로 화면을 구성하다 보면 컴포넌트를 재사용하려고 너무 많은 로직을 하나의 컴포넌트에 넣는 경우가 있어요.

그럴때는 가끔 컴포넌트를 일부러 복제해서 컴포넌트 내의 로직을 권한에 맞게 간결하게 유지 시키기도 합니다. 거의 동일한 코드지만 각각의 권한에 맞게 컴포넌트를 나눠서 관리할 수 있긴해요.

2024-10-29 11:47 UTC, json9512 commented on components/Button.js
> +export default function createButton({ style }) {
다만, 이 방법도 당연히 단점이 많아서 (ex. 관리 포인트가 늘어남, 지속적인 분기 처리가 필요함 등) 그때 그때 상황에 따라 나누는 것 같습니다.