[이예린] Sprint8
codeit-sprint-fullstack/2-Sprint-Mission-FE pull request #148
Opened 2024-10-21 14:05 UTC by annylee0723

## 요구사항

### 기본

- [x]
- []
- []

### 심화

- [x]
- []

## 주요 변경사항

-
-

## 스크린샷

![image](이미지url)

## 멘토에게

-
-
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2024-10-24 12:30 UTC, MCprotein commented
@annylee0723 체크되어있는거는 다 하신건가요?

2024-10-24 16:16 UTC, annylee0723 commented
> @annylee0723 체크되어있는거는 다 하신건가요?

넵 ! 새 기능 추가하면서 이전 코드들도 조금씩 수정되고 있어서 아직 푸쉬하지 않았습니다🥲

2024-10-24 22:10 UTC, MCprotein commented
> 넵 ! 새 기능 추가하면서 이전 코드들도 조금씩 수정되고 있어서 아직 푸쉬하지 않았습니다🥲

아하 넵! 커밋 단위만 신경써주세요!

2024-10-25 08:39 UTC, MCprotein requested changes

2024-10-25 08:39 UTC, MCprotein commented on sprint8/src/components/AddComment.js
> +  };
@annylee0723 
1. postComment와 sendComment를 나눈 이유가 있으신가요?
2. postComment는 비동기함수라서 await 가 없으면 비동기적으로 작동하는데, await를 안붙인 이유가 있나요?
3. axios를 코드에 그대로 사용하기보다는 추상화를 해서 wrapper 함수를 만들어 사용하는게 좋아요 
그래야 해당 라이브러리 문제가 생기거나 라이브러리를 다른거로 교체할때 유지보수가 수월하고, 코드 수정시 한번에 통제할 수 있기때문이에요
wrapper 함수를 만드는 법은 검색해보거나 미션4 태영님꺼에 나와있으니 보고 수정해보세요

2024-10-25 08:39 UTC, MCprotein commented on sprint8/src/components/AddComment.js
> +    setIsButtonActive(comment.trim().length > 0);
@annylee0723 truthy, falsy 개념에 대해 검색해보고 코드를 수정해보세요

2024-10-25 08:39 UTC, MCprotein commented on sprint8/src/components/CommentList.js
> +      }
@annylee0723 이것도 axios를 추상화하면 try catch 를 wrapper 함수 안에 넣고 여기는 없어도돼요 
그리고 console.log 는 디버깅 후에 제거해주시고, try catch 를 쓸때 catch 에서 다시 throw 해주지 않으면 에러가 무시되니 다시 던져주세요

2024-10-25 08:39 UTC, MCprotein commented on sprint8/src/components/CreateEditPost.js
> +  // const [enterInput, setEnterInput] = useState(''); //이 또한 추후 삭제
@annylee0723 이런거는 TODO 주석으로 달아주세요. TODO 주석은 vscode extension도 많아서 편하니까 검색해보고 적용해보세요

2024-10-25 08:39 UTC, MCprotein commented on sprint8/src/components/CreateEditPost.js
> +  // }, [enterInput]);
@annylee0723 이건 무슨 주석인가요?

2024-10-25 08:39 UTC, MCprotein commented on sprint8/src/components/PostList.js
> +          <div key={index} className={style.container}>
@annylee0723 지금 key 에 index 넣는게 많은데, 아래 링크 보시겠어요?
https://www.google.com/search?q=react+key+index&rlz=1C5CHFA_enKR1040KR1040&oq=react+key+index&gs_lcrp=EgZjaHJvbWUqBwgAEAAYgAQyBwgAEAAYgAQyBwgBEAAYgAQyBwgCEAAYgAQyBwgDEAAYgAQyBwgEEAAYgAQyBwgFEAAYgAQyBwgGEAAYgAQyBwgHEAAYgAQyBwgIEAAYgAQyBwgJEAAYgATSAQg0MDM3ajBqN6gCALACAA&sourceid=chrome&ie=UTF-8

2024-10-25 08:39 UTC, MCprotein commented on sprint8/src/components/Sorting.js
> +        </div>
@annylee0723 이거 최신순 버튼이랑 오랜된순 버튼 컴포넌트를 만드는건 어떠세요? 제말이 무조건 맞다는게 아니니까 생각해보시고 별로면 아닌거같다고 말씀해주세요

2024-10-25 08:39 UTC, MCprotein commented on sprint8/src/lib/axios.js
> +  baseURL: 'https://sprint8back.onrender.com/'
@annylee0723 이거 왜 환경변수로 관리 안하고 하드코딩하셨나요?

2024-10-25 08:39 UTC, MCprotein commented on sprint8/src/pages/_document.js
> +          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.6/dist/web/static/pretendard.css"
@annylee0723 이건 왜 Npm 패키지 설치 안하고 이렇게 하셨나요? next.js 사용방법이 공식문서에 있는데 궁금하네요
https://github.com/orioncactus/pretendard?tab=readme-ov-file#nextjs

2024-10-25 08:39 UTC, MCprotein commented on sprint8/src/pages/free-board/[id].js
> +    }
여기도 위와 동일한 의견 드립니다

2024-10-25 08:39 UTC, MCprotein commented on sprint8/src/pages/free-board/create-post.js
> +    }
이렇게 하면 code block의 depth가 깊어져서 나중에 보기 어려울 수 있어요
아래처럼 early return pattern을 적용해보세요
```js
if (!title || !content) return

try {
  내용  
} catch (err) {
  내용
}
```

2024-10-25 08:39 UTC, MCprotein commented on sprint8/src/pages/free-board/create-post.js
> +    const data = { title: title, content: content };
@annylee0723 자바스크립트에서 object literal 방식으로 객체를 만들때 key와 value가 동일하다면 key만 입력해도돼요
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Object_initializer

```suggestion
    const data = { title, content };
```

2024-10-25 08:39 UTC, MCprotein commented on sprint8/src/pages/free-board/create-post.js
> +    }
@annylee0723 이건어떨까요?
```suggestion
    const isButtonActive = title && content
      setIsButtonActive(isButtonActive);
    }
```

2024-10-25 08:39 UTC, MCprotein commented on sprint8/src/pages/free-board/edit-post/[id].js
> +    const data = { title: title, content: content };
@annylee0723 여기도 Object literal 마찬가지 의견 드립니다

2024-10-25 08:39 UTC, MCprotein commented on sprint8/src/pages/free-board/edit-post/[id].js
> +    }
@annylee0723 여기도 위 코멘트들과 동일한 의견 남깁니다

2024-10-25 08:39 UTC, MCprotein commented on sprint8/src/pages/free-board/edit-post/[id].js
> +      console.log('title', title);
@annylee0723 console.log 는 디버깅 후 제거해주세요

2024-10-25 08:39 UTC, MCprotein commented on sprint8/src/pages/free-board/index.js
> +      `/articles?order=${order}&search=${searchKeyword}`
@annylee0723 요런거는 URLSearchParams 이용하면 더 깔끔하게 할 수 있을거같기도한데, 취향차이라 한번 보기만 해보세요!

2024-10-25 08:39 UTC, MCprotein commented on sprint8/src/pages/free-board/index.js
> +//Best 게시글은 고정된 값이니까 서버에서 받아올 수 있지 않을까? 싶어서 시도
@annylee0723 이게무슨말인가요?

2024-10-25 08:39 UTC, MCprotein commented on sprint8/src/pages/free-board/index.js
> +    };
@annylee0723 이거도 에러가 발생했으면 빈값을 내보내는게아니라 에러를 던져야돼요

2024-10-25 08:39 UTC, MCprotein commented on sprint8/src/utils/formatDate.js
> +}
@annylee0723 이런 날짜 변환은 dayjs, moment 같은 라이브러리로 편하게 할 수 있어요 한번 찾아보세요

2024-10-25 08:40 UTC, MCprotein commented
@annylee0723 코멘트 없는 코드도 다시 보면서 수정해주세요! 코멘트 달았던 코드와 동일한 내용인 코드중에 또 코멘트 안달은게 좀있어요!

2024-10-25 09:08 UTC, annylee0723 commented on sprint8/src/lib/axios.js
> +  baseURL: 'https://sprint8back.onrender.com/'
LMS 강의에서 알려준 방법으로 적용했습니다,,! api 디렉토리를 만들어서 api 처리 후 사용하는 방식 말씀하신게 맞을까용?

2024-10-25 09:14 UTC, MCprotein commented on sprint8/src/lib/axios.js
> +  baseURL: 'https://sprint8back.onrender.com/'
@annylee0723 아뇨 환경변수 .env 파일을 이용하는 방법을 말씀드린건데, 혹시 뭔지 모르시나요?

2024-10-25 09:14 UTC, annylee0723 commented on sprint8/src/pages/free-board/index.js
> +//Best 게시글은 고정된 값이니까 서버에서 받아올 수 있지 않을까? 싶어서 시도
Next.js를 최대한 활용해보고자 했습니다, 고정된 값이 렌더링 된다면 서버에서 데이터를 받아오는 방식이 괜찮지 않을까 싶어서 시도 해봤어요

2024-10-25 09:17 UTC, MCprotein commented on sprint8/src/pages/free-board/index.js
> +//Best 게시글은 고정된 값이니까 서버에서 받아올 수 있지 않을까? 싶어서 시도
@annylee0723 아하 넵 서버에서 가져오는게 맞아요 근데 지금은 articles api 를 사용하고있는데 그렇게하기보다는 베스트글 api 를 따로 만들어서 쓰는게 더 좋을거같아요

2024-10-26 12:37 UTC, annylee0723 commented on sprint8/src/components/PostList.js
> +          <div key={index} className={style.container}>
to-be: id 값 사용으로 키 밸류 수정 했습니다
commit: [90af74a](https://github.com/codeit-sprint-fullstack/2-Sprint-Mission-FE/pull/148/commits/90af74a78f863b61e0200ee976c05703eff4b7ac)

2024-10-26 13:06 UTC, annylee0723 commented on sprint8/src/pages/_document.js
> +          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.6/dist/web/static/pretendard.css"
해당 문서가 있는지 몰랐습니다, 로컬 폰트로 수정했습니다 
commit: [c89b66c](https://github.com/codeit-sprint-fullstack/2-Sprint-Mission-FE/pull/148/commits/c89b66c7cb3566623aeb65cbf461685644e4a9c8)

2024-10-26 13:13 UTC, annylee0723 commented on sprint8/src/components/Sorting.js
> +        </div>
음,, 보통 디자인 잡을 때 드롭박스는 조합이 아닌 하나의 컴포넌트로 취급하기도 하고, 분리해도 성능적으로 큰 차이가 없을 것 같아서(렌더링 횟수가 줄어들고 이런게 아니다보니, 틀렸으면 알려주세요8ㅅ8) 지금 방식을 유지하는게 나을거 같습니다,,!

2024-10-26 13:18 UTC, annylee0723 commented on sprint8/src/components/CreateEditPost.js
> +  // }, [enterInput]);
얘도 트러블 슈팅 때문에 작성했던 부분이라서 삭제 했습니다 (커밋 메세지에 추가했어야 했는데 잘못 남겼네요,,)
commit: [c89b66c](https://github.com/codeit-sprint-fullstack/2-Sprint-Mission-FE/pull/148/commits/c89b66c7cb3566623aeb65cbf461685644e4a9c8)

2024-10-26 13:50 UTC, annylee0723 commented on sprint8/src/components/CreateEditPost.js
> +  // const [enterInput, setEnterInput] = useState(''); //이 또한 추후 삭제
해당 주석은 삭제했지만 TODO extension 다운 받아서 사용법 익혔습니다. 되게 좋네요 bb

2024-10-26 13:57 UTC, annylee0723 commented on sprint8/src/pages/free-board/index.js
> +//Best 게시글은 고정된 값이니까 서버에서 받아올 수 있지 않을까? 싶어서 시도
아 이전 미션 요구사항에 없어서 좋아요 필드를 안만들었습니다,,, 이번 미션 요구사항에도 좋아요는 임의 값으로 프론트에서 처리하라고 나와있어서 베스트글 api는 따로 구현을 안했는데 새로 만들까요?

2024-10-26 14:00 UTC, annylee0723 commented on sprint8/src/pages/free-board/edit-post/[id].js
> +      console.log('title', title);
삭제 완료했습니다
commit: [b5d0589](https://github.com/codeit-sprint-fullstack/2-Sprint-Mission-FE/pull/148/commits/b5d0589a8594ce08a5b8f5145a8d6833f6095f2f)

2024-10-26 14:02 UTC, annylee0723 commented on sprint8/src/pages/free-board/index.js
> +    };
에러문 출력 로직으로 수정했습니다
commit: [1c12932](https://github.com/codeit-sprint-fullstack/2-Sprint-Mission-FE/pull/148/commits/1c12932bd6da7953c19bd0f9d1140d61192f4b54)

2024-10-26 14:02 UTC, annylee0723 commented on sprint8/src/utils/formatDate.js
> +}
dayjs 라이브러리 사용으로 수정했습니다 
commit: [428e859](https://github.com/codeit-sprint-fullstack/2-Sprint-Mission-FE/pull/148/commits/428e859c03e1df32b7f534be692a0cf074d8b293)

2024-10-26 14:51 UTC, annylee0723 commented on sprint8/src/components/AddComment.js
> +    setIsButtonActive(comment.trim().length > 0);
확인 후 적용 완료 했습니다 !
commit: [c9a7e95](https://github.com/codeit-sprint-fullstack/2-Sprint-Mission-FE/pull/148/commits/c9a7e95bdbff9b20eb3d707624a6e702ce3d213d)

2024-10-26 14:52 UTC, annylee0723 commented on sprint8/src/pages/free-board/create-post.js
> +    }
영감 받고 truthy falsy 적용 후 수정했습니다 
commit: [d71273e](https://github.com/codeit-sprint-fullstack/2-Sprint-Mission-FE/pull/148/commits/d71273e108012bf0f2d2f098cbba27a52f1177f6)

2024-10-26 15:27 UTC, annylee0723 commented on sprint8/src/lib/axios.js
> +  baseURL: 'https://sprint8back.onrender.com/'
아하 확인 후 수정했습니다 !
commit: [b3d1114](https://github.com/codeit-sprint-fullstack/2-Sprint-Mission-FE/pull/148/commits/b3d1114c9fb212068e721c5bff8ef85bbd3d5c79)

2024-10-26 15:28 UTC, annylee0723 commented on sprint8/src/pages/free-board/edit-post/[id].js
> +    const data = { title: title, content: content };
수정 완료 했습니다 !
commit: [f27c2d6](https://github.com/codeit-sprint-fullstack/2-Sprint-Mission-FE/pull/148/commits/f27c2d6064ed42b50e6bf559d9181b49bd5ac044)

2024-10-26 15:29 UTC, annylee0723 commented on sprint8/src/pages/free-board/create-post.js
> +    }
수정 완료했습니다 !
commit: [c9a7e95](https://github.com/codeit-sprint-fullstack/2-Sprint-Mission-FE/pull/148/commits/c9a7e95bdbff9b20eb3d707624a6e702ce3d213d)

2024-10-26 15:56 UTC, annylee0723 commented on sprint8/src/pages/free-board/create-post.js
> +    const data = { title: title, content: content };
수정 완료했습니다 !
commit: [f27c2d6](https://github.com/codeit-sprint-fullstack/2-Sprint-Mission-FE/pull/148/commits/f27c2d6064ed42b50e6bf559d9181b49bd5ac044)

2024-10-26 16:16 UTC, MCprotein commented on sprint8/src/components/CreateEditPost.js
> +  // const [enterInput, setEnterInput] = useState(''); //이 또한 추후 삭제
@annylee0723 넵 좋습니다!

2024-10-26 16:17 UTC, MCprotein commented on sprint8/src/components/PostList.js
> +          <div key={index} className={style.container}>
@annylee0723 넵 좋습니다!

2024-10-26 16:19 UTC, MCprotein commented on sprint8/src/components/Sorting.js
> +        </div>
@annylee0723 여러개의 컴포넌트가 모여 하나의 컴포넌트가 될 수도 있고, 저는 성능때문에 말씀드린건 아니에요
최신순, 오래된순 외에 더 많은 버튼이 생긴다면 각 버튼을 컴포넌트로 관리하면 좋을거같았는데 아직은 버튼이 2개밖에없어서 굳이 겠지만 버튼 개수가 많아진다면 한번 고려는 해보시는게 좋을거같아요

2024-10-26 16:21 UTC, MCprotein commented on sprint8/src/lib/axios.js
> +  baseURL: 'https://sprint8back.onrender.com/'
@annylee0723 넵 좋습니다!

2024-10-26 16:22 UTC, MCprotein commented on sprint8/src/pages/free-board/create-post.js
> +    }
@annylee0723 다른 커밋인거같은데.. 다른 코멘트 남길게요

2024-10-26 16:22 UTC, MCprotein commented on sprint8/src/pages/free-board/create-post.js
> +    const data = { title: title, content: content };
@annylee0723 넵 좋습니다!

2024-10-26 16:23 UTC, MCprotein commented on sprint8/src/pages/free-board/create-post.js
> +    }
@annylee0723 아.. 요거는 이렇게할필요가 없어요 코멘트 다시 남길게요

2024-10-26 16:23 UTC, MCprotein commented on sprint8/src/components/AddComment.js
> +    setIsButtonActive(comment.trim().length > 0);
@annylee0723 좀 다르게 이해하신거같은데 코멘트 다시 남길게요

2024-10-26 16:24 UTC, MCprotein commented on sprint8/src/pages/free-board/edit-post/[id].js
> +      console.log('title', title);
@annylee0723 넵 고생하셨습니다1

2024-10-26 16:24 UTC, MCprotein commented on sprint8/src/pages/free-board/index.js
> +//Best 게시글은 고정된 값이니까 서버에서 받아올 수 있지 않을까? 싶어서 시도
@annylee0723 아뇨 미션은 그냥 하시고 혹시 프로젝트하실때 이런 내용이 나오면 따로만드시는게 좋겠다는 의미였어요!

2024-10-26 16:25 UTC, MCprotein commented on sprint8/src/utils/formatDate.js
> +}
@annylee0723 넵 고생하셨스니다!

2024-10-26 16:28 UTC, MCprotein commented on sprint8/src/pages/_document.js
> +          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.6/dist/web/static/pretendard.css"
@annylee0723 넵 앞으로 공식문서도 같이 보는 습관을 기르시길 바랄게요! 고생하셨습니다!

2024-10-26 16:28 UTC, MCprotein commented on sprint8/src/pages/free-board/edit-post/[id].js
> +    const data = { title: title, content: content };
@annylee0723 넵 좋습니다!

2024-10-26 16:28 UTC, MCprotein commented on sprint8/src/pages/free-board/index.js
> +    };
@annylee0723 넵 좋습니다!

2024-10-26 16:36 UTC, MCprotein requested changes

2024-10-26 16:36 UTC, MCprotein commented on sprint8/src/components/AddComment.js
> +    setIsButtonActive(!!comment);
@annylee0723 기존에 `setIsButtonActive(comment.trim().length > 0);` 이걸 `setIsButtonActive(!!comment);` 이렇게 바꾸셨는데, optional chaining 에 대해 알고 계신가요?

2024-10-26 16:36 UTC, MCprotein commented on sprint8/src/pages/free-board/create-post.js
> +    if (!title || !content) return;
@annylee0723 `        ` 이건 true 판정인데, 고려해보셨나요?

2024-10-26 16:36 UTC, MCprotein commented on sprint8/src/pages/free-board/create-post.js
> +    setIsButtonActive(!!title && !!content);
@annylee0723 
```js

    if (title && content) {
      setIsButtonActive(true);
    } else {
      setIsButtonActive(false);
    }
```
위처럼 되어있는걸 바꾸셨는데, 느낌표를 사용하신 이유가 있나요?

2024-10-27 07:46 UTC, annylee0723 commented on sprint8/src/pages/free-board/edit-post/[id].js
> +    }
wrapper 함수로 빼서 수정 완료했습니다
commit: [7082286](https://github.com/codeit-sprint-fullstack/2-Sprint-Mission-FE/pull/148/commits/7082286982a1c4713c7a2e8a32c81a60516ae811)

2024-10-27 07:47 UTC, annylee0723 commented on sprint8/src/components/CommentList.js
> +      }
wrapper 함수 제작 후 수정 완료했습니다
commit: [7082286](https://github.com/codeit-sprint-fullstack/2-Sprint-Mission-FE/pull/148/commits/7082286982a1c4713c7a2e8a32c81a60516ae811)

2024-10-27 08:40 UTC, annylee0723 commented on sprint8/src/pages/free-board/create-post.js
> +    setIsButtonActive(!!title && !!content);
두개의 값이 모두 존재해야 true를 반환하는 로직을 생각하면서 첫번째 코드를 작성했습니다. truthy/falsy를 알게 된 후에 간결하게 작성해보고자 수정했습니다.

2024-10-27 08:41 UTC, annylee0723 commented on sprint8/src/components/Sorting.js
> +        </div>
오 알겠습니다 ! 사실 요구사항에서 최신순 정렬만 기재 해놔서 처음에 버튼 하나만 두다가 심심한거 같아서 오래된순 정렬을 추가한거였습니다,, 이번에는 냅두고 다음 미션 시행 시 버튼 두개 이상 요구사항에 있을 시 컴포넌트로 처리해도 될까요?

2024-10-27 08:45 UTC, annylee0723 commented on sprint8/src/components/AddComment.js
> +  };
1. 딱히 큰 이유 없었습니다 ,, onclick에서 바로 처리하도록 수정했습니다. commit: [ca3e7d3](https://github.com/codeit-sprint-fullstack/2-Sprint-Mission-FE/pull/148/commits/ca3e7d398940c30893ffa6103f1a090b5bcba985)
2. 함수 호출 기능만 생각해서 작성했습니다. postComment가 작동한 후에 추가적으로 실행해야 되는 함수가 없어서 위와 같이 사용 해도 상관 없다고 생각했었습니다. 비동기 함수 특징을 다시 고안해서 create-post의 라우터 호출을 다시 조정해봤습니다. commit: [ca3e7d3](https://github.com/codeit-sprint-fullstack/2-Sprint-Mission-FE/pull/148/commits/ca3e7d398940c30893ffa6103f1a090b5bcba985)
3. 수정 완료했습니다: [7082286](https://github.com/codeit-sprint-fullstack/2-Sprint-Mission-FE/pull/148/commits/7082286982a1c4713c7a2e8a32c81a60516ae811)

2024-10-27 08:49 UTC, annylee0723 commented on sprint8/src/pages/free-board/create-post.js
> +    if (!title || !content) return;
앗 작성해주신 부분이 안보입니다🥲

2024-10-27 08:58 UTC, annylee0723 commented on sprint8/src/components/AddComment.js
> +    setIsButtonActive(!!comment);
오 잘 모르던 개념이었습니다
일단 적용시켜봤는데 맞게 했을까요?
`comment가 null 또는 undefined인 경우, trim() 메서드는 호출되지 않음`을 고려했습니다.

commit: [cd8e2de](https://github.com/codeit-sprint-fullstack/2-Sprint-Mission-FE/pull/148/commits/cd8e2defdfe4792e73836177bf91cb732a8908f9)

2024-10-27 11:49 UTC, annylee0723 commented on sprint8/src/pages/free-board/create-post.js
> +    setIsButtonActive(!!title && !!content);
수정 완료했습니다
commit: [7386aaa](https://github.com/codeit-sprint-fullstack/2-Sprint-Mission-FE/pull/148/commits/7386aaa580b88c8ac1d9c4f3b561cd6c369c1374)

2024-10-27 11:49 UTC, annylee0723 commented on sprint8/src/pages/free-board/create-post.js
> +    if (!title || !content) return;
수정 완료 했습니다
commit: [7386aaa](https://github.com/codeit-sprint-fullstack/2-Sprint-Mission-FE/pull/148/commits/7386aaa580b88c8ac1d9c4f3b561cd6c369c1374)

2024-10-27 11:52 UTC, annylee0723 commented on sprint8/src/components/AddComment.js
> +    setIsButtonActive(!!comment);
수정 완료 했습니다
commit: [7386aaa](https://github.com/codeit-sprint-fullstack/2-Sprint-Mission-FE/pull/148/commits/7386aaa580b88c8ac1d9c4f3b561cd6c369c1374)

2024-10-28 08:16 UTC, MCprotein commented on sprint8/src/components/AddComment.js
> +  };
@annylee0723 넵 고생하셨습니다!

2024-10-28 08:17 UTC, MCprotein commented on sprint8/src/components/CommentList.js
> +      }
@annylee0723 넵 고생하셨습니다!

2024-10-28 08:18 UTC, MCprotein commented on sprint8/src/components/AddComment.js
> +    setIsButtonActive(!!comment);
@annylee0723 넵 고생하셨습니다! 그런데 제가 잘못알려드린게 있네요
empty string '' 일때 length 로 비교하든 그냥 비교하든 어차피 false 여서 length 로 할 필요가 없어요
혼란드려 죄송합니다 
일단 여기서는 냅두고 다음부터는 array일때만 length 비교 해보시죠!

2024-10-28 08:19 UTC, MCprotein commented on sprint8/src/pages/free-board/create-post.js
> +    if (!title || !content) return;
@annylee0723 넵 고생하셨습니다!

2024-10-28 08:19 UTC, MCprotein commented on sprint8/src/pages/free-board/create-post.js
> +    setIsButtonActive(!!title && !!content);
@annylee0723 넵 고생하셨습니다!

2024-10-28 08:19 UTC, MCprotein commented on sprint8/src/components/Sorting.js
> +        </div>
@annylee0723 넵 그러면 될거같아요! 고생하셨습니다!

2024-10-28 08:20 UTC, MCprotein commented on sprint8/src/pages/free-board/edit-post/[id].js
> +    }
@annylee0723 넵 고생하셨습니다1

2024-10-28 08:20 UTC, MCprotein approved these changes
@annylee0723 예린님 고생하셨습니다!

2024-10-30 13:25 UTC, merged