[김민선] Sprint8
codeit-sprint-fullstack/2-Sprint-Mission-FE pull request #151
Opened 2024-10-22 01:47 UTC by alscksdlek

## 기본 요구사항

### 공통
- [ ] Github에 스프린트 미션 PR을 만들어 주세요.
- [ ] Next.js를 사용해 진행합니다.

### 자유 게시판 페이지
- [ ] 게시글 목록에서 드롭다운을 사용하여 "최신 순"으로 정렬할 수 있도록 합니다.
- [ ] 본인이 이전 미션에서 생성한 게시글 목록 조회 API를 활용해 GET 메서드로 데이터를 가져옵니다.
- [ ] 게시글 제목에 검색어가 일부 포함되면 해당 게시글을 검색할 수 있도록 합니다.
- [ ] 이미지는 디폴트 이미지로 프론트엔드에서 처리해 주세요.
- [ ] 게시글 닉네임 및 좋아요 개수 역시 임의값으로 프론트엔드에서 처리해주세요.
- [ ] 베스트 게시글은 최신순 3개 게시글을 요청으로 데이터를 가져와 구현해주세요.
- [ ] 자유게시판 페이지에서 특정 게시글을 클릭하면 해당 게시물의 상세 페이지로 이동합니다.

### 게시글 등록 & 수정 페이지
- [ ] 각 input 필드에 정확한 placeholder 값을 입력합니다.
- [ ] 모든 input 필드에 값을 입력하면 '등록' 버튼이 활성화됩니다.
- [ ] 본인이 이전 미션에서 생성한 게시글 생성 API를 활용해 POST 메서드로 게시글을 등록합니다.
- [ ] '등록' 버튼을 누르면 해당 게시물 상세 페이지로 이동합니다.
- [ ] 게시글 수정 페이지 UI는 게시글 등록 페이지와 동일합니다.
- [ ] 본인이 이전 미션에서 생성한 게시글 상세 API의 PATCH 메소드를 사용하여 게시물을 수정합니다.

### 게시글 상세 페이지
- [ ] 본인이 이전 미션에서 생성한 게시글 상세 API의 GET 메소드를 사용하여 데이터를 가져옵니다.
- [ ] 본인이 이전 미션에서 생성한 게시글 상세 API의 DELETE 메소드를 사용하여 게시물을 삭제합니다.
- [ ] 댓글 input에 값을 입력하면 '등록' 버튼이 활성화됩니다.
- [ ] 본인이 이전 미션에서 생성한 댓글 생성 API를 활용해 POST 메소드로 댓글을 등록합니다.
- [ ] 본인이 이전 미션에서 생성한 댓글 생성 API를 활용해 PATCH 메소드로 댓글을 수정합니다.
- [ ] 본인이 이전 미션에서 생성한 댓글 생성 API를 활용해 DELETE 메소드로 댓글을 삭제합니다.

## 심화 요구사항
- [ ] 디자인 시안에 따라 반응형 디자인을 구현합니다.
- [ ] (생략 가능) 원한다면 지금까지 진행한 모든 React 코드를 Next.js로 마이그레이션 해주세요.
      (마이그레이션에 상당한 시간이 소요될 수 있으므로 진행을 권장하지 않습니다.)

## 스크린샷

![image](이미지url)

## 멘토에게
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2024-10-23 13:12 UTC, MCprotein requested changes

2024-10-23 13:12 UTC, MCprotein commented on components/BestPost.js
> +  }
@alscksdlek 혹시 truthy, falsy 개념에 대해서 아시나요?

2024-10-23 13:12 UTC, MCprotein commented on components/SearchBar.js
> +  };
@alscksdlek 이런 상황에서는 else 를 사용하지 않아도 돼요.
early return pattern에 대해서 검색해보세요.

2024-10-23 13:12 UTC, MCprotein commented on pages/community.js
> +
@alscksdlek api 요청보내는 부분은 이렇게 하기보다 axios를 한 번 wrapping 한 함수를 사용하고, 그 함수안에서 글로벌 에러 핸들링과 비슷하게 처리하는게 좋을거같아요
그리고 catch일때는 에러를 발생시켜야되는데 왜 빈값을 return 하게 하셨나요?

2024-10-23 17:35 UTC, alscksdlek commented on components/BestPost.js
> +  }
개념은 알지만  truthy, falsy 각각에 뭐가 해당하는지 정확히는 모릅니다

2024-10-23 17:38 UTC, alscksdlek commented on components/SearchBar.js
> +  };
if (windowWidth > 743 || windowWidth < 375) {
    setSmallSize(false);
    return;
  } 이렇게 수정하도록 하겠습니다!

2024-10-23 17:46 UTC, alscksdlek commented on components/SearchBar.js
> +  };
```
  const handleResize = () => {
    const windowWidth = window.innerWidth;
    if (windowWidth <= 743 && windowWidth >= 375) {
      setSmallSize(true);
      return;
    }
    setSmallSize(false);
  }; 
```
이렇게 수정하였습니다!

2024-10-23 18:11 UTC, alscksdlek commented on pages/community.js
> +
시도해봤는데 잘 안되네요 ..ㅠ 댓글 목록을 가져올 때 다시 한번 시도해보겠습니다 음 뭔가 오류가 발생했으니 빈 배열을 주면 문구가 나타나니깐 오류가 났다는 걸 보여주고 싶었던 것 같습니다

2024-10-24 06:17 UTC, MCprotein commented on components/BestPost.js
> +  }
@alscksdlek 한번 찾아보시고 코드 수정 해보시겠어요?

2024-10-24 06:19 UTC, MCprotein commented on pages/community.js
> +
@alscksdlek axios wrapping 하는게 잘안된다는건가요?

2024-10-25 08:41 UTC, MCprotein requested changes

2024-10-25 08:41 UTC, MCprotein commented on lib/axios.js
> +  baseURL: "https://two-sprint-mission-be-yj7h.onrender.com",
@alscksdlek 민선님도 이거 왜 환경변수로 관리 안하고 하드코딩 하셨나요?

2024-10-26 16:40 UTC, alscksdlek commented on pages/community.js
> +
axios wrapping 해서 데이터를 가져올 때 잘 안됐었는데 해결했습니다! 에러 함수가 너무 부실한 것 같은데 어떤 식으로 작성하면 좋을지 잘 모르겠습니다 나중에 코드를 올리면 한 번 봐주시면 감사하겠습니다!

2024-10-26 16:43 UTC, alscksdlek commented on lib/axios.js
> +  baseURL: "https://two-sprint-mission-be-yj7h.onrender.com",
코드잇 강의에서 배운대로 했습니다 지금보니 env 파일에 넣어야 될 것 같네요,, 혹시 맞을까요?

2024-10-26 16:45 UTC, MCprotein commented on pages/community.js
> +
@alscksdlek 코드 언제올리실건가요??

2024-10-26 16:46 UTC, MCprotein commented on lib/axios.js
> +  baseURL: "https://two-sprint-mission-be-yj7h.onrender.com",
@alscksdlek 코드잇 강의에 나온거는 정말 기초적인거고, 그거대로만 하면 안돼요
내부 api 주소는 노출되면 안되기때문에 말씀하신대로 env 환경변수 처리해야돼요

2024-10-26 16:46 UTC, alscksdlek commented on pages/community.js
> +
이제부터 밤새하고 아침이나 점심쯤에 올릴 것 같습니다! 일단 지금 대충 적은거라도  push 할까요? 에러함수는 더 추가하려구요

2024-10-26 19:00 UTC, alscksdlek commented on lib/axios.js
> +  baseURL: "https://two-sprint-mission-be-yj7h.onrender.com",
처리했습니다!

2024-10-27 05:42 UTC, MCprotein commented on lib/axios.js
> +  baseURL: "https://two-sprint-mission-be-yj7h.onrender.com",
@alscksdlek nextjs에서 환경변수 처리하는 방식이 따로 있을텐데, process.env 로 설정해도 잘 작동하나요?
예린님 커밋 참고해보세요

sprint8/src/lib/axios.js 파일
https://github.com/codeit-sprint-fullstack/2-Sprint-Mission-FE/pull/148/files

2024-10-28 09:04 UTC, alscksdlek commented on lib/axios.js
> +  baseURL: "https://two-sprint-mission-be-yj7h.onrender.com",
네 작동은 되더라구요 
```
 import axios from "axios";

const instance = axios.create({
  baseURL: process.env.NEXT_PUBLIC_API_SERVER,
});

export default instance;
```
수정하였습니다!

2024-10-28 09:09 UTC, alscksdlek commented on components/BestPost.js
> +  }
개념은 찾아봤는데 어떻게 적용해야 할지 모르겠습니다.. ㅠ

2024-10-28 13:21 UTC, MCprotein commented on lib/axios.js
> +  baseURL: "https://two-sprint-mission-be-yj7h.onrender.com",
@alscksdlek 넵민선님 고생하셨습니다1

2024-10-28 13:21 UTC, MCprotein commented on components/BestPost.js
> +  }
@alscksdlek 이 내용은 따로 말씀드릴게요

2024-10-30 13:29 UTC, MCprotein approved these changes
@alscksdlek 민선님 고생하셨습니다!

2024-10-30 13:29 UTC, merged