[서지우] sprint1
codeit-sprint-fullstack/2-Sprint-Mission-FE pull request #16
Opened 2024-08-07 06:09 UTC by JiwooFS

## 요구사항

### 기본

- [x]
- []
- []

### 심화

- [x]
- []

## 주요 변경사항

-
-

## 스크린샷

![image](이미지url)

## 멘토에게

-
-
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2024-08-07 09:59 UTC, MCprotein commented on SprintStyle.css
> +.구경하러가기 {
@JiwooFS 
한글컨벤션을 사용하는것 자체에는 문제가 없다고 생각하지만, 일부분에만 한글을 쓰신 이유가 있을까요?

2024-08-07 10:03 UTC, MCprotein requested changes

2024-08-07 10:03 UTC, MCprotein commented on SprintStyle.css
> +.letsgo {
@JiwooFS 두 단어로 이루어진 이름은 이렇게 붙여쓰는것보다는 delimiter를 넣어주는게 좋을거같아요.
전체적으로 이렇게 쓴것과 kebab-case를 쓴게 공존하는데, 명확한 이유와 기준이 없다면 하나로 통일하는게 좋아요.
ex) sellproduct, footer-content
가이드 문서 공유드릴테니 참고해서 수정부탁드려요! 
https://google.github.io/styleguide/htmlcssguide.html#ID_and_Class_Name_Delimiters
https://blog.sonim1.com/221

2024-08-07 10:03 UTC, MCprotein commented on SprintStyle.css
> +.SNS {
@JiwooFS faq와 SNS 모두 줄임말인데, naming convention이 통일이 안됐어요. 이부분도 확인부탁드릴게요!

2024-08-07 10:04 UTC, MCprotein commented on login/index.html
> +            <p style = "font-size: 18px; line-height: 21.48px; font-weight: 700px;top: 16px">이메일<br></style>
@JiwooFS 전체적으로 보면 css 파일이 아니라 이렇게 태그 내부에 style 로 존재하는부분이 많은데, 이렇게 하신 이유가 있을까요?

2024-08-07 10:08 UTC, MCprotein requested changes

2024-08-07 10:08 UTC, MCprotein commented on login/index.html
> +            <input type = "email" placeholder = "이메일을 입력해주세요" />
@JiwooFS 이부분은 지원님 PR에서 말씀드렸던 부분인데, input 태그를 쓸때는 label 태그와 함께 써주는게 더 좋을거같네요! 
해당 comment 링크 공유드릴테니 참고해서 수정해보세요!
https://github.com/codeit-sprint-fullstack/2-Sprint-Mission-FE/pull/10#discussion_r1705437612

2024-08-07 13:30 UTC, MCprotein commented
@JiwooFS 
지우님! 따로 문의하신  `화면의 너비가 1920px 이상이면 내부에 있는 요소 간 동일한 간격을 유지하며 가운데 정렬해야 합니다.` 요구사항에 대한 header, footer 부분 답변드릴게요! 

## footer 
일단 더 간단한 footer부터 보면, footer class를 준 div tag안에 footer-content class div가 있잖아요
그러면 footer-content class div를 감싸고 있는 footer class div 에다가 아래 옵션을 줘야 footer-content class div요소들이 가운데 정렬을 해요
```css
.footer {
    display: flex;
    justify-content: center;
}
```
그리고 1920px 이상일때 각 요소가 멀어지는것을 방지하기 위해 max-width를 설정하고, max-width를 전부 사용하도록 width: 100%를 설정하면 돼요! justify-content 이거는 space-between이 더 좋을거같긴한데, 마음에 드는걸로 해도 될거같아요
```css
.footer-content {
    display: flex;
    flex-direction: row;
    justify-content: space-around;
    align-items: flex-start;
    width: 100%;
    max-width: 1920px;
}
```

## header
이제 header를 봐보면, 여기는 footer와는 다르게 header tag 아래에 바로 a tag가 있어요.
좀 간단하게 하기 위해서 div tag로 한번 감싸줄게요
```html
            <div class="header-temp">
                <a href = "index.html"><img src = "/images/panda.png" class = "panda"></a>
                <a href = "/login" class = "login">로그인</a>
            </div>
```
이후에는 footer와 동일하게 하면 되는데, header tag에서 justify-content: center로 주고, header-temp class에다가 max-width, width: 100% 설정하구요. 즉, header-temp는 footer-content와 동일하게 하면돼요
```css
header {
    height: 70px;
    width: 100%;
    display: flex;
    align-items: center;
    background-color: white;
    z-index: 1;
    justify-content: center;
    padding: 0 200px;
}

header > .header-temp {
    max-width: 1920px;
    width: 100%;
    display: flex;
    justify-content: space-between;
}
```

---

참고해서 수정 해주시구요! 
다음부터 PR 올린 후에 질문사항이 있으면 PR 코멘트로 부탁드려요!

2024-08-07 13:48 UTC, MCprotein commented
전체적으로 formatter 설정이 안되어있는거같은데 이부분 함 확인부탁드려요~

Ref: https://in-future.tistory.com/103

2024-08-08 04:07 UTC, JiwooFS commented on SprintStyle.css
> +.구경하러가기 {
헉... 그냥 생각나는데로 적다보니 그렇게 되었습니다.. 다음부턴 영어로 통일해서 해보겠습니다!

2024-08-08 04:12 UTC, JiwooFS commented on SprintStyle.css
> +.SNS {
넵 수정하겠습니다!

2024-08-08 04:27 UTC, JiwooFS commented on login/index.html
> +            <p style = "font-size: 18px; line-height: 21.48px; font-weight: 700px;top: 16px">이메일<br></style>
뭔가 짧게 느껴지는 것들을 그렇게 했던거 같은데, 역시 CSS파일에 다 정리해서 써놓는게 좋을까요..?

2024-08-08 04:52 UTC, MCprotein commented on SprintStyle.css
> +.구경하러가기 {
@JiwooFS 스프린트 미션마다 다른 프로젝트를 하는게 아니고 계속 같은 프로젝트에 기능을 추가하는 방식이라서 이번에 수정하는게 좋을거같아요!

2024-08-08 04:54 UTC, MCprotein commented on login/index.html
> +            <p style = "font-size: 18px; line-height: 21.48px; font-weight: 700px;top: 16px">이메일<br></style>
@JiwooFS 네 지금은 짧게 느껴질 수도 있지만, 계속 코드를 추가 작성하다보면 방대해질수도 있어요. 그리고 css 요소를 재사용해야될때가 있을수도 있어서 웬만하면 inline보다는 파일에 따로 명시하는게 좋을거같아요!

2024-08-08 04:56 UTC, MCprotein commented on SprintStyle.css
> +.letsgo {
@JiwooFS naming convention을 그냥 소문자만 있는 형식으로 바꾸셨는데, kebab-case로 변경해주세요! 일반적으로 css 요소는 kebab-case를 사용하기때문에 해당 생태계에 맞는 convention을 따르는게 좋아요. 지금은 혼자 코드를 작성해서 중요성을 잘 못느끼시겠지만, 나중에 다른사람들과 협업할때 각자 사용하는 convention이 다르면 의견 조율하는거부터 힘이 빠지고 시간이 소요되거든요.

2024-08-08 05:01 UTC, JiwooFS commented on SprintStyle.css
> +.구경하러가기 {
아하 알겠습니다!

2024-08-08 05:08 UTC, JiwooFS commented on SprintStyle.css
> +.letsgo {
login 과 signup 같은경우 뭔가 -를 넣기 불편해서 그냥 나머지를 다 붙여버렸는데 혹시 이 아이들도 -를 넣는게 좋을까요...?

2024-08-08 05:36 UTC, JiwooFS commented on login/index.html
> +            <p style = "font-size: 18px; line-height: 21.48px; font-weight: 700px;top: 16px">이메일<br></style>
class로 묶어서 CSS 파일에 명시했습니다

2024-08-08 05:46 UTC, JiwooFS commented on SprintStyle.css
> +.구경하러가기 {
영어로 통일했습니다!

2024-08-08 05:55 UTC, JiwooFS commented on login/index.html
> +            <input type = "email" placeholder = "이메일을 입력해주세요" />
p태그를 label태그로 수정했습니다

2024-08-08 06:47 UTC, JiwooFS commented
전체적으로 수정 완료했습니다. 혹시 formatter는 그냥 적용만 시키면 되는걸까요? 아니면 어떤걸 더 추가야 할까요?

2024-08-08 07:35 UTC, MCprotein commented on SprintStyle.css
> +.letsgo {
@JiwooFS login, signup 같은건 괜찮아보입니다! 다만 나중에도 이 규칙을 잊지 않도록 주의해주세요!

2024-08-08 08:04 UTC, JiwooFS commented on SprintStyle.css
> +.letsgo {
넵 주의하겠습니다! 마지막에 코멘트 확인 부탁드려요!

2024-08-08 11:45 UTC, MCprotein commented
> 전체적으로 수정 완료했습니다. 혹시 formatter는 그냥 적용만 시키면 되는걸까요? 아니면 어떤걸 더 추가해야 할까요? 그리고 혹시 심화 요구사항도 지금 충족시켜야 하나요?

@JiwooFS 넵 지우님! 고생하셨습니다!
formatter는 vscode 상에서 적용하면 되구요, 심화요구사항은 전 전달받은게 없어서 모르겠네요. 매니저님들께 여쭤보셔야될거같아요!

2024-08-08 11:49 UTC, MCprotein requested changes

2024-08-08 11:49 UTC, MCprotein commented on signup/index.html
> +                <input type="password" id="pw-box" name="pw-box" placeholder="비밀번호를 다시 한 번 입력해주세요" />
@JiwooFS 
id는 unique value여야합니다
이렇게하면 나중에 비밀번호 확인쪽은 작동안할거에요
확인 부탁드려요!

2024-08-08 11:49 UTC, MCprotein commented on SprintStyle.css
> +    padding: 12px, 23px;
@JiwooFS 여기 , 가 들어갔네요! 오타인가요??
Ref: https://developer.mozilla.org/ko/docs/Web/CSS/padding

2024-08-09 00:32 UTC, JiwooFS commented on SprintStyle.css
> +    padding: 12px, 23px;
수정했습니다!

2024-08-09 00:41 UTC, JiwooFS commented on signup/index.html
> +                <input type="password" id="pw-box" name="pw-box" placeholder="비밀번호를 다시 한 번 입력해주세요" />
비밀번호 확인에 있는 input의 id를 pw-check 로 수정했습니다!

2024-08-09 10:27 UTC, MCprotein commented
@JiwooFS 고생하셨습니다! 배포만 최신으로 다시해주세요!

2024-08-10 04:49 UTC, JiwooFS commented
넵 감사합니다!

2024-08-10 17:37 UTC, MCprotein commented
@JiwooFS 지우님! 고생하셨습니다!

2024-08-10 17:37 UTC, merged

2024-08-13 12:41 UTC, MCprotein commented on index.html
> +    <title>pandamarket</title>
@JiwooFS 지우님! 요거 제가 놓쳤는데, 요구사항에 판다마켓 으로되어있어서 한글로써주셔야돼요!

2024-08-14 01:38 UTC, JiwooFS commented on index.html
> +    <title>pandamarket</title>
앗 넵 스프린트 미션 3 할때 수정하겠습니다