Next 김태연 sprint8
codeit-sprint-fullstack/2-Sprint-Mission-FE pull request #160
Opened 2024-10-27 11:14 UTC by taeyeonkim94

## 요구사항

### 기본

- [x]
- []
- []

### 심화

- [x]
- []

## 주요 변경사항

-
-

## 스크린샷

![image](이미지url)

## 멘토에게

-
-
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2024-10-27 11:55 UTC, MCprotein commented
@taeyeonkim94 태연님 vercel 링크 눌렀는데 로그인창이 뜨네요 확인한번부탁드려요

2024-10-28 08:47 UTC, MCprotein requested changes

2024-10-28 08:47 UTC, MCprotein commented on components/CommentItem.js
> +  const patchCompleteBtn = `w-[106px] h-[42px] px-[23px] py-[12px] flex items-center text-f3f4f6 rounded-[8px] border-none bg-3692ff`;
@taeyeonkim94 코드 전체적으로 볼때 css를 다 자바스크립트 레벨에서 하드코딩해놓으셨는데 이렇게 하신 이유가 있나요?

2024-10-28 08:47 UTC, MCprotein commented on components/CommentItem.js
> +    console.log(chosenOption);
@taeyeonkim94 console.log는 디버깅 후 제거해주세요

2024-10-28 08:47 UTC, MCprotein commented on components/CommentItem.js
> +  };
@taeyeonkim94 태연님도 axios 그대로 사용하지 마시고, 미션4 태영님 pr 보고 axios 추상화해서 wrapper 함수를 사용해보세요

2024-10-28 08:47 UTC, MCprotein commented on components/CommentItem.js
> +      <div className={commentHeader1}>
@taeyeonkim94 맨뒤에 1은 왜붙은건가요?

2024-10-28 08:47 UTC, MCprotein commented on components/EditDeleteDropDown.js
> +              key={index}
@taeyeonkim94 리스트에서 key 에다가 인덱스를 안넣는게 좋아요. 이유와 해결방법은 검색해보세요.

2024-10-28 08:47 UTC, MCprotein commented on components/EditDeleteDropDown.js
> +  const items = ["수정하기", "삭제하기"];
@taeyeonkim94 이렇게 하기보다는 아래처럼 하는게 더 좋을거같아요.
이유는 아래 코멘트와 함께 생각해보세요
```suggestion
const items = [
  {key: 'edit', field: '수정하기'},
  {key: 'delete', field: '삭제하기'},
]
```

2024-10-28 08:47 UTC, MCprotein commented on components/Section.js
> +    return (
@taeyeonkim94 여기 if 안에 return 이 있으면 아래에 else나 else if 가 없어도 돼요. 왜 그런지는 한 번 생각해보고 잘 모르겠으면 말씀해주세요

2024-10-28 08:47 UTC, MCprotein commented on components/Section.js
> +  const selectClass = (name) => {
@taeyeonkim94 이거 name을 하드코딩 하는게아니라 Object.freeze로 enum처럼 관리하는게 더 좋을거같아요

2024-10-28 08:47 UTC, MCprotein commented on components/ValidatedInputBox.js
> +  const convertClass = (type) => {
@taeyeonkim94 여기도 type을 enum 처럼 관리하는게 좋아보이네요

2024-10-28 08:47 UTC, MCprotein commented on hooks/useDataFetch.js
> +    const dataFetch = async () => {
@taeyeonkim94 fetch 를 어떤 의미로 사용하신건가요?

2024-10-28 08:47 UTC, MCprotein commented on hooks/useDataFetch.js
> +  return data || {};
@taeyeonkim94 여기다가 말고, setData(response.data || {}) 이렇게하는건 어떠세요?
여기다가 하면 return 값과 data값이 달라지게 되서 의도하지않은 결과가 발생할수도있을거같아요

2024-10-28 08:47 UTC, MCprotein commented on hooks/useDataFetchNew.js
> +    switch (type) {
@taeyeonkim94 이것도 enum 으로 관리하는게 좋을거같아요

2024-10-28 08:47 UTC, MCprotein commented on hooks/useDataFetchNew.js
> +      console.log(url);
@taeyeonkim94 console.log는 지워주세요

2024-10-28 08:47 UTC, MCprotein commented on hooks/useDataFetchNew.js
> +    const dataFetch = async () => {
@taeyeonkim94 위 코멘트와 동일한 의견 드립니다

2024-10-28 08:47 UTC, MCprotein commented on pages/freeboard/[id].js
> +  };
@taeyeonkim94 여기도 다른 코멘트 보고 수정해주시고 try catch 를 제거하거나 에러를 throw 하도록 변경해주세요
console.log 만 있으면 에러가 무시돼요

2024-10-28 08:47 UTC, MCprotein commented on pages/freeboard/[id].js
> +    }
@taeyeonkim94 여기도 에러 처리 코드 수정해주세요

2024-10-28 08:47 UTC, MCprotein commented on pages/freeboard/[id].js
> +    }
@taeyeonkim94 여기도 에러 처리코드 수정해주세요

2024-10-28 08:47 UTC, MCprotein commented on pages/freeboard/write/[[...slug]].js
> +    const url = editMode ? `/articles/${slug}` : "/articles";
@taeyeonkim94  생성, 수정은 다른 컴포넌트로 분리하는게 좋아요
지금은 똑같은 값을 다루기때문에 이렇게 하신거같은데, 데이터가 더 복잡해지면 다루는 값이 달라질 수 있기때문에 코드가 더 복잡해질거에요

2024-10-28 08:47 UTC, MCprotein commented on pages/freeboard/write/[[...slug]].js
> +    }
@taeyeonkim94 여기도 에러처리코드 수정해주세요

2024-10-28 08:47 UTC, MCprotein commented on pages/freeboard/write/[[...slug]].js
> +    }
@taeyeonkim94 여기도 에러처리코드 수정해주세요

2024-10-28 08:47 UTC, MCprotein commented on pages/freeboard/write/[[...slug]].js
> +        }
@taeyeonkim94 에러 처리 코드 수정해주세요

2024-10-28 08:47 UTC, MCprotein commented on pages/freeboard/write/[[...slug]].js
> +            {editMode ? "수정" : "생성"}
@taeyeonkim94 이런 조건문이 지금 중복으로 많이쓰이는데, 함수로빼면 좋을거같아요

2024-10-28 08:47 UTC, MCprotein commented on pages/items/index.js
> +        setProductsList([]);
@taeyeonkim94 에러가 발생하면 빈값을 내보내는게 아니라 에러를 던져서 적절하게 에러를 핸들링해야돼요

2024-10-28 08:47 UTC, MCprotein commented on pages/items/index.js
> +  }, [pageSize]);
@taeyeonkim94 이건 디버깅용 코드인가요?

2024-10-28 08:47 UTC, MCprotein commented on pages/register.js
> +  };
@taeyeonkim94 이거 index 말고 다른 unique key로 할 수는 없을까요?

2024-10-28 08:47 UTC, MCprotein commented on pages/register.js
> +      }
@taeyeonkim94 이런거는 정규표현식보다는 isNaN 이나 Number.isSafetyInteger 같은걸 사용하는게 더 좋을거같아요

2024-10-28 08:47 UTC, MCprotein commented on utils/convertDate.js
> +}
@taeyeonkim94 태연님 https://github.com/codeit-sprint-fullstack/2-Sprint-Mission-FE/pull/148#discussion_r1816263590 요거 참고해서 수정해주세요.

2024-10-28 09:09 UTC, taeyeonkim94 commented on components/CommentItem.js
> +      <div className={commentHeader1}>
시간에 쫓기다 보니 수정을 제대로 못했습니다 ㅠㅠ

2024-10-29 00:26 UTC, taeyeonkim94 commented on components/CommentItem.js
> +    console.log(chosenOption);
넵

2024-10-29 00:26 UTC, taeyeonkim94 commented on components/CommentItem.js
> +  };
넵

2024-10-29 00:29 UTC, taeyeonkim94 commented on components/EditDeleteDropDown.js
> +              key={index}
드랍다운메뉴 리스트는 삭제되거나 요소의 이름이 변경 될 일이 없다보니 인덱스를 활용했습니다.
고치겠습니다

2024-10-29 00:31 UTC, taeyeonkim94 commented on pages/items/index.js
> +        setProductsList([]);
제가 에러찾으면서 짯던 코드인거같은데 고치겠습니다

2024-10-29 00:31 UTC, taeyeonkim94 commented on pages/items/index.js
> +  }, [pageSize]);
이거도 페이지쪽에서 문제가 생겼어서 에러찾기용 코드입니다 죄송합니다 ㅠㅠ

2024-10-29 00:32 UTC, taeyeonkim94 commented on pages/register.js
> +  };
테그의 이름으로 변경하겠습니다

2024-10-29 00:32 UTC, taeyeonkim94 commented on pages/register.js
> +      }
넵

2024-10-29 04:11 UTC, taeyeonkim94 reviewed
1

2024-10-29 04:11 UTC, taeyeonkim94 commented on components/Section.js
> +  const selectClass = (name) => {
한번 찾아서 해보겠습니다

2024-10-29 04:11 UTC, taeyeonkim94 commented on components/Section.js
> +    return (
어짜피 if문에서 리턴이 나오면 끝나서 다음 코드로 넘어가지 않기 떄문이겠네요 고치겠습니다

2024-10-29 04:11 UTC, taeyeonkim94 commented on hooks/useDataFetch.js
> +    const dataFetch = async () => {
많은 페이지들이 처음에 데이터를 가져와야되기떄문에 공통된 훅을 만들고 싶었고 단순하게 데이터를 가져오는 훅이라고 생각해서 useDataFetch, dataFetch라는 이름을 썻습니다,
이름에 문제가 될까요?

2024-10-29 04:11 UTC, taeyeonkim94 commented on hooks/useDataFetch.js
> +  return data || {};
넵 아마 이거도 초기 페이지 사이즈 값이 제대로 들어오지 않아서 해결하다보니 붙은거 같네요 ㅠㅠ
아마 count의 디폴트값을 없애고 if(count)dataFetch();로 실행하면 data || {};나 setData(response.data || {}) 처럼 값이 없을 경우를 생각하지 않아도 될까요?

2024-10-29 04:11 UTC, taeyeonkim94 commented on hooks/useDataFetchNew.js
> +    switch (type) {
넵

2024-10-29 04:11 UTC, taeyeonkim94 commented on pages/freeboard/[id].js
> +  };
트라이캐치문의 의의에 대해 의문점을 많이 가지던 상황이였는데 멘토님에게 질문하려다보니 스스로 정리가 된 느낌입니다.
트라이매치문 : 프로그램이 원치않게 종료되지 않게 하고 문제가 생겼음을 알려준다.
유효성 검증 같은 경우에는 사용자의 입력값이 잘못됐기 때문에 올바른 입력값을 입력하도록 유도하기 때문에 필요한 이유를 알기 쉬웠지만
위의 코드 같은 경우에는 사용자가 뭘 할 수 있는 상황이 아니기 떄문에 디버깅 용도 외에는 이해가 잘 가지 않았습니다 
만약 트라이캐치문이 저기 코드에서 필요하다면 현재 사이트에 문제가 생겼음을 에러메시지를 변환해서 사용자에게 얼럿이나 모달 같은 방식으로 알리는 용도라고 생각하면 될까요?

2024-10-29 04:11 UTC, taeyeonkim94 commented on pages/freeboard/write/[[...slug]].js
> +    const url = editMode ? `/articles/${slug}` : "/articles";
코드가 90프로쯤 똑같다고 생각해서 공통 컴포넌트로 구현했는데 다루는 값이 달라진다는 의미가 어떤 경우인지 알 수 있을까요? 예를 들어 생성시에만 다루는 데이터가 있다든지 하는 경우인가요? 수정시에는 다룰 수 없는 부분이라던가?

2024-10-29 04:11 UTC, taeyeonkim94 commented on pages/freeboard/[id].js
> +  };
에러를 thorw 하는건 이유가 어떤건가요? 제가 이해하기로는 보통 캐치문에서 에러를 thorw를 하는 이유는  내부 에러메시지를 밖으로 알리지 않고 에러메시지를 직관적으로 바꾸거나 더 상위코드에서 에러를 처리하기 위해서라고 이해했는데 똑같은 의미라고 생각하면 될까요?

2024-10-29 08:40 UTC, taeyeonkim94 commented on pages/freeboard/[id].js
> +  };
트라이캐치문의 의의에 대해 의문점을 많이 가지던 상황이였는데 멘토님에게 질문하려다보니 스스로 정리가 된 느낌입니다.
트라이매치문 : 프로그램이 원치않게 종료되지 않게 하고 문제가 생겼음을 알려준다.
유효성 검증 같은 경우에는 사용자의 입력값이 잘못됐기 때문에 올바른 입력값을 입력하도록 유도하기 때문에 필요한 이유를 알기 쉬웠지만
위의 코드 같은 경우에는 사용자가 뭘 할 수 있는 상황이 아니기 떄문에 디버깅 용도 외에는 이해가 잘 가지 않았습니다
만약 트라이캐치문이 저기 코드에서 필요하다면 현재 사이트에 문제가 생겼음을 에러메시지를 변환해서 사용자에게 얼럿이나 모달 같은 방식으로 알리는 용도라고 생각하면 될까요?

2024-10-29 08:44 UTC, MCprotein commented on components/CommentItem.js
> +  const patchCompleteBtn = `w-[106px] h-[42px] px-[23px] py-[12px] flex items-center text-f3f4f6 rounded-[8px] border-none bg-3692ff`;
tailwind는 inline style로 사용해야함

2024-10-29 08:45 UTC, MCprotein commented on hooks/useDataFetch.js
> +    const dataFetch = async () => {
@taeyeonkim94 행위가 함수 이름에 나타나있는게 좋은데, fetch는 get method과 동일한 의미로 사용되지 않는것같아서 좀더 명확한 이름으로 수정하는게 좋을거같아요

2024-10-29 08:47 UTC, MCprotein commented on hooks/useDataFetch.js
> +  return data || {};
@taeyeonkim94 아뇨 count 는 클라이언트에서 다루는 값이고, dataFetch로 넘어온 response 는 서버에서 준 값이니 다를 수 있다고 생각해야돼요

2024-10-29 08:52 UTC, MCprotein commented on pages/freeboard/[id].js
> +  };
@taeyeonkim94 
> 위의 코드 같은 경우에는 사용자가 뭘 할 수 있는 상황이 아니기 떄문에 디버깅 용도 외에는 이해가 잘 가지 않았습니다
만약 트라이캐치문이 저기 코드에서 필요하다면 현재 사이트에 문제가 생겼음을 에러메시지를 변환해서 사용자에게 얼럿이나 모달 같은 방식으로 알리는 용도라고 생각하면 될까요?

넵 저도 말씀하신걸 생각했어요

에러를 throw 하라고 말씀드린건, 각각의 catch 에서 수행해야될 작업을 진행하고, 에러를 그 상위 레벨로 올려 전역적으로 처리하기 위함이에요. catch 코드가 많이 있을텐데, 이 코드 각각 하는 행동이 명시되어있다면 관리하기가 굉장히 까다로워질거에요. 예를들면 다른곳과 같은 팝업을 띄워줘야하는데, 예전에 했던게 기억이안나서 토스트메세지를 띄운다거나 redirect 한다거나.. 이러면 코드 전체적으로 일관성이 없어져서 스파게티코드가 될 수 있어요

2024-10-29 08:54 UTC, MCprotein commented on pages/freeboard/write/[[...slug]].js
> +    const url = editMode ? `/articles/${slug}` : "/articles";
@taeyeonkim94 네 맞아요
예를들어 게시글을 생성할때는 게시글이 어떤 게시판에 존재할지 정할 수 있지만 수정할때는 게시판을 수정하지못한다고 가정해봐요
혹은 생성할때는 자동으로 생성되는 데이터인데, 수정할때는 사용자가 변경할 수 있는 데이터가 있을수도 있어요

2024-10-30 13:35 UTC, MCprotein approved these changes
@taeyeonkim94 태연님 고생하셨습니다!

2024-10-30 13:35 UTC, merged

2024-11-02 14:11 UTC, taeyeonkim94 commented on pages/register.js
> +      }
해결