[김태영] Sprint8
codeit-sprint-fullstack/2-Sprint-Mission-FE pull request #161
Opened 2024-10-27 13:14 UTC by csbizz

# 요구사항

## 기본

### 공통

- [x] Github에 스프린트 미션 PR을 만들어 주세요.
- [x] Next.js를 사용해 진행합니다.

### 자유 게시판 페이지

- [x] 게시글 목록에서 드롭다운을 사용하여 "최신 순"으로 정렬할 수 있도록 합니다.
- [x] 본인이 이전 미션에서 생성한 게시글 목록 조회 API를 활용해 GET 메서드로 데이터를 가져옵니다.
- [x] 게시글 제목에 검색어가 일부 포함되면 해당 게시글을 검색할 수 있도록 합니다.
- [x] 이미지는 디폴트 이미지로 프론트엔드에서 처리해 주세요.
- [x] 게시글 닉네임 및 좋아요 개수 역시 임의값으로 프론트엔드에서 처리해주세요.
- [x] 베스트 게시글은 최신순 3개 게시글을 요청으로 데이터를 가져와 구현해주세요.
- [x] 자유게시판 페이지에서 특정 게시글을 클릭하면 해당 게시물의 상세 페이지로 이동합니다.

### 게시글 등록 & 수정 페이지

- [x] 각 input 필드에 정확한 placeholder 값을 입력합니다.
- [x] 모든 input 필드에 값을 입력하면 '등록' 버튼이 활성화됩니다.
- [x] 본인이 이전 미션에서 생성한 게시글 생성 API를 활용해 POST 메서드로 게시글을 등록합니다.
- [x] '등록' 버튼을 누르면 해당 게시물 상세 페이지로 이동합니다.
- [x] 게시글 수정 페이지 UI는 게시글 등록 페이지와 동일합니다.
- [x] 본인이 이전 미션에서 생성한 게시글 상세 API의 PATCH 메소드를 사용하여 게시물을 수정합니다.

### 게시글 상세 페이지

- [x] 본인이 이전 미션에서 생성한 게시글 상세 API의 GET 메소드를 사용하여 데이터를 가져옵니다.
- [] 본인이 이전 미션에서 생성한 게시글 상세 API의 DELETE 메소드를 사용하여 게시물을 삭제합니다.
- [x] 댓글 input에 값을 입력하면 '등록' 버튼이 활성화됩니다.
- [] 본인이 이전 미션에서 생성한 댓글 생성 API를 활용해 POST 메소드로 댓글을 등록합니다.
- [] 본인이 이전 미션에서 생성한 댓글 생성 API를 활용해 PATCH 메소드로 댓글을 수정합니다.
- [] 본인이 이전 미션에서 생성한 댓글 생성 API를 활용해 DELETE 메소드로 댓글을 삭제합니다.

## 심화

### 공통

- [] 디자인 시안에 따라 반응형 디자인을 구현합니다.
- [] (생략 가능) 원한다면 지금까지 진행한 모든 React 코드를 Next.js로 마이그레이션 해주세요.
마이그레이션에 상당한 시간이 소요될 수 있으므로 진행을 권장하지 않습니다.

## 주요 변경사항

-
-

## 스크린샷

## 멘토에게

-

2024-10-28 09:22 UTC, MCprotein commented on pages/articles/[id].jsx
> +import c from '@/src/utils/constants';
@csbizz 태영님 지금은 괜찮을거같지만, 코드 양이 많아지면 이렇게 한글자인것들 관리하기가 많이 힘들거에요

2024-10-28 13:24 UTC, MCprotein commented on pages/articles/[id].jsx
> +  };
@csbizz 이거 혹시 value가 `'        '`  이거면 어떻게되나요?

2024-10-29 08:24 UTC, MCprotein requested changes

2024-10-29 08:24 UTC, MCprotein commented on src/components/Modal.jsx
> +            } else if (button && typeof button === 'object') {
@csbizz 버튼이 array인가 판별하기 위한 조건이라면 typeof 말고 Array.isArray 메소드를 사용해야돼요

2024-10-29 08:24 UTC, MCprotein commented on src/components/product/ProductCard.jsx
> +  const imgUrl = images?.length ? images[0] : '/Image/img_default.png';
@csbizz 요렇게 줄일수 있겠네요
```suggestion
  const imgUrl = images?.[0] || '/Image/img_default.png';
```

2024-10-29 08:24 UTC, MCprotein commented on src/hooks/useValidation.js
> +  if (value?.length <= 0) {
@csbizz length는 음수가 될 수 없고, string 이라면 '' 도 0과마찬가지로 falsy 이므로 아래처럼 작성할 수 있을거같아요
```suggestion
  if (!value?.trim?.()) {
```

2024-10-29 08:24 UTC, MCprotein commented on src/utils/utils.js
> +}
@csbizz isEmpty가 utils.js에도 있고 isEmpty.js 도 있는데 중복인가요? 
그리고 요 코드에는 string 일 경우 trim 도 해줘야될거같아요

2024-10-30 01:48 UTC, csbizz commented on pages/articles/[id].jsx
> +import c from '@/src/utils/constants';
인지는 하고 있습니다. constants 자체가 여기저기서 사용 중인데, 뒤에 길게 이어져서 변수명이라도 줄이려고 사용 중입니다. 특별한 경우가 없다면 광역적으로 사용하면서 길이가 너무 길어지지 않는 경우는 변수명을 줄이지 않고 사용할 계획입니다.

2024-10-30 01:50 UTC, csbizz commented on pages/articles/[id].jsx
> +  };
trim하지 않아서 아마 입력한 것으로 인정될 것 같습니다. 공백만 있는 경우에는 예외처리를 해두는게 좋을까요?

2024-10-30 01:52 UTC, csbizz commented on src/components/Modal.jsx
> +            } else if (button && typeof button === 'object') {
64번 라인을 말씀하시는 거라면 null이 아닌 object를 체크하려고 했습니다.

2024-10-30 01:53 UTC, csbizz commented on src/components/product/ProductCard.jsx
> +  const imgUrl = images?.length ? images[0] : '/Image/img_default.png';
배열의 경우에도 optional chaining을 지원하는군요? 처음 알았습니다;

2024-10-30 02:08 UTC, csbizz commented on src/utils/utils.js
> +}
중복되어있네요. imEmpty.js는 삭제했습니다.
string의 경우 사용하는 쪽에서 trim하도록 하겠습니다.

2024-10-30 04:12 UTC, MCprotein commented on pages/articles/[id].jsx
> +import c from '@/src/utils/constants';
@csbizz 넵 알겠습니다! 꼭 하나로 묶어서 사용할 필요는 없을거같아요

2024-10-30 04:13 UTC, MCprotein commented on pages/articles/[id].jsx
> +  };
@csbizz 넵 보통 `'        '` 이런 값은 입력되지않은값으로 취급하는게 좋아요 실제로 아무 내용이 없는 값이니까 의미가없죠

2024-10-30 04:14 UTC, MCprotein commented on src/components/Modal.jsx
> +            } else if (button && typeof button === 'object') {
@csbizz 아 buttons랑 헷갈렸어요 ㅋㅋ 알겠습니다!

2024-10-30 04:17 UTC, MCprotein commented on src/components/product/ProductCard.jsx
> +  const imgUrl = images?.length ? images[0] : '/Image/img_default.png';
@csbizz 넵 아실수도있는데 배열말고도 함수에도 적용할 수 있고, 다양하게 사용할 수 있죵
```js
array?.sort?.()
```

2024-10-30 04:19 UTC, MCprotein commented on src/utils/utils.js
> +}
@csbizz 넵 좋습니다 !

2024-10-30 13:53 UTC, MCprotein approved these changes
@csbizz 태영님 고생하셨습니다!

2024-10-30 13:54 UTC, merged