Next 박효빈 sprint8
codeit-sprint-fullstack/2-Sprint-Mission-FE pull request #163
Opened 2024-10-30 12:35 UTC by hyobiin9

## 요구사항

### 기본 요구사항
---
## 공통

- [x] Github에 스프린트 미션 PR을 만들어 주세요.
- [x] Next.js를 사용해 진행합니다.

## 자유 게시판 페이지
- [ ] 게시글 목록에서 드롭다운을 사용하여 "최신 순"으로 정렬할 수 있도록 합니다.
- [ ] 본인이 이전 미션에서 생성한 게시글 목록 조회 API를 활용해 GET 메서드로 데이터를 가져옵니다.
- [ ] 게시글 제목에 검색어가 일부 포함되면 해당 게시글을 검색할 수 있도록 합니다.
- [ ] 이미지는 디폴트 이미지로 프론트엔드에서 처리해 주세요.
- [ ] 게시글 닉네임 및 좋아요 개수 역시 임의값으로 프론트엔드에서 처리해주세요.
- [ ] 베스트 게시글은 최신순 3개 게시글을 요청으로 데이터를 가져와 구현해주세요.
- [ ] 자유게시판 페이지에서 특정 게시글을 클릭하면 해당 게시물의 상세 페이지로 이동합니다.
## 게시글 등록 & 수정 페이지
- [ ] 각 input 필드에 정확한 placeholder 값을 입력합니다.
- [ ] 모든 input 필드에 값을 입력하면 '등록' 버튼이 활성화됩니다.
- [ ] 본인이 이전 미션에서 생성한 게시글 생성 API를 활용해 POST 메서드로 게시글을 등록합니다.
- [ ] '등록' 버튼을 누르면 해당 게시물 상세 페이지로 이동합니다.
- [ ] 게시글 수정 페이지 UI는 게시글 등록 페이지와 동일합니다.
- [ ] 본인이 이전 미션에서 생성한 게시글 상세 API의 PATCH 메소드를 사용하여 게시물을 수정합니다.
## 게시글 상세 페이지
- [ ] 본인이 이전 미션에서 생성한 게시글 상세 API의 GET 메소드를 사용하여 데이터를 가져옵니다.
- [ ] 본인이 이전 미션에서 생성한 게시글 상세 API의 DELETE 메소드를 사용하여 게시물을 삭제합니다.
- [ ] 댓글 input에 값을 입력하면 '등록' 버튼이 활성화됩니다.
- [ ] 본인이 이전 미션에서 생성한 댓글 생성 API를 활용해 POST 메소드로 댓글을 등록합니다.
- [ ] 본인이 이전 미션에서 생성한 댓글 생성 API를 활용해 PATCH 메소드로 댓글을 수정합니다.
- [ ] 본인이 이전 미션에서 생성한 댓글 생성 API를 활용해 DELETE 메소드로 댓글을 삭제합니다.
## 심화 요구사항
- [ ] 디자인 시안에 따라 반응형 디자인을 구현합니다.

## 멘토에게

-
-
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2024-10-31 16:00 UTC, MCprotein requested changes

2024-10-31 16:00 UTC, MCprotein commented on components/BestPost/BestPost.jsx
> +      );
@hyobiin9 효빈님 제가 예전에 이렇게 하지말라고 했는데 왜 이렇게 하신건가요?

2024-10-31 16:00 UTC, MCprotein commented on components/Dropdown/Dropdown.jsx
> +        {console.log(options)}
@hyobiin9 이거뭔가요?

2024-10-31 16:00 UTC, MCprotein commented on components/Header/Header.jsx
> +            </p>
@hyobiin9 active_board, active_market 이것들 어차피 같은 버튼이고 같은 css 요소인데, 하나로 통일하고 함수로 빼는게 더 좋을거같아요

2024-10-31 16:00 UTC, MCprotein commented on lib/axios.js
> +  baseURL: "https://panda-market-api.vercel.app/",
@hyobiin9 서버 host는 환경에따라 달라지기때문에 환경변수로 관리해야돼요

2024-10-31 16:00 UTC, MCprotein commented on pages/board/[id].jsx
> +      console.error("게시글을 가져오는 중 오류 발생:", error);
@hyobiin9 이렇게하면 catch 쓰는 의미가 없어요 다른곳들도 전부 이런거 수정해야돼요

2024-10-31 16:00 UTC, MCprotein commented on pages/board/[id].jsx
> +  ];
@hyobiin9 Dropdown의 value, label, style을 왜 여기서 선언하나요?

2024-10-31 16:00 UTC, MCprotein commented on pages/board/register.jsx
> +    }
@hyobiin9 early return pattern과 falsy 개념을 적용해서 수정해보세요

2024-11-01 00:48 UTC, hyobiin9 commented on components/BestPost/BestPost.jsx
> +      );
기능 구현을 우선시 하느라 저렇게 작업해둔 것 같습니다.
추후에 스프린트 미션 9 진행 후 수정하겠습니다!

2024-11-01 00:49 UTC, hyobiin9 commented on components/Dropdown/Dropdown.jsx
> +        {console.log(options)}
에러 찾으려고 출력했던건데 삭제하겠습니다

2024-11-01 00:50 UTC, hyobiin9 commented on components/Header/Header.jsx
> +            </p>
넵 수정하였습니다!

2024-11-01 00:57 UTC, hyobiin9 commented on pages/board/[id].jsx
> +  ];
드롭다운을 사용하는 곳이 두 곳이 있는데, 사용되는 두 군데에서 css가 다릅니다..
그래서 클래스명을 따로 지정해주고 싶었는데 적용이 되지 않는 것 같아서 css를 여기서 작성했습니다.

2024-11-02 14:49 UTC, hyobiin9 commented on pages/board/[id].jsx
> +      console.error("게시글을 가져오는 중 오류 발생:", error);
넵 미션 9 진행 후 수정하도록 하겠습니다

2024-11-02 14:49 UTC, hyobiin9 commented on lib/axios.js
> +  baseURL: "https://panda-market-api.vercel.app/",
넵 미션 9 진행 후 수정하도록 하겠습니다

2024-11-02 14:49 UTC, hyobiin9 commented on pages/board/register.jsx
> +    }
넵 미션 9 진행 후 수정하도록 하겠습니다

2024-11-02 16:16 UTC, MCprotein commented on components/BestPost/BestPost.jsx
> +      );
@hyobiin9 네 알겠습니다

2024-11-02 16:16 UTC, MCprotein commented on components/Dropdown/Dropdown.jsx
> +        {console.log(options)}
@hyobiin9 네 알겠습니다

2024-11-02 16:16 UTC, MCprotein commented on components/Header/Header.jsx
> +            </p>
@hyobiin9 네 고생하셨습니다

2024-11-02 16:17 UTC, MCprotein commented on lib/axios.js
> +  baseURL: "https://panda-market-api.vercel.app/",
@hyobiin9 넵

2024-11-02 16:17 UTC, MCprotein commented on pages/board/[id].jsx
> +      console.error("게시글을 가져오는 중 오류 발생:", error);
@hyobiin9 넵

2024-11-02 16:17 UTC, MCprotein commented on pages/board/[id].jsx
> +  ];
@hyobiin9 안티패턴같은데.. 누가 이렇게 하라고 한건가요? 제가 몰라서 여쭤보는거에요

2024-11-02 16:17 UTC, MCprotein commented on pages/board/register.jsx
> +    }
@hyobiin9 넵

2024-11-02 16:23 UTC, hyobiin9 commented on pages/board/[id].jsx
> +  ];
검색을 하다가 해결이 안되어서 지피티한테 물어봤습니다.
처음엔 클래스명을 따로 지정해주면 된다고 해서 시도해봤는데 적용이 되지 않는 것 같아서
임시적으로 저렇게 코드를 작성해뒀습니다. 미션 9 진행후 리팩토링하겠습니다!

2024-11-02 16:33 UTC, MCprotein commented on pages/board/[id].jsx
> +  ];
@hyobiin9 네 이런건 TODO 주석 달아주세요

2024-11-02 16:33 UTC, hyobiin9 commented on pages/board/[id].jsx
> +  ];
넵 알겠습니다!

2024-11-02 16:35 UTC, MCprotein approved these changes
@hyobiin9 효빈님 고생하셨습니다!

2024-11-02 16:35 UTC, merged