[김태연] Sprint9
codeit-sprint-fullstack/2-Sprint-Mission-FE pull request #169
Opened 2024-11-02 14:00 UTC by taeyeonkim94

## 코드리뷰 피드백 수정사항
피드백 지적사항 수정 현황
- [x] console.log 제거
- [x] 에러 처리 코드 에러던지기
- [x] 조건문 함수로 빼내기
- [x] 날짜 포맷 변경 함수에서 라이브러리 사용으로 변경
- [x] 게시글 컴포넌트 게시글 생성, 수정 컴포넌트로 분리
- [x] if문 뒤에 리턴이 있을 경우 else if 대신 if문으로 변경
- [x] 하드코딩 문자열 Object.freeze로 변경
- [x] map의 키에 들어가 있는 index를 다른 유니크키로 변경
- [x] 드랍다운 item 배열에서 객체타입으로 수정
- [x] 데이터 받아오는 훅 이름, 훅 안의 함수 이름 직관적으로 변경
- [x] 게시글 컴포넌트를 생성과 수정 컴포넌트 분리
- [x] register.js에서 정규표현식보다 isNaN이나 Number,isSafetyIntteger 변경
- [x] axios 추상화해서 wrapper 함수 사용하기

## 요구사항
### 기본
공통
- [x] Github에 위클리 미션 PR을 만들어 주세요.
- [x] React 혹은 Next.js를 사용해 진행합니다.
- [x] 프론트엔드에서 api 요청 구현은 TanStack React Query를 활용해 주세요.
- [x] API는 https://panda-market-api.vercel.app를 사용합니다. 명세는 https://panda-market-api.vercel.app/docs를 확인해 주세요.

로그인/회원가입 페이지
- [x] JavaScript로 구현한 로그인/회원가입 페이지를 React.js 혹은 Next.js로 마이그레이션해 주세요.

로그인 페이지
- [x] "회원 가입하기"를 클릭하면 회원가입 페이지로 이동해 주세요.
- [x] 로그인 실패하는 경우, 이메일 input 아래에 "이메일을 확인해 주세요.", 비밀번호 input 아래에 "비밀번호를 확인해 주세요." 에러 메시지를 표시해 주세요.
- [x] 로그인 버튼이 활성화된 후, 로그인 버튼 클릭 또는 Enter키 입력으로 로그인 실행합니다.
- [x] "/auth/signIn"으로 POST 요청해서 성공 응답을 받으면 중고 마켓 페이지로 이동합니다. 참고로 JWT로 구현되어 있습니다.
- [x] 실패할 경우, 실패 메시지를 모달을 통해 표시합니다.

회원가입 페이지
- [x] "회원 가입하기"를 클릭하면 '/signin' 페이지로 이동합니다
- [x] 회원가입 버튼 클릭 또는 Enter키 입력으로 회원가입을 실행합니다.
- [x] 비밀번호 input과 비밀번호 확인 input의 값이 다른 경우, 비밀번호 확인 input 아래에 "비밀번호가 일치하지 않아요." 에러 메시지를 표시해 주세요.
- [x] 버튼이 활성화된 후, 회원가입은 "/auth/signUp" POST 요청해서 진행합니다. 참고로 JWT로 구현되어 있습니다.
- [x] 회원가입 성공 응답을 받으면 중고마켓 페이지로 이동합니다.
- [x] 실패할 경우, 실패 메시지를 모달을 통해 표시합니다.
로그인, 회원가입 페이지 공통

- [x] 눈 모양 아이콘 클릭 시 비밀번호의 문자열이 보이기도 하고, 가려집니다.
- [x] 비밀번호의 문자열이 가려질 때는 눈 모양 아이콘에는 사선이 그어져 있고, 비밀번호의 문자열이 보일 때는 사선이 없는 눈 모양 아이콘이 보입니다.
- [x] 소셜 로그인에 구글 아이콘 클릭 시 'https://www.google.com', 카카오 아이콘 클릭 시 'https://www.kakaocorp.com/page'로 이동합니다.
- [x] 로그인/회원가입 시 성공 응답으로 받은 accessToken을 로컬 스토리지에 저장합니다.
- [x] 로그인/회원가입 페이지에 접근 시 로컬 스토리지에 accessToken이 있는 경우 '/folder' 페이지로 이동합니다.

GNB
- [x] 상단 내비게이션 바에 프로필 영역은 인가된 경우, 유저 정보 API를 활용해 주세요.
- [x] 인가되지 않았을 경우 "로그인" 버튼이 보이게 해 주세요.

상품 상세 페이지
- [x] PC, Tablet, Mobile 디자인에 해당하는 상품 상세 페이지를 만들어 주세요.
- [x] 상품 상세 페이지 url path는 "/items/{itemId)"로 설정하세요.
- [x] '목록으로 돌아가기' 버튼 클릭 시 중고마켓 페이지 "/items"로 이동합니다.
- [x] 상품 상세 데이터는 '/products/{productId}' GET 메서드 사용해 불러오세요. 이때, 상품 상세 조회는 인가된 사용자만 이용할 수 있도록 합니다.
- [x] 상품에 대한 댓글 조회도 가능합니다.
- [x] 상품 수정 및 삭제 기능을 API를 활용해 구현합니다. 이때, 인가된 사용자만 이용할 수 있도록 합니다.
- [x] 상품 수정은 '/products/{productId}' PUT을 사용합니다.
- [x] 상품 삭제는 '/products/{productId}' DELETE를 사용합니다.
- [x] 상품 삭제 전, 확인 모달을 띄워주세요.
- [ ] 상품에 대한 좋아요 및 좋아요 취소 기능을 https://panda-market-api.vercel.app/docs에 명세된 '/products/{productId}/favorite' POST & DELETE 활용해 구현합니다. 이때 인가된 사용자만 좋아요 기능을 이용할 수 있도록 합니다.
- [x] 댓글 생성 및 삭제 기능을 API를 활용해 구현합니다. 이때, 인가된 사용자만 이용할 수 있도록 합니다.
- [x] 댓글 수정은 https://panda-market-api.vercel.app/docs에 명세된 '/products/{productId}/comments' PUT을 사용합니다.
- [x] 댓글 삭제는 https://panda-market-api.vercel.app/docs에 명세된 '/products/{productId}/comments' DELETE를 사용합니다.
### 심화
로그인 및 회원가입 페이지 공통
- [ ] 로그인, 회원가입 기능에 react-hook-form을 활용해 주세요.
- [x] 브라우저에 현재 보이는 화면의 영역(viewport) 너비를 기준으로 분기되는 반응형 디자인을 적용합니다.
PC: 1200px 이상
Tablet: 744px 이상 ~ 1199px 이하
Mobile: 375px 이상 ~ 743px 이하
375px 미만 사이즈의 디자인은 고려하지 않습니다
유저 기능

- [x] 리퀘스트 헤더에 인증 토큰을 첨부할 때 axios interceptors를 활용해 주세요. (axios를 사용하지 않는다면 이와 유사한 기능을 활용해 주세요.)
React-Query로 마이그레이션

- [x] fetch 혹은 axios로 구현된 기존의 API 요청 코드를 React-Qeury로 마이그레이션 합니다.
로딩 및 에러 핸들링

- [ ] 로딩 인디케이터와 에러 메시지를 구현합니다.
- [ ] 상품 목록 및 상품 상세 데이터를 Prefetching 합니다
상품 데이터 캐싱 및 업데이트

- [x] React Query의 캐싱 기능을 활용하여 데이터 로딩 시간을 최소화합니다.
- [ ] 상품 목록 페이지에서 데이터의 실시간 업데이트를 위해 적절한 Query Refresh 설정을 적용합니다.
## 주요 변경사항
배포링크: https://2-sprint-mission-fe-seven.vercel.app/

- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2024-11-03 11:48 UTC, MCprotein commented on constants.js
> +});
@taeyeonkim94 태연님 이것의 이름을 BUTTON_TYPE 으로 하면 좀더 명확한 코드가 될거같은데 어떠신가요?
```suggestion
export const BUTTON_TYPE = Object.freeze({
  edit: {value: 'EDIT', label: '수정하기'},
  delete: {value: 'delete', label:' 수정하기'}
});
```

그러면 이 값을 사용하는 코드에서도 아래처럼 어떤 상수인지 더 직관적으로 알 수 있을거같아요
```js
    if (chosenOption === BUTTON_TYPE.edit.value) setEditMode(true);
    else if (chosenOption === BUTTON_TYPE.delete.value) onDelete(data.id);
```
 대소문자는 취향에 따른거지만, value를 구조분해할당으로 가져와서 쓰느냐 아니면 객체를명시하고 사용할것이냐는 문제가 있잖아요
저는 BUTTON_TYPE을 명시해주는게 좋다고 생각해요. 코드 양이 늘어날수록 `이 상수는 어디서부터 온거지?` 라는 의문이 생길 수 있어요. 항상 그 코드를 보고 있는게 아니니까 본인이 작성했던 코드여도 까먹게되고 나중에 다시봤을때 한 번에 기억이 안날수도 있죠. 그래서 어떤것과 관련된 값인지 코드에 명시를 해주는게 한 눈에 담기 좋을거같아요

2024-11-03 11:50 UTC, MCprotein commented on lib/axios.js
> +  baseURL: "http://localhost:3001"
@taeyeonkim94 태연님 서버 호스트는 환경변수로 관리해야돼요. 이유를 아시나요?

2024-11-03 11:54 UTC, MCprotein commented on hooks/useDataFetchNew.js
>        const response = await axios.get(url);
@taeyeonkim94 axios 이렇게 그대로 갖다쓰는거보다 추상화해서 wrapper 함수를 쓰도록 해보세요
코드는 확장과 변화에 열려있어야하는데, 이렇게 그대로 갖다쓰면 라이브러리를 교체하거나 버전업데이트되서 내장메소드가 많이 바뀌게됐을때 이 코드를 사용하는 부분을 다고쳐야되서 유지보수 비용이 증가해요 (비용은 가격이아니라 인적자원 및 시간) 
그리고 wrapper 를 만들어야 여러 코드에 적용되는 에러핸들링을 하기에도 용이해요

2024-11-03 11:55 UTC, MCprotein commented on pages/freeboard/[id].js
> +        const resposne = await deleteArticle(id);
response는 try scope를 나가면 사라질텐데 어떤 의미가 있나요?

2024-11-03 12:03 UTC, MCprotein commented on pages/freeboard/write/index.js
> +            className={isPost ? `${postBtn} ${on}` : `${postBtn} ${off}`}
@taeyeonkim94 
이거 아까 얘기할때 제가 태연님 말씀을 착각했던거같아요
제가 어쩔수없다고 말씀드렸던건 isEdit 가지고 삼항연산자를 만드는 부분이고, 요런 방식보다는 아래 링크에 있는 방식이였어요
https://velog.io/@shackstack/React-className%EC%97%90%EC%84%9C-%EC%82%BC%ED%95%AD%EC%97%B0%EC%82%B0%EC%9E%90-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0

```suggestion
className={`w-[74px] h-full px-[23px] py-[12px] text-[16px] font-semibold leading-19.09px text-f3f4f6 rounded-[8px] ${isPost ? 'bg-3692ff' : 'bg-9ca3a'}`}
```

2024-11-03 12:09 UTC, MCprotein requested changes
@taeyeonkim94 보통 리액트 기반으로 개발할때 컴포넌트 코드가 작성된 파일은 확장자를 jsx로 사용하고, 컴포넌트가 아니라 유틸같은 자바스크립트 파일만 있는 파일은 js 확장자를 사용해요
기능상으로는 차이가 없지만 파일이름만 보고 컴포넌트인지 구분할 수 있고, vscode에서도 확장자별로 인식하여 지원하는 기능이 다르기 때문이에요
jsx에 대해 검색해보시고 변경해보세요

2024-11-03 14:14 UTC, taeyeonkim94 commented on pages/freeboard/write/index.js
> +            className={isPost ? `${postBtn} ${on}` : `${postBtn} ${off}`}
저도 이렇게 이해했습니다

2024-11-03 15:00 UTC, MCprotein commented on utils/convertDate.js
> +  return formattedDate;
@taeyeonkim94 태연님 다른사람 pr은 안보시나요?

2024-11-03 15:03 UTC, MCprotein commented on utils/convertDate.js
> +  return formattedDate;
@taeyeonkim94 태연님 제가 착각해서 댓글썼다가 지웠는데 무시해주세요

2024-11-06 13:33 UTC, MCprotein commented
@taeyeonkim94 태연님 코멘트 내용은 나중에 수정하시는걸까요?

2024-11-07 01:34 UTC, taeyeonkim94 commented on hooks/useDataFetchNew.js
>        const response = await axios.get(url);
랩퍼함수 만들었습니다 추가 기능은 아직 에러 발생 시 에러 반환뿐입니다

2024-11-07 01:34 UTC, taeyeonkim94 commented on pages/freeboard/[id].js
> +        const resposne = await deleteArticle(id);
랩퍼함수로 변경하면서 수정했습니다

2024-11-07 01:40 UTC, taeyeonkim94 commented on lib/axios.js
> +  baseURL: "http://localhost:3001"
보안성 때문이겠네요 수정했습니다

2024-11-07 02:07 UTC, taeyeonkim94 commented on constants.js
> +});
이해했습니다 근데 BUTTON_TYPE보다는 드랍다운에서 왔으니 EDIT_DELETE_를 뺴고 DROPDOWN_LIST로 사용하는건 별로일까요?

2024-11-08 04:04 UTC, taeyeonkim94 commented on constants.js
> +});
수정했습니다

2024-11-10 13:53 UTC, MCprotein commented on lib/axios.js
> +  baseURL: "http://localhost:3001"
@taeyeonkim94 보안도 있고, 환경에 따라 호스트가 달라지기때문입니다
로컬 환경, 개발 환경, 운영 환경에 따라 호스트가 다르죠

2024-11-10 13:56 UTC, MCprotein commented on api/api.js
> +      if (error.response && error.response.status === 401) {
@taeyeonkim94 이건 아래와 같이 쓸 수 있어요
```suggestion
      if (error?.response.status === 401) {
```

2024-11-10 14:32 UTC, MCprotein commented on api/api.js
> +    }
@taeyeonkim94 별다른 행위 없이 단순히 throw 만 한다면 catch block을 없애도 돼요

2024-11-10 14:34 UTC, MCprotein commented on api/api.js
> +    const response = await instance.get("/users/me", {
@taeyeonkim94 제가 말씀드린 wrapping 은 axios 자체를 wrapping 하는거였어요
극단적인 예시를 들어보자면, 만약 axios get 메소드가 사라진다면 많은 부분을 수정해야될거에요.
하지만 wrapping 한걸 사용한다면 wrapping 함수 하나만 수정하면 죠

2024-11-10 14:34 UTC, MCprotein commented on api/api.js
> +export const postUser = async (formData) => {
@taeyeonkim94 이 api 파일 안에 너무 많은 자원에 대한 api가 공존해있어서 파일로 분리하면 더 좋을거같아요

2024-11-10 14:38 UTC, MCprotein commented on components/Modal.jsx
> +        <p className="mt-[24px]">정말로 상품을 삭제하시겠어요?</p>
@taeyeonkim94 모달 이라는 범용적인 컴포넌트니까 이 메세지도 props로 받게 하면 더 좋을거같아요

2024-11-10 14:40 UTC, MCprotein commented on components/Nav.js
> +            src={user.image ? user.image : "/images/ic_profile.png"}
@taeyeonkim94 아래처럼 바꿀수있어요

```suggestion
            src={user.image ?? "/images/ic_profile.png"}
```

```suggestion
            src={user.image || "/images/ic_profile.png"}
```

2024-11-10 14:41 UTC, MCprotein commented on components/Section.js
> +  if (name === "safety") {
@taeyeonkim94 여기는 누락된거같네요

2024-11-10 14:50 UTC, MCprotein commented on lib/hooks/useGetData.js
> +      const { comments } = articleComments || productComments || {};
@taeyeonkim94 이거 article, product 말고 또 다양한것들이 많이 생기면 그때마다 이부분에 추가가 되어야할거같은데, 
useGetData는 범용적으로 사용되는거니까 변화를 수용할 수 있도록 수정해보면 좋을거같아요

2024-11-10 14:53 UTC, MCprotein commented on pages/freeboard/index.jsx
> +            베스트 게시글
@taeyeonkim94 bestList, standardList 각각에 해당하는 컴포넌트를 또 만들면 어덜까요? column의 개수와 이름을 props로 넘겨줄 수 있게 만든다면 다른 글 목록 기능에서도 사용할 수 있을거같요

2024-11-10 14:55 UTC, MCprotein commented on pages/freeboard/write/[slug].js
> +      handleError(new Error("데이터 전송중 오류"));
@taeyeonkim94 이렇게하면 에러 객체가 사라져서 클라이언트의 문제인지, 서버의 문제인지 알 수 없을거같은데 어떻게생각하시나요?

2024-11-10 14:57 UTC, MCprotein commented on pages/items/[id].jsx
> +      handleError(new Error("삭제 실패"));
@taeyeonkim94 커스텀에러객체를 사용해서 어느정도 에러를 분류할 필요는 없을까요?

2024-11-10 15:06 UTC, MCprotein commented on pages/login.jsx
> +  };
@taeyeonkim94 이런건 순수함수로 만드는게 좋을거같아요
입출력이 명확하고 멱등성이 있어야돼요

2024-11-13 14:24 UTC, MCprotein approved these changes
@taeyeonkim94 태연님 고생하셨습니다!

2024-11-13 14:27 UTC, merged