[이강수] sprint9
codeit-sprint-fullstack/2-Sprint-Mission-FE pull request #173
Opened 2024-11-04 05:28 UTC by kipid

# 스프린트 미션 9 시안 확인

instance.interceptors 부분을 제대로 작성한건지 모르겠네요. refreshToken 이 안먹히는것도 같아서...

아래 링크를 통해 강의 학습 후 만들어봐야 할 실습 과제 디자인을 확인해 보세요

- 스프린트 미션 9 Figma 디자인 확인하러 바로가기

## 요구사항
### 기본 요구사항
#### 공통

- [x] Github에 위클리 미션 PR을 만들어 주세요.
- [x] React 혹은 Next.js를 사용해 진행합니다.
- [x] 프론트엔드에서 api 요청 구현은 TanStack React Query를 활용해 주세요.
- [x] API는 https://panda-market-api.vercel.app를 사용합니다. 명세는 https://panda-market-api.vercel.app/docs를 확인해 주세요.

#### 로그인/회원가입 페이지

- [x] JavaScript로 구현한 로그인/회원가입 페이지를 React.js 혹은 Next.js로 마이그레이션해 주세요.

#### 로그인 페이지

- [x] "회원 가입하기"를 클릭하면 회원가입 페이지로 이동해 주세요.
- [ ] 로그인 실패하는 경우, 이메일 input 아래에 "이메일을 확인해 주세요.", 비밀번호 input 아래에 "비밀번호를 확인해 주세요." 에러 메시지를 표시해 주세요.
	// 이건 다 400 error 가 떠서 어떻게 분기해야할지 감이 안잡히네요.
- [x] 로그인 버튼이 활성화된 후, 로그인 버튼 클릭 또는 Enter키 입력으로 로그인 실행합니다.
- [x] "/auth/signIn"으로 POST 요청해서 성공 응답을 받으면 중고 마켓 페이지로 이동합니다. 참고로 JWT로 구현되어 있습니다.
- [x] 실패할 경우, 실패 메시지를 모달을 통해 표시합니다.

#### 회원가입 페이지

- [x] "회원 가입하기"를 클릭하면 '/signin' 페이지로 이동합니다
- [x] 회원가입 버튼 클릭 또는 Enter키 입력으로 회원가입을 실행합니다.
- [x] 비밀번호 input과 비밀번호 확인 input의 값이 다른 경우, 비밀번호 확인 input 아래에 "비밀번호가 일치하지 않아요." 에러 메시지를 표시해 주세요.
- [x] 버튼이 활성화된 후, 회원가입은 "/auth/signUp" POST 요청해서 진행합니다. 참고로 JWT로 구현되어 있습니다.
- [x] 회원가입 성공 응답을 받으면 중고마켓 페이지로 이동합니다.
- [x] 실패할 경우, 실패 메시지를 모달을 통해 표시합니다.

#### 로그인, 회원가입 페이지 공통

- [x] 눈 모양 아이콘 클릭 시 비밀번호의 문자열이 보이기도 하고, 가려집니다.
- [x] 비밀번호의 문자열이 가려질 때는 눈 모양 아이콘에는 사선이 그어져 있고, 비밀번호의 문자열이 보일 때는 사선이 없는 눈 모양 아이콘이 보입니다.
- [x] 소셜 로그인에 구글 아이콘 클릭 시 'https://www.google.com', 카카오 아이콘 클릭 시 'https://www.kakaocorp.com/page'로 이동합니다.
- [x] 로그인/회원가입 시 성공 응답으로 받은 accessToken을 로컬 스토리지에 저장합니다.
- [x] 로그인/회원가입 페이지에 접근 시 로컬 스토리지에 accessToken이 있는 경우 '/folder' 페이지로 이동합니다.

#### GNB

- [x] 상단 내비게이션 바에 프로필 영역은 인가된 경우, 유저 정보 API를 활용해 주세요.
- [x] 인가되지 않았을 경우 "로그인" 버튼이 보이게 해 주세요.

#### 상품 상세 페이지

- [x] PC, Tablet, Mobile 디자인에 해당하는 상품 상세 페이지를 만들어 주세요.
- [x] 상품 상세 페이지 url path는 "/items/{itemId)"로 설정하세요.
- [x] '목록으로 돌아가기' 버튼 클릭 시 중고마켓 페이지 "/items"로 이동합니다.
- [x] 상품 상세 데이터는 '/products/{productId}' GET 메서드 사용해 불러오세요. 이때, 상품 상세 조회는 인가된 사용자만 이용할 수 있도록 합니다.
	- [x] 상품에 대한 댓글 조회도 가능합니다.
- [x] 상품 수정 및 삭제 기능을 API를 활용해 구현합니다. 이때, 인가된 사용자만 이용할 수 있도록 합니다.
	- [ ] 상품 수정은 '/products/{productId}' PUT을 사용합니다.
	- [x] 상품 삭제는 '/products/{productId}' DELETE를 사용합니다.
- [ ] 상품 삭제 전, 확인 모달을 띄워주세요.
- [x] 상품에 대한 좋아요 및 좋아요 취소 기능을 https://panda-market-api.vercel.app/docs에 명세된 '/products/{productId}/favorite' POST & DELETE 활용해 구현합니다. 이때 인가된 사용자만 좋아요 기능을 이용할 수 있도록 합니다.
- [x] 댓글 생성 및 삭제 기능을 API를 활용해 구현합니다. 이때, 인가된 사용자만 이용할 수 있도록 합니다.
	- [x] 댓글 수정은 https://panda-market-api.vercel.app/docs에 명세된 '/products/{productId}/comments' PUT을 사용합니다.
	- [x] 댓글 삭제는 https://panda-market-api.vercel.app/docs에 명세된 '/products/{productId}/comments' DELETE를 사용합니다.

### 심화 요구사항

#### 로그인 및 회원가입 페이지 공통

- [x] 로그인, 회원가입 기능에 react-hook-form을 활용해 주세요.
- [x] 브라우저에 현재 보이는 화면의 영역(viewport) 너비를 기준으로 분기되는 반응형 디자인을 적용합니다.
	- PC: 1200px 이상
	- Tablet: 744px 이상 ~ 1199px 이하
	- Mobile: 375px 이상 ~ 743px 이하
	- 375px 미만 사이즈의 디자인은 고려하지 않습니다

#### 유저 기능

- [x] 리퀘스트 헤더에 인증 토큰을 첨부할 때 axios interceptors를 활용해 주세요. (axios를 사용하지 않는다면 이와 유사한 기능을 활용해 주세요.)

#### React-Query로 마이그레이션

- [x] fetch 혹은 axios로 구현된 기존의 API 요청 코드를 React-Qeury로 마이그레이션 합니다.

#### 로딩 및 에러 핸들링

- [ ] 로딩 인디케이터와 에러 메시지를 구현합니다.
- [ ] 상품 목록 및 상품 상세 데이터를 Prefetching 합니다

#### 상품 데이터 캐싱 및 업데이트

- [x] React Query의 캐싱 기능을 활용하여 데이터 로딩 시간을 최소화합니다.
- [x] 상품 목록 페이지에서 데이터의 실시간 업데이트를 위해 적절한 Query Refresh 설정을 적용합니다.

2024-11-13 13:58 UTC, prravda reviewed
전반적으로 확인 완료하였고, 리뷰 남겼습니다.

`/boards` 로 넘어갈 때 page not found 가 발생합니다.
그리고 sprint8 에선 nextjs 를 사용하셨는데 다시 React 를 사용하시게 된 이유가 있을까요?

2024-11-13 13:58 UTC, prravda commented on src/apis/itemsService.js
> +		return err?.response?.data || err;
`err?.response?.data` 로 결과를 확인하시는 이유가 있을까요?

2024-11-13 13:58 UTC, prravda commented on src/components/Comment.jsx
> +      });
`onError` 를 통해 에러가 반환되는 경우 어떻게 처리할지도 고민해주시면 좋겠습니다.

2024-11-13 13:58 UTC, prravda commented on src/pages/RegisPage.jsx
validation logic 들을 따로 빼서 관리해 보는 건 어떨까요?

2024-11-13 13:59 UTC, prravda requested changes
conflict 난 사항들 resolve 부탁드립니다!

2024-11-13 13:59 UTC, prravda commented
> React-Query 로 쓰게되면 useEffect 를 안써야 할것도 같은데, Too many re-render error 가 나서 어쩔수 없이 useEffect 를 쓰긴 했습니다. 뭔가가 잘못된것도 같은데, 어디를 고쳐야할지 잘 감이 안잡히네요.

이 부분은 추가로 확인하고 정리한 뒤 답변드릴 수 있도록 하겠습니다.

2024-11-13 14:00 UTC, prravda commented
> React-Query 로 쓰게되면 useEffect 를 안써야 할것도 같은데, Too many re-render error 가 나서 어쩔수 없이 useEffect 를 쓰긴 했습니다. 뭔가가 잘못된것도 같은데, 어디를 고쳐야할지 잘 감이 안잡히네요.

이 부분은 추가로 확인하고 정리한 뒤 답변드릴 수 있도록 하겠습니다.

2024-11-13 14:00 UTC, closed without merging

2024-11-14 04:46 UTC, kipid commented
> conflict 난 사항들 resolve 부탁드립니다!

Closed 되어서 그런지 conflict resolve 하는 버튼이 안보여요. 어떻게 해야 하는건지;;;

2024-11-14 04:51 UTC, kipid commented
> 전반적으로 확인 완료하였고, 리뷰 남겼습니다.
> 
> `/boards` 로 넘어갈 때 page not found 가 발생합니다. 그리고 sprint8 에선 nextjs 를 사용하셨는데 다시 React 를 사용하시게 된 이유가 있을까요?

이미지 처리하기가 힘들어 보여서 React route 를 써봤는데, sprint 10 에선 다시 nextjs 사용하였습니다.
어쩌다 보니 손이 두세배로 고생하네요 ㅠㅜ

2024-11-14 07:30 UTC, kipid reviewed
간단히 답변 남겼습니다. 이제 중간 프로젝트라 중간 프로젝트에 집중해야 할거 같아요.

2024-11-14 07:30 UTC, kipid commented on src/pages/ItemsPage.jsx
> +  }, [result1, pageSize]);
useQuery 를 쓰면 useEffect 는 거의 쓰지 않아야할것도 같은데...
Too many re-render 에러가 나서 어쩔수없이 useEffect 를 썼습니다. 이게 맞는걸까요?

2024-11-14 07:30 UTC, kipid commented on src/apis/itemsService.js
> +		return err?.response?.data || err;
error 의 message 를 주로 PopUp.jsx 로 띄우는데, err.response.data 에 이 에러메세지가 잘 적혀있는 경우가 많더라구요. 그래서 data 가 있으면 그걸로 반환하게 했습니다.

2024-11-14 07:30 UTC, kipid commented on src/components/Comment.jsx
> +      });
넵 알겠습니다.

2024-11-14 07:30 UTC, kipid commented on src/pages/RegisPage.jsx
useForm() 의 {...register("..")} 사용해보란 말씀이신거죠? 알겠습니다.

2024-11-15 03:52 UTC, prravda commented on src/apis/itemsService.js
> +		return err?.response?.data || err;
그거라면 합리적인 이유네요, 좋습니다!