[김영은] Sprint 1&2
codeit-sprint-fullstack/2-Sprint-Mission-FE pull request #34
Opened 2024-08-11 13:21 UTC by Maybeiley

## 요구사항

### 기본

- [x]  React와 같은 UI 라이브러리를 사용하지 않고 진행합니다
- [x] PC사이즈만 고려해 주어진 디자인으로 구현합니다.
- [x]  HTML, CSS 파일을 [Netlify](https://www.netlify.com/)로 배포해 주세요. (참고: https://www.codeit.kr/learn/5309)
- [x]  랜딩 페이지의 url path는 루트(‘/’)로 설정합니다.
- [x]  title은 “판다마켓”로 설정합니다.
- [x]  “판다마켓” 로고 클릭 시 루트 페이지(‘/’)로 이동합니다.
- [x]  '로그인' 버튼 클릭 시 로그인 페이지(‘/login’)로 이동합니다 (빈 페이지)
- [x]  “구경하러 가기”버튼 클릭 시(’/items’)로 이동합니다. (빈 페이지)
- [x]  “Privacy Policy”, “FAQ”는 클릭 시 각각 Privacy 페이지(‘/privacy’), FAQ 페이지(‘/faq’)로 이동합니다.(모두 빈 페이지)
- [x]  페이스북, 트위터, 유튜브, 인스타그램 아이콘을 클릭 시 각각의 홈페이지로 새로운 창이 열리면서 이동합니다.
- [x]  아래로 스크롤해도 “판다 마켓” 로고와 “로그인” 버튼이 있는 상단 내비게이션 바(Global Navigation Bar)가 최상단에 고정되게 해 주세요.
- [x]  화면의 너비가 1920px 이상이면 하늘색 배경색은 너비를 꽉 채우도록 채워지고, 내부 요소들의 위치는 고정되고, 여백만 커지도록 합니다.
- [x]  화면의 너비가 1920px 보다 작아질 때, “판다마켓” 로고의 왼쪽 여백 200px, “로그인" 버튼의 오른쪽 여백 200px이 유지되고, 화면의 너비가 작아질수록 두 요소 간 거리가 가까워지도록 설정합니다.
- [x]  화면의 너비가 1920px 이상이면 내부에 있는 요소 간 동일한 간격을 유지하며 가운데 정렬해야 합니다.
- [x]  화면의 너비가 1920px 보다 작아질 때, 최하단에 있는 “codeit-2024”의 왼쪽 여백 200px과 SNS 아이콘들의 오른쪽 여백 200px을 유지하면서 가운데 있는 “Privacy Policy”, “FAQ” 요소와 각각 동일한 간격을 유지하며 가까워져야 합니다.
- [x]  클릭으로 기능이 동작해야 하는 경우, 사용자가 클릭할 수 있는 요소임을 알 수 있도록 CSS 속성 cursor: pointer로 설정합니다.

**Mission 2**
- [x]  README.md 파일을 작성해 주세요.
- [x]  본인 브랜치(ex)part1-홍길동)에 스프린트 미션을 업로드해 주세요.
- [x]  적절한 커밋 메시지를 남겨 주세요.
- [x]  1-Sprint-Mission 레포지토리를 fork 합니다.
- [x]  GitHub에 PR(Pull Request)을 생성해 upstream의 본인 브랜치(ex)part1-홍길동)에 미션을 제출합니다.
- [x]  PR 코멘트
- [x]  Git 활용 과정에서 유닉스 커맨드를 활용해 주세요.
- [x]  HTML, CSS 파일을 Netlify로 배포합니다. (참고: https://www.codeit.kr/learn/5309)

`로그인 페이지, 회원가입 페이지 공통`

- [x] “판다마켓" 로고 클릭 시 루트 페이지(“/”)로 이동합니다.
- [x] 로그인 페이지, 회원가입 페이지 모두 로고 위 상단 여백이 동일합니다.
- [x] SNS 아이콘들은 클릭 시 각각 “https://www.google.com/”, “https://www.kakaocorp.com/page/” 으로 이동합니다.
- [x] input 요소에 focus in 일 때, 테두리 색상은 ##3692FF입니다.
- [x] input 요소에 focus out 일 때, 테두리는 없습니다.

`로그인 페이지`

- [x] “회원가입”버튼 클릭 시 “/signup” 페이지로 이동합니다.

`회원가입 페이지`

- [x] “로그인”버튼 클릭 시 “/login” 페이지로 이동합니다

### 심화

**Mission 1**
- [x] reset.css를 설정해 주세요.
- [x] 사용자의 브라우저 설정에 따라 기본 폰트 크기 설정이 변화함에 따라서 페이지의 요소 간 간격, 요소의 크기, font-size 등 모든 크기와 관련된 값이 크고 작아지도록 설정해 주세요.

**Mission 2**
- [x] palette에 있는 color값들을 css 변수로 등록해서 사용합니다.
- [x] 구글 애널리틱스로 방문자 수 확인하기 할 수 있도록 설정합니다.

`로그인 페이지, 회원가입 페이지 공통`

- [x] 비밀번호, 비밀번호 확인 input 요소 오른쪽에 비밀번호를 확인할 수 있는 눈 모양 아이콘을 추가합니다.

## 주요 변경사항

- netlify : https://go-panda-market.netlify.app/
- eye, pw 클래스 이름 변경
- <script> 위치 변경
- mid-banner display 방식 변경
- <img /> 맺음 시 "/" 추가

## 스크린샷

<img width="1234" alt="Screenshot 2024-08-06 at 7 21 02 PM" src="https://github.com/user-attachments/assets/9af72f9a-68b3-4ab0-b6f1-7d0f131ad5eb">
<img width="1237" alt="Screenshot 2024-08-06 at 7 20 49 PM" src="https://github.com/user-attachments/assets/5fd98a43-6714-437c-a470-1de8556495c4">

## 멘토에게

- flexbox을 좀 더 활용해 보았는데, 전체 구조를 모두 flex로 구성하려고 하니 한계가 많아서 말씀하신 mid-banner 부분만 flex로 재구성했습니다. banner 사이는 margin 대신 gap을 줬습니다. 요소별로 flex를 사용할 때는 크게 어렵지 않았는데, 전체 구성을 짜려니 부모 자식 요소간의 문제(?)로 잘 적용이 안 되어 생각보다 여러 번 시도해야 했습니다 :( 덕분에 연습이 많이 되었습니다! 계속 연습하고 공부해봐야 겠습니다.
- 리뷰로 말씀하신 부분들 수정했는데, 추가 사항 있으면 사소한 것이라도 더 짚어주시면 감사하겠습니다!

2024-08-11 23:19 UTC, junguksim requested changes
너무 잘해주셨습니다!!
바로 merge 해도 상관없지만, 이름과 관련된 사소한 개선점들 몇가지 멘션해뒀습니다.

고민한 흔적이 느껴지는 코드였어요. 수고하셨습니다 :)

2024-08-11 23:19 UTC, junguksim commented on index.html
> +      <div class="right-aligned">
아주 잘하셨습니다!
제가 의도한 구현 방식이 이겁니다.

전체를 한번 더 감싸준뒤, flex-end 로 주게 되면 오른쪽 정렬,  flex-start 로 주게 되면 왼쪽 정렬인 식이었어요.
(다만 flex-start 는 기본값이니까 왼쪽은 따로 안해도 될 것 같습니다)

2024-08-11 23:19 UTC, junguksim commented on login/index.html
> +        <img class="show-password" src="images/invisible.png">
사소하지만, 
password 를 보여주는 기능을 껐다 켰다 하는 버튼이므로,
toggle-show-password 로 바꿔주면 좋을 것 같아요.

(이미지 이름 invisible.png 도 마찬가지로 더 명시적일 수 있을 거 같습니다!)

2024-08-19 01:49 UTC, Maybeiley commented on login/index.html
> +        <img class="show-password" src="images/invisible.png">
말씀하신대로 toggle-show-password로 변경하여 새 커밋 2개를 푸시했습니다!

2024-08-19 01:52 UTC, junguksim approved these changes

2024-08-19 01:52 UTC, merged