[서유림] Sprint1
codeit-sprint-fullstack/2-Sprint-Mission-FE pull request #4
Opened 2024-08-02 07:44 UTC by Seo-Yurim

## 요구사항

### 기본

- [ O ]  React와 같은 UI 라이브러리를 사용하지 않고 진행합니다.

- [ O ]  PC사이즈만 고려해 주어진 디자인으로 구현합니다.

- [ O ]  HTML, CSS 파일을 [Netlify](https://www.netlify.com/)로 배포해 주세요.

- [ O ]  랜딩 페이지의 url path는 루트(‘/’)로 설정합니다.

- [ O ]  title은 “판다마켓”로 설정합니다.

- [ O ]  “판다마켓” 로고 클릭 시 루트 페이지(‘/’)로 이동합니다.

- [ O ]  '로그인' 버튼 클릭 시 로그인 페이지(‘/login’)로 이동합니다 (빈 페이지)

- [ O ]  “구경하러 가기”버튼 클릭 시(’/items’)로 이동합니다. (빈 페이지)

- [ O ]  “Privacy Policy”, “FAQ”는 클릭 시 각각 Privacy 페이지(‘/privacy’), FAQ 페이지(‘/faq’)로 이동합니다.(모두 빈 페이지)

- [ O ]  페이스북, 트위터, 유튜브, 인스타그램 아이콘을 클릭 시 각각의 홈페이지로 새로운 창이 열리면서 이동합니다.

- [ O ]  아래로 스크롤해도 “판다 마켓” 로고와 “로그인” 버튼이 있는 상단 내비게이션 바(Global Navigation Bar)가 최상단에 고정되게 해 주세요.

- [ O ]  화면의 너비가 1920px 이상이면 하늘색 배경색은 너비를 꽉 채우도록 채워지고, 내부 요소들의 위치는 고정되고, 여백만 커지도록 합니다.

- [ O ]  화면의 너비가 1920px 보다 작아질 때, “판다마켓” 로고의 왼쪽 여백 200px, “로그인" 버튼의 오른쪽 여백 200px이 유지되고, 화면의 너비가 작아질수록 두 요소 간 거리가 가까워지도록 설정합니다.

- [ O ]  화면의 너비가 1920px 이상이면 내부에 있는 요소 간 동일한 간격을 유지하며 가운데 정렬해야 합니다.

- [ O ]  화면의 너비가 1920px 보다 작아질 때, 최하단에 있는 “codeit-2024”의 왼쪽 여백 200px과 SNS 아이콘들의 오른쪽 여백 200px을 유지하면서 가운데 있는 “Privacy Policy”, “FAQ” 요소와 각각 동일한 간격을 유지하며 가까워져야 합니다.

- [ O ]  클릭으로 기능이 동작해야 하는 경우, 사용자가 클릭할 수 있는 요소임을 알 수 있도록 CSS 속성 cursor: pointer로 설정합니다.

### 심화 요구사항

- [ X ] reset.css를 설정해 주세요.
- [ X ] 사용자의 브라우저 설정에 따라 기본 폰트 크기 설정이 변화함에 따라서 페이지의 요소 간 간격, 요소의 크기, font-size 등 모든 크기와 관련된 값이 크고 작아지도록 설정해 주세요.

## 멘토에게

- 코드를 간결화 해보기는 했는데 혹시 불필요한 부분이 있는지 궁금합니다.
- 지금 저의 코드가 유지보수에 용이한 코드인지 궁금합니다.

## netlify에 업로한 저의 사이트 주소입니다. 
→   https://welcome-panda-market.netlify.app/

2024-08-05 12:32 UTC, MCprotein commented
@Seo-Yurim 유림님! 다른분들이 하신것처럼 체크박스 마크다운문법으로 수정해주세요! 
ex) https://github.com/codeit-sprint-fullstack/2-Sprint-Mission-FE/pull/5

Refs: https://jihyehwang09.github.io/2019/05/06/TIL-2019-05-06/

2024-08-05 13:42 UTC, kipid commented
저한테도 메일이 와요.

2024년 8월 5일 (월) 오후 9:33, YoonSoo_Shin ***@***.***>님이 작성:

> @Seo-Yurim <https://github.com/Seo-Yurim> 유림님! 다른분들이 하신것처럼 체크박스 마크다운문법으로
> 수정해주세요!
> ex) #5
> <https://github.com/codeit-sprint-fullstack/2-Sprint-Mission-FE/pull/5>
>
> Refs: https://jihyehwang09.github.io/2019/05/06/TIL-2019-05-06/
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/codeit-sprint-fullstack/2-Sprint-Mission-FE/pull/4#issuecomment-2268964846>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB3LHXZMUL2HVAF6K7MU6J3ZP5WILAVCNFSM6AAAAABL4AUQWWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENRYHE3DIOBUGY>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***
> .com>
>

2024-08-06 00:06 UTC, Seo-Yurim commented on style.css
> +.footer-Q {
이름들을 뭐라 설정할지 고민하다가 일단 대충 짓고 나중에 바꾸려했는데 까먹었네요 ㅠㅠ ! 수정하겠습니다 !!

2024-08-06 00:07 UTC, Seo-Yurim commented on style.css
> +.SNS {
넵 ! SNS가 줄임말이라 소문자보다는 대문자로 쓰는게 익숙해서 저도 모르게 그렇게 쓴 것 같은데 혹시 소문자로 하는  편이 나을까요?!

2024-08-06 04:59 UTC, MCprotein commented on style.css
> +.footer-Q {
@Seo-Yurim 넵 가독성 있게 작성하는게 좋을거같아요!

2024-08-06 05:05 UTC, MCprotein commented on style.css
> +.SNS {
@Seo-Yurim 하나의 컨벤션으로 통일하는게 좋긴하지만 (kebab-case) 특별한 규칙을 만들고 이후에도 일관성있게 코드를 작성하면 상관없을거같아요! ex) 앞으로 줄임말은 모두 대문자로 통일
https://github.com/reactjs/react.dev/blob/main/src/styles/algolia.css
react 공식문서 페이지 css도 PascalCase랑 kebab-case를 섞어서 쓰고있긴하네요 ㅎㅎ

2024-08-06 11:59 UTC, MCprotein requested changes

2024-08-06 11:59 UTC, MCprotein commented on style.css
> +  max-width: 1920px;
@Seo-Yurim 유림님! 아래 요구사항에 대한 예시 보여드립니다! 수정부탁드려요! 
- 화면의 너비가 1920px 이상이면 하늘색 배경색은 너비를 꽉 채우도록 채워지고, 내부 요소들의 위치는 고정되고, 여백만 커지도록 합니다.
![스크린샷 2024-08-06 오후 8 50 53](https://github.com/user-attachments/assets/a3ff6d30-62cb-418b-b462-7d0c4a5abe95)

2024-08-07 02:15 UTC, Seo-Yurim commented on style.css
> +  max-width: 1920px;
수정 완료하여 다시 커밋하였습니다 !!

2024-08-07 03:26 UTC, MCprotein commented on style.css
> +  max-width: 1920px;
@Seo-Yurim 고생하셨습니다!

2024-08-07 03:26 UTC, MCprotein approved these changes

2024-08-07 04:41 UTC, MCprotein requested changes
@Seo-Yurim 
> 사용자의 브라우저 설정에 따라 기본 폰트 크기 설정이 변화함에 따라서 페이지의 요소 간 간격, 요소의 크기, font-size 등 모든 크기와 관련된 값이 크고 작아지도록 설정해 주세요.

이 요구사항에 체크가 되어있는데, css 파일 보면 font-size 에만 적용이 되어있는거같아요! 확인한번부탁드려요!

2024-08-07 05:58 UTC, MCprotein commented on style.css
> +.footer-Q {
@Seo-Yurim  CSS naming convention으로 참고할만한 좋은 자료 공유드려요!
https://google.github.io/styleguide/htmlcssguide.html#ID_and_Class_Name_Delimiters

2024-08-07 06:36 UTC, Seo-Yurim commented
@MCprotein 폰트 사이즈에만 꽂혀서 다른 부분을 보지못했던 것 같습니다 ㅠㅠ 수정하여 재업로드 하였습니다 !!

2024-08-07 09:46 UTC, MCprotein commented
> @MCprotein 폰트 사이즈에만 꽂혀서 다른 부분을 보지못했던 것 같습니다 ㅠㅠ 수정하여 재업로드 하였습니다 !!

넵 고생하셨습니다!

2024-08-09 10:34 UTC, merged

2024-08-12 15:30 UTC, MCprotein commented on style.css
> +  height: 1.125rem;
@Seo-Yurim 요거 제가 놓쳤던 부분인데, 똑같은 요소 중복으로 작성이되어서요! 수정부탁드립니다!

2024-08-13 00:49 UTC, Seo-Yurim commented on style.css
> +  height: 1.125rem;
수정 완료하였습니다 !!

2024-08-13 04:27 UTC, MCprotein commented on style.css
> +  height: 1.125rem;
@Seo-Yurim 이미 merge가 된 상태에서는 push 하셔도 반영이 되지 않아요! 
미션3 진행하실때 이부분도 함께 수정해서 PR 올려주세요!