[김태영] Sprint 3
codeit-sprint-fullstack/2-Sprint-Mission-FE pull request #41
Opened 2024-08-16 07:00 UTC by csbizz

## 요구사항

### 기본

공통

    [ ] Github에 스프린트 미션 PR을 만들어 주세요.

로그인, 회원가입 페이지 공통

    [ ] 로그인 및 회원가입 페이지의 이메일, 비밀번호, 비밀번호 확인 input에 필요한 유효성 검증 함수를 만들고 적용해 주세요.
    [ ] 이메일 input에서 focus out 할 때, 값이 없을 경우 input에 빨강색 테두리와 아래에 “이메일을 입력해주세요.” 빨강색 에러 메세지를 보입니다.
    [ ] 이메일 input에서 focus out 할 때, 이메일 형식에 맞지 않는 경우 input에 빨강색 테두리와 아래에 “잘못된 이메일 형식입니다” 빨강색 에러 메세지를 보입니다.
    [ ] 비밀번호 input에서 focus out 할 때, 값이 없을 경우 아래에 “비밀번호를 입력해주세요.” 에러 메세지를 보입니다
    [ ] 비밀번호 input에서 focus out 할 때, 값이 8자 미만일 경우 아래에 “비밀번호를 8자 이상 입력해주세요.” 에러 메세지를 보입니다.
    [ ] input 에 빈 값이 있거나 에러 메세지가 있으면 ‘로그인’ 버튼은 비활성화 됩니다.
    [ ] Input 에 유효한 값을 입력하면 ‘로그인' 버튼이 활성화 됩니다.
    [ ] 활성화된 ‘로그인’ 버튼을 누르면 “/items” 로 이동합니다

const USER_DATA = [
    { email: 'codeit1@codeit.com', password: "codeit101!" },
    { email: 'codeit2@codeit.com', password: "codeit202!" },
    { email: 'codeit3@codeit.com', password: "codeit303!" },
    { email: 'codeit4@codeit.com', password: "codeit404!" },
    { email: 'codeit5@codeit.com', password: "codeit505!" },
    { email: 'codeit6@codeit.com', password: "codeit606!" },
];

로그인 페이지

    [ ] 이메일과 비밀번호를 입력하고 로그인 버튼을 누른 후, 다음 조건을 참조하여 로그인 성공 여부를 alert 메시지로 출력합니다.
        만약 입력한 이메일이 데이터베이스(USER_DATA)에 없거나, 이메일은 일치하지만 비밀번호가 틀린 경우, '비밀번호가 일치하지 않습니다.'라는 메시지를 alert로 표시합니다
        만약 입력한 이메일이 데이터베이스에 존재하고, 비밀번호도 일치할 경우, “/items”로 이동합니다.

회원가입

    [ ] 회원가입을 위해 이메일, 닉네임, 비밀번호, 비밀번호 확인을 입력한 뒤, 회원가입 버튼을 클릭하세요. 그 후에는 다음 조건에 따라 회원가입 가능 여부를 alert로 알려주세요.
        1. 입력한 이메일이 이미 데이터베이스(USER_DATA)에 존재하는 경우, '사용 중인 이메일입니다'라는 메시지를 alert로 표시합니다.
        2. 입력한 이메일이 데이터베이스(USER_DATA)에 없는 경우, 회원가입이 성공적으로 처리되었으므로 로그인 페이지(”/login”)로 이동합니다.

### 심화

공통

    [ ] 페이스북, 카카오톡, 디스코드, 트위터 등 SNS에서 판다마켓 랜딩 페이지(“/”) 공유 시 미리보기를 볼 수 있도록 랜딩 페이지 메타 태그를 설정합니다.
    [ ] 미리보기에서 제목은 “판다마켓”, 설명은 “일상에서 모든 물건을 거래해보세요”로 설정합니다.
    [ ] 주소와 이미지는 자유롭게 설정하세요.
    [ ] 로그인, 회원가입 페이지에 공통으로 사용하는 로직이 있다면, 반복하지 않고 공통된 로직을 모듈로 분리해 사용해 주세요.

랜딩 페이지

    [ ] 브라우저에 현재 보이는 화면의 영역(viewport) 너비를 기준으로 분기되는 반응형 디자인을 적용합니다.
        PC: 1200px 이상
        Tablet: 744px 이상 ~ 1199px 이하
        Mobile: 375px 이상 ~ 743px 이하
        375px 미만 사이즈의 디자인은 고려하지 않습니다
    [ ] Tablet 사이즈로 작아질 때 최소 좌우 여백이 “판다마켓” 로고의 왼쪽에 여백 24px, “로그인” 버튼 오른쪽 여백 24px을 유지할 수 있도록 “판다마켓” 로고와 “로그인" 버튼의 간격이 가까워집니다.
    [ ] Mobile 사이즈로 작아질 때 최소 좌우 여백이 “판다마켓” 로고의 왼쪽에 여백 16px, “로그인” 버튼 오른쪽 여백 16px을 유지할 수 있도록 “판다마켓” 로고와 “로그인" 버튼의 간격이 가까워집니다.
    [ ] PC, Tablet 사이즈의 이미지 크기는 고정값을 사용합니다.
    [ ] Mobile 사이즈의 이미지는 좌우 여백 32px을 제외하고 이미지 영역이 꽉 차게 구현합니다. (이때 가로가 커지는 비율에 맞춰 세로도 커져야 합니다.)
    [ ] Mobile 사이즈 너비가 커지면, “Privacy Policy”, “FAQ”, “codeit-2023”이 있는 영역과 SNS 아이콘들이 있는 영역의 사이 간격이 커집니다.

로그인, 회원가입 페이지 공통

    [ ] Tablet 사이즈에서 내부 디자인은 PC사이즈와 동일합니다.
    [ ] Mobile 사이즈에서 좌우 여백 16px 제외하고 내부 요소들이 너비를 모두 차지합니다.
    [ ] Mobile 사이즈에서 내부 요소들의 너비는 기기의 너비가 커지는 만큼 커지지만 400px을 넘지 않습니다.
    [ ] 오류 메시지 모달을 구현합니다. 모달 내 내용은 alert 메시지와 동일합니다.
    [ ] 비밀번호 및 비밀번호 확인 입력란에 눈 모양 아이콘 클릭 시 비밀번호 표시/숨기기 토글이 가능합니다. 기본 상태는 비밀번호 숨김으로 설정합니다.

## 주요 변경사항

- PR 생성
- 기본 요구사항

## 스크린샷

## 멘토에게

- 진행중입니다.

2024-08-16 10:53 UTC, MCprotein commented on src/js/login.mjs
> +const loginBtn = document.querySelector('#login-field').lastElementChild;
@csbizz 태영님! lastElementChild 이거보다는 id를 지정해서 가져오려고하는 요소만 딱 가져오는건 어떨까요?
그리고 querySelector vs getElementBy~ 차이도 검색해보시면 좋겠네요!

2024-08-16 11:07 UTC, MCprotein commented on src/js/login.mjs
> +    if(!verification.verifyId(e.target.value)) {
@csbizz 요거 제가 디코 채널에 올린 prettier 설정 해보고 수정해주세요!

2024-08-16 11:31 UTC, MCprotein commented on src/js/login.mjs
> +    }
아래 코드처럼 간단하게 할 수도 있는데, 어떠세요?
```suggestion
    if (!verification.verifyPw(inputId.value, inputPw.value)) {
      return alert('비밀번호가 일치하지 않습니다.');
    }

    location.href = "../items";
```

2024-08-16 11:40 UTC, MCprotein commented on src/js/verification.mjs
> +    return false;
@csbizz  요거를 iterator 함수를 사용하면 아래와 같이 바꿀수 있어요! iterator 함수에 대해서도 찾아보세요!

https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/some
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/find

```suggestion
    return !!USER_DATA.find(user => user.email === email && user.password === pw)
```
```suggestion
    return USER_DATA.some(user => user.email === email && user.password === pw)
```

2024-08-18 07:53 UTC, csbizz commented on src/js/verification.mjs
> +    return false;
find 사용례에서 !!는 어떤 의미인가요? !는 부정연산자인거로 알고 있는데 부정연산자를 2번 사용하신 것 같진 않은데

2024-08-18 08:44 UTC, MCprotein commented on src/js/login.mjs
> +const loginBtn = document.querySelector('#login-field').lastElementChild;
@csbizz 태영님! 코멘트 관련해서 해결되었으면 해결되었다고 답변남겨주세요!

2024-08-18 08:44 UTC, MCprotein commented on src/js/login.mjs
> +    if(!verification.verifyId(e.target.value)) {
@csbizz 태영님! 코멘트 관련해서 해결되었으면 해결되었다고 답변남겨주세요!

2024-08-18 09:14 UTC, MCprotein commented on src/js/login.mjs
> +    }
@csbizz 태영님! 코멘트 관련해서 해결되었으면 해결되었다고 답변남겨주세요!

2024-08-18 09:31 UTC, MCprotein commented on src/js/verification.mjs
> +    return false;
@csbizz 
부정연산자가 맞아요! 
truthy, falsy 개념에 대해서 아시나요? 아직 배우지 않으셨으면 아래 링크를 참조해보세요
- https://developer.mozilla.org/ko/docs/Glossary/Truthy
- https://developer.mozilla.org/ko/docs/Glossary/Falsy

어떤 값에 대해 두 번 부정연산자 처리를 하면 해당 값에 대한 truthy, falsy 값을 나타내는 boolean 으로 값이 변환됩니다

예를들어 USER_DATA.find(user => user.email === email && user.password === pw) 의 값이 
{email: '어쩌구', password: '저쩌구'} 요렇게 나왔다면, 이 값은 truthy 이므로 ! 를 한 번 처리해주면 false가 됩니다. 이 때 한 번 더 ! 를 처리해주면 true가 됩니다.

2024-08-18 10:42 UTC, csbizz commented on src/js/login.mjs
> +const loginBtn = document.querySelector('#login-field').lastElementChild;
버튼에 아이디 설정해서 요소 추출했습니다

2024-08-18 10:42 UTC, csbizz commented on src/js/login.mjs
> +    if(!verification.verifyId(e.target.value)) {
프리티어 설정 완료했습니다

2024-08-18 10:43 UTC, csbizz commented on src/js/login.mjs
> +    }
early return pattern으로 변경했습니다

2024-08-18 10:44 UTC, csbizz commented on src/js/verification.mjs
> +    return false;
오... 이런 사용법은 생각 못해봤네요 감사합니다

2024-08-18 12:42 UTC, MCprotein commented
@csbizz 태영님! 앞으로는 커밋 메세지 컨벤션을 정해서 맞춰주세요!
그리고 기능 단위로 커밋 하는걸 추천드리지만, 꼭 그렇게 하진 않아도 괜찮으니 롤백이 용이하도록 커밋을 해주세요!

아래 글들 읽어보시는것도 좋겠네요! 
- https://jaeheon.kr/257
- https://tech.10000lab.xyz/git/git-commit-discipline.html

2024-08-20 13:45 UTC, MCprotein requested changes

2024-08-20 13:45 UTC, MCprotein commented on src/js/verification.mjs
> +  return USER_DATA.some(usr.email === email && usr.password === pw);
@csbizz 태영님! 여기 문법이 잘못되었네요! 오타인거같은데 확인부탁드릴게요!

2024-08-20 13:47 UTC, MCprotein commented on src/js/signup.mjs
> +const loginBtn = document.querySelector('#login-field').lastElementChild;
@csbizz 여기도 https://github.com/codeit-sprint-fullstack/2-Sprint-Mission-FE/pull/41#discussion_r1719688322 요거처럼 하면 어떨까요?

2024-08-21 15:12 UTC, csbizz commented on src/js/verification.mjs
> +  return USER_DATA.some(usr.email === email && usr.password === pw);
return USER_DATA.some((usr) => usr.email === email && usr.password === pw);
위와 같이 수정했습니다

2024-08-21 15:12 UTC, csbizz commented on src/js/signup.mjs
> +const loginBtn = document.querySelector('#login-field').lastElementChild;
버튼 아이디로 요소 선택하게 변경햇습니다

2024-08-26 04:19 UTC, MCprotein commented
@csbizz 태영님! netlify 주소도 올려주세요!

2024-08-26 04:19 UTC, merged

2024-08-26 07:48 UTC, csbizz commented
> @csbizz 태영님! netlify 주소도 올려주세요!

https://sprintmission1kty.netlify.app/
주소가 이전과 달라지지 않아서 올리지 않았네요 다음부턴 변경사항 생기면 올리겠습니다

2024-08-27 13:49 UTC, MCprotein commented
@csbizz 태영님! 미션1,2 에서 화면 확대시 nav랑 footer 일정한 간격으로 고정되는거 하셨던거같은데 netlify에 반영이 안되어잇는거같아요 확인함해주실 수 있을까요?

2024-08-28 04:53 UTC, csbizz commented
> @csbizz 태영님! 미션1,2 에서 화면 확대시 nav랑 footer 일정한 간격으로 고정되는거 하셨던거같은데 netlify에 반영이 안되어잇는거같아요 확인함해주실 수 있을까요?

랜딩 페이지 레이아웃 변경하면서 설정이 없어진 것 같네요...