basic 박효빈
codeit-sprint-fullstack/2-Sprint-Mission-FE pull request #51
Opened 2024-08-17 13:26 UTC by hyobiin9

## 요구사항

### 기본

- [x]
- []
- []

### 심화

- [x]
- []

## 주요 변경사항

-
-

## 스크린샷

![image](이미지url)

## 멘토에게

-
-
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2024-08-20 14:55 UTC, json9512 requested changes
# 요약
- 피그마 기준 누락된 것이 있어요. (로그인 버튼 활성화 시 스타일 변경)
- 코드를 한번 정리할 수 있을 것 같아요

고생하셨습니다! 👍 

스프린트 미션 3 제출 완료하면 다시 코드리뷰 하도록 할게요

2024-08-20 14:55 UTC, json9512 commented on login/index.js
> +  try {
`try...catch` 구문의 경우 이런 형태로 작성해주시면 됩니다!

```js
try {
 //..
} catch (e) {
 //..
} finally {
 //..
}
```

(중괄호 옆에 명령어를 붙여서 작성해요)

2024-08-20 14:55 UTC, json9512 commented on login/index.js
> +function validity_email() {
함수의 경우 동사를 사용해주는게 좀 더 의미가 명확해요!
그리고 js의 경우 함수명은 `camelCase`를 사용해서 작성하는게 일반적이에요.

`validity_email` -> `validateEmail`

참고:
- [camelCase](https://developer.mozilla.org/ko/docs/Glossary/Camel_case)

2024-08-20 14:55 UTC, json9512 commented on login/index.js
> +    button();
이것은 무엇을 하는 함수인가요? 🤔

2024-08-20 14:55 UTC, json9512 commented on login/index.js
> +function button() {
좀 더 명확한 의미의 함수명을 작성해주세요

2024-08-20 14:55 UTC, json9512 commented on login/index.js
> +  if (email_input.classList.contains('pass') && pw_input.classList.contains('pass')) {
현재 로직은 `email_input`과 `pw_input`에 `pass, fail`을 class로 담아서 상태를 관리하는 형태에요.

다른 방식으로는 해결할 수 없을까요? 🤔

2024-08-20 14:55 UTC, json9512 commented on login/index.js
> +    if (match_data.password === new_data.password) {
이 로직도 `match_data`를 찾는 `USER_DATA.find`에서 같이 처리해줄 수 있지 않나요? 🤔

2024-08-20 14:55 UTC, json9512 commented on login/index.js
> +      alert('로그인 성공');
로그인 성공 시에는 alert을 안 띄워줘도 될 것 같아요!

2024-08-20 14:55 UTC, json9512 commented on login/index.js
> +    else if (!email_input.checkValidity()) {
email 형식이 `test@` 일 때도 정상적인 email로 처리되고 있어서 올바른 에러 메세지가 뜨지 않고 있습니다

2024-08-20 14:55 UTC, json9512 commented on login/index.js
> +    loginBtn.classList.remove('inactive');
모든 input 값이 유효할 때 로그인 버튼이 활성화 되어야하는데 안되고 있는 것 같아요!

2024-08-20 14:55 UTC, json9512 commented on login/index.js
> +    loginBtn.classList.remove('inactive');
정확히는 스타일 변화가 없습니다

2024-08-21 00:43 UTC, hyobiin9 commented on login/index.js
> +function validity_email() {
네 알겠습니다! 수정 완료하였습니다

2024-08-21 00:43 UTC, hyobiin9 commented on login/index.js
> +function button() {
수정 완료하였습니다

2024-08-21 00:45 UTC, hyobiin9 commented on login/index.js
> +    loginBtn.classList.remove('inactive');
수정하였습니다

2024-08-21 00:49 UTC, hyobiin9 commented on login/index.js
> +    button();
try catch문의 이벤트가 발생하고 난 후에 button 함수(email, pw가 정보와 일치하는지 확인하는 기능)을 실행하고 싶어서 작성하였습니다.

2024-08-21 00:53 UTC, hyobiin9 commented on login/index.js
> +    if (match_data.password === new_data.password) {
![image](https://github.com/user-attachments/assets/5fcebc3b-9145-4235-9b2c-b137b9ac233a)

2024-08-21 00:53 UTC, hyobiin9 commented on login/index.js
> +    if (match_data.password === new_data.password) {
이러한 코드 형태를 말씀하시는건가요?

2024-08-21 00:57 UTC, hyobiin9 commented on login/index.js
> +    else if (!email_input.checkValidity()) {
수정 완료하였습니다!

2024-08-21 00:59 UTC, hyobiin9 commented on login/index.js
> +  if (email_input.classList.contains('pass') && pw_input.classList.contains('pass')) {
true false 형식의 느낌으로 pass fail을 사용하였습니다.
말씀하시는 다른 방법으로 생각나는건 list에 담아서 true false의 구조를 갖추는 형식밖에 생각이 나지 않습니다ㅠ

2024-08-26 05:16 UTC, hyobiin9 commented on login/index.js
> +      alert('로그인 성공');
삭제했습니다!

2024-08-28 12:33 UTC, json9512 commented on login/index.js
> +  try {
네 맞아요!
catch 문의 매개 변수를 생략하면 에러의 값은 따로 전달되지 않습니다. 만약, 매개 변수를 할당하면 해당 에러의 값을 받을 수 있고 특정 에러만 별도로 처리하도록 로직을 짤 수 있어요

2024-08-28 12:55 UTC, json9512 approved these changes

2024-08-28 12:55 UTC, json9512 commented on index.html
> +        <img class="loginbutton-img" src="img/login-button.png">
kebab-case는 띄어쓰기 를 `-`로 대체한다고 생각해주시면 됩니다!
`loginbutton-img` -> `login-button-img`의 형태가 올바른 표현입니다.

2024-08-28 12:55 UTC, json9512 commented on login/index.js
> +const email_input = document.querySelector('.input-email');
기본적으로 JS에서 변수 네이밍은 `pascalCase`이고 상수인 constant의 경우 간혹 `CAPITAL_SNAKE_CASE`로 적습니다.

여기서는 `emailInput`의 형태가 좀 더 JS 스러운 명칭이에요!

2024-08-28 12:55 UTC, json9512 commented on login/index.js
> +  if(isClicked){
자간 공백이 필요해보여요!
`if(isClicked){` -> `if (isClicked) { `

2024-08-28 12:55 UTC, json9512 commented on login/index.js
> +function validateEmail() {
좀 더 간결하게 짤 수 있을 것 같아요!
굳이 `error`를 변수로 할당할 필요가 없습니다

```ts
function validatePw() {
  let error;
  try {
    if (pw_input.value === '') {
      pw_input.classList.add('fail');
      error = new TypeError('비밀번호를 입력해주세요.');
      throw error;
    }
    else if (pw_input.value.length < 8) {
      pw_input.classList.add('fail');
      error = new TypeError('비밀번호를 8자 이상 입력해주세요.');
      throw error;
    }
    else {
      pw_error.value = '';
      pw_input.classList.remove('fail');
      pw_input.classList.add('pass');
    }
  }

  catch {
    pw_input.classList.remove('pass');
    pw_error.value = error.message;
    pw_input.classList.add('fail');
  }

  finally {
    logButton();
  }
}
```
```ts
const setError = (message) => {
  pw_input.classList.add('fail');
  pw_input.classList.remove('pass');
  pw_error.value = message;
};

const clearError = () => {
  pw_input.classList.remove('fail');
  pw_input.classList.add('pass');
  pw_error.value = '';
};

function validatePw() {
  const MIN_LENGTH = 8;

  try {
    const password = pw_input.value.trim();

    if (password === '') {
      throw new TypeError('비밀번호를 입력해주세요.');
    }

    if (password.length < MIN_LENGTH) {
      throw new TypeError(`비밀번호를 ${MIN_LENGTH}자 이상 입력해주세요.`);
    }

    clearError();

  } catch (error) {
    setError(error.message);
  } finally {
    logButton();
  }
}

```

2024-08-28 12:55 UTC, json9512 commented on login/index.js
> +    logButton();
`logButton`으로 잘 변경해주셨지만 좋은 명칭은 아닙니다!
`log`라는 단어를 기록하다의 용도로 개발에서 많이 쓰는 단어라서요. ex. 로그 찍는다 -> 현재 상태를 확인한다/기록한다

따라서 `logButton`이라고 명칭 지으면 기록하는 행위와 연관되기 쉽습니다.
`loginButton`으로 풀어서 적는것이 더 명확한 것 같아요!

2024-08-28 12:55 UTC, json9512 commented on login/index.js
> +  console.log(33);
불필요한 console.log는 제거해주세요!

2024-08-28 13:03 UTC, json9512 commented
# 디자인
- 여전히 input과 label 간 간격이 안 맞긴합니다!
- 하나 팁을 드리자면 피그마에서 ctrl + click으로 원하는 요소를 선택하신 뒤, 거리를 비교하고 싶은 요소에 ctrl+alt+mouse 가져다대면 선택된 요소와 호버된 요소의 거리가 픽셀로 찍힙니다!
- 스샷에서는 16px이 둘의 공백이고 선택된 요소는 "비밀번호" 레이블, 거리를 비교하는 요소는 아래 인풋창입니다

![image](https://github.com/user-attachments/assets/ae918428-6c2c-428a-b603-048f22972231)

2024-08-28 13:19 UTC, json9512 commented on login/index.js
> +  if (email_input.classList.contains('pass') && pw_input.classList.contains('pass')) {
넵! 우선은 이렇게 작업하셔도 무방합니다

2024-08-28 13:22 UTC, json9512 commented
요거 작업 컨플릭트가 나는데요!
작업 브랜치에서 (hyobiin9:Basic-박효빈-sprint3)에서 `git merge codeit-sprint-fullstack:Basic-박효빈`을 시도하시면 컨플릭트를 해결하라는 파일들이 뜰텐데, 해당 파일들 변경 사항 추적하셔서 최근 코드로 바꿔주시고 다시 git add . -> git commit -> git push 해주시면 됩니다!

제가 작업 해드리고 싶은데 효빈님 개인 레포로 포크한 작업물이어서 제가 따로 권한이 없어서요!

2024-08-29 01:10 UTC, hyobiin9 commented on login/index.js
> +  try {
우선은 이렇게 작성해놔도 되는걸까요?

2024-08-29 01:12 UTC, hyobiin9 commented on login/index.js
> +    if (match_data.password === new_data.password) {
아 네! 다시 확인해보니 '등록된 정보가 없습니다'는 따로 경우의 수를 나누지 않았네요. 수정 했습니다!

2024-08-29 01:26 UTC, hyobiin9 commented on login/index.js
> +  if(isClicked){
수정 완료했습니다!

2024-08-29 01:28 UTC, hyobiin9 commented on login/index.js
> +    logButton();
넵 수정했습니다!

2024-08-29 01:29 UTC, hyobiin9 commented on login/index.js
> +  console.log(33);
삭제했습니다~!!

2024-08-29 01:35 UTC, hyobiin9 commented on login/index.js
> +const email_input = document.querySelector('.input-email');
네! 수정 했습니다!!

2024-08-29 01:40 UTC, hyobiin9 commented on login/index.js
> +function validateEmail() {
이렇게 정리하니 코드가 훨씬 간결하고 가독성이 좋아진 느낌이네요 수정하였습니다!

2024-08-30 12:23 UTC, closed without merging