Sprint3 기본 요구사항 작성
codeit-sprint-fullstack/2-Sprint-Mission-FE pull request #52
Opened 2024-08-18 07:55 UTC by Seo-Yurim

# 요구사항

## 기본 요구사항
### 공통

- [x] Github에 스프린트 미션 PR을 만들어 주세요.

### 로그인, 회원가입 페이지 공통

- [x] 로그인 및 회원가입 페이지의 이메일, 비밀번호, 비밀번호 확인 input에 필요한 유효성 검증 함수를 만들고 적용해 주세요.
- [x] 이메일 input에서 focus out 할 때, 값이 없을 경우 input에 빨강색 테두리와 아래에 “이메일을 입력해주세요.” 빨강색 에러 메세지를 보입니다.
- [x] 이메일 input에서 focus out 할 때, 이메일 형식에 맞지 않는 경우 input에 빨강색 테두리와 아래에 “잘못된 이메일 형식입니다” 빨강색 에러 메세지를 보입니다.
- [x] 비밀번호 input에서 focus out 할 때, 값이 없을 경우 아래에 “비밀번호를 입력해주세요.” 에러 메세지를 보입니다
- [x] 비밀번호 input에서 focus out 할 때, 값이 8자 미만일 경우 아래에 “비밀번호를 8자 이상 입력해주세요.” 에러 메세지를 보입니다.
- [x] input 에 빈 값이 있거나 에러 메세지가 있으면 ‘로그인’ 버튼은 비활성화 됩니다.
- [x] Input 에 유효한 값을 입력하면 ‘로그인' 버튼이 활성화 됩니다.
- [x] 활성화된 ‘로그인’ 버튼을 누르면 “/items” 로 이동합니다

const USER_DATA = [
    { email: 'codeit1@codeit.com', password: "codeit101!" },
    { email: 'codeit2@codeit.com', password: "codeit202!" },
    { email: 'codeit3@codeit.com', password: "codeit303!" },
    { email: 'codeit4@codeit.com', password: "codeit404!" },
    { email: 'codeit5@codeit.com', password: "codeit505!" },
    { email: 'codeit6@codeit.com', password: "codeit606!" },
];

### 로그인 페이지
 
- [x] 이메일과 비밀번호를 입력하고 로그인 버튼을 누른 후, 다음 조건을 참조하여 로그인 성공 여부를 alert 메시지로 출력합니다.
- [x] 만약 입력한 이메일이 데이터베이스(USER_DATA)에 없거나, 이메일은 일치하지만 비밀번호가 틀린 경우, '비밀번호가 일치하지 않습니다.'라는 메시지를 alert로 표시합니다
- [x] 만약 입력한 이메일이 데이터베이스에 존재하고, 비밀번호도 일치할 경우, “/items”로 이동합니다.

### 회원가입

- [x] 회원가입을 위해 이메일, 닉네임, 비밀번호, 비밀번호 확인을 입력한 뒤, 회원가입 버튼을 클릭하세요. 그 후에는 다음 조건에 따라 회원가입 가능 여부를 alert로 알려주세요.
- [x] 입력한 이메일이 이미 데이터베이스(USER_DATA)에 존재하는 경우, '사용 중인 이메일입니다'라는 메시지를 alert로 표시합니다.
- [x] 입력한 이메일이 데이터베이스(USER_DATA)에 없는 경우, 회원가입이 성공적으로 처리되었으므로 로그인 페이지(”/login”)로 이동합니다.

## 심화 요구사항
### 공통

- [ ] 페이스북, 카카오톡, 디스코드, 트위터 등 SNS에서 판다마켓 랜딩 페이지(“/”) 공유 시 미리보기를 볼 수 있도록 랜딩 페이지 메타 태그를 설정합니다.
- [ ] 미리보기에서 제목은 “판다마켓”, 설명은 “일상에서 모든 물건을 거래해보세요”로 설정합니다.
- [ ] 주소와 이미지는 자유롭게 설정하세요.
- [ ] 로그인, 회원가입 페이지에 공통으로 사용하는 로직이 있다면, 반복하지 않고 공통된 로직을 모듈로 분리해 사용해 주세요.

### 랜딩 페이지

- [ ] 브라우저에 현재 보이는 화면의 영역(viewport) 너비를 기준으로 분기되는 반응형 디자인을 적용합니다.
        - PC: 1200px 이상
        - Tablet: 744px 이상 ~ 1199px 이하
        - Mobile: 375px 이상 ~ 743px 이하
        - 375px 미만 사이즈의 디자인은 고려하지 않습니다
- [ ] Tablet 사이즈로 작아질 때 최소 좌우 여백이 “판다마켓” 로고의 왼쪽에 여백 24px, “로그인” 버튼 오른쪽 여백 24px을 유지할 수 있도록 “판다마켓” 로고와 “로그인" 버튼의 간격이 가까워집니다.
- [ ] Mobile 사이즈로 작아질 때 최소 좌우 여백이 “판다마켓” 로고의 왼쪽에 여백 16px, “로그인” 버튼 오른쪽 여백 16px을 유지할 수 있도록 “판다마켓” 로고와 “로그인" 버튼의 간격이 가까워집니다.
- [ ] PC, Tablet 사이즈의 이미지 크기는 고정값을 사용합니다.
- [ ] Mobile 사이즈의 이미지는 좌우 여백 32px을 제외하고 이미지 영역이 꽉 차게 구현합니다. (이때 가로가 커지는 비율에 맞춰 세로도 커져야 합니다.)
- [ ] Mobile 사이즈 너비가 커지면, “Privacy Policy”, “FAQ”, “codeit-2023”이 있는 영역과 SNS 아이콘들이 있는 영역의 사이 간격이 커집니다.

### 로그인, 회원가입 페이지 공통

- [ ] Tablet 사이즈에서 내부 디자인은 PC사이즈와 동일합니다.
- [ ] Mobile 사이즈에서 좌우 여백 16px 제외하고 내부 요소들이 너비를 모두 차지합니다.
- [ ] Mobile 사이즈에서 내부 요소들의 너비는 기기의 너비가 커지는 만큼 커지지만 400px을 넘지 않습니다.
- [ ] 오류 메시지 모달을 구현합니다. 모달 내 내용은 alert 메시지와 동일합니다.
- [ ] 비밀번호 및 비밀번호 확인 입력란에 눈 모양 아이콘 클릭 시 비밀번호 표시/숨기기 토글이 가능합니다. 기본 상태는 비밀번호 숨김으로 설정합니다.

---
## Netlify 주소
 → https://welcome-panda-market.netlify.app/
---
## 멘토에게
- 현재 기능 실현 중심으로 작성을 해서 변수 이름 및 코드가 길고, 중복되는 코드도 많습니다... ! 참고 부탁드립니다 ㅠㅠ

2024-08-18 09:59 UTC, MCprotein commented on .vscode/launch.json
> +    ]
@Seo-Yurim 오 디버깅 설정은 혼자 찾아서 하신건가요??

2024-08-18 10:00 UTC, MCprotein commented on login/index.html
> +          id="useremail"
@Seo-Yurim 이거 포맷이 왜이렇게 깨진건가요??

2024-08-18 10:00 UTC, MCprotein commented on login/login.js
> +const inputEmail = document.querySelector('#useremail');
@Seo-Yurim querySelector와 getElementById/Class 와의 차이점을 아시나요?

2024-08-18 10:08 UTC, MCprotein commented on login/login.js
> +  if (inputEmail.value !== '') {
@Seo-Yurim truthy, falsy 개념에 대해 아시나요?
- https://developer.mozilla.org/ko/docs/Glossary/Truthy
- https://developer.mozilla.org/ko/docs/Glossary/Falsy
이 개념을 적용하면 아래코드로 변경할 수 있어요
다만 모든 케이스에 대해 좋다는건 아니고, 이렇게 쓰면 좀더 코드를 간략하게 작성할수 있으니 참고하면 좋을거같아요!
```js
if (!inputEmail.value) {

}
```

2024-08-18 10:13 UTC, Seo-Yurim commented on .vscode/launch.json
> +    ]
VS Code 내에서 디버그를 한 번 눌러봤는데 그때 생긴 것 같아요 .. ! 정확히 무슨 내용인지는 알지 못합니다 ㅠㅠ

2024-08-18 10:14 UTC, Seo-Yurim commented on login/index.html
> +          id="useremail"
멘토님이 주신 프리티어 설정 적용하고나니 저렇게 되더라구요 근데 원래 저렇게 되는게 맞는지 몰라서 옵션을 좀 더 찾아보고 수정할 예정입니다 !!

2024-08-18 10:18 UTC, MCprotein requested changes

2024-08-18 10:18 UTC, MCprotein commented on login/login.js
> +  if (emailFormat.test(inputEmail.value)) {
@Seo-Yurim 
순수함수 라는 개념을 하시나요?
순수함수는 멱등성을 유지해야되는데, 이 말은 같은 값을 넣으면 같은 결과를 반환해야된다는것을 의미해요.
그리고 함수의 재사용성을 위해서 inputEmail.value는 argument(parameter)로 받아서 처리하는게 좋아요! 
```js
// emailFormatChecker(inputEmail.value) 로 사용 
function emailFormatChecker(email) {
  if (emailFormat.test(email)) {
    
  }
}
```

2024-08-18 10:19 UTC, Seo-Yurim commented on login/login.js
> +const inputEmail = document.querySelector('#useremail');
안그래도 태영님 PR 코멘트보고 찾아봤었는데 querySelector를 쓰면 다양한 선택자 사용이 가능하고 getElemetById를 쓰면 속도가 빠르다 정도로 나오더라구요, querySelector가 편의성 측에서 더 좋은 것 같아서 사용하였는데 정확하게 상황에 따라 어떤 것을 사용해야할지는 모르겠습니다 ㅠㅠ

2024-08-18 10:21 UTC, MCprotein commented on login/index.html
> +          id="useremail"
@Seo-Yurim 헉.. 제가 알려드린거는 자바스크립트에 대한 프리티어라서 적용이 되는게 좀 이상하네요.. 한 번 알아보시고 잘안되면 말씀해주세요!

2024-08-18 10:21 UTC, Seo-Yurim commented on login/login.js
> +  if (inputEmail.value !== '') {
개념은 알고있었지만 활용할 생각은 하지못했습니다 ! 참고하여 코드 수정하겠습니다 !!

2024-08-18 10:22 UTC, MCprotein commented on .vscode/launch.json
> +    ]
@Seo-Yurim 저거는 vscode의 debugger 설정인데, 개발할때 반드시 사용해야 되는 기능이에요! 좀 어렵겠지만 사용법 찾아보시면 좋을거같아요!
console.log(다른 언어에서 println, ...) 찍어서 디버깅 하는거보다 훨씬 강력한 기능이에요

2024-08-18 10:24 UTC, MCprotein commented on login/login.js
> +const inputEmail = document.querySelector('#useremail');
@Seo-Yurim 뭘 사용하냐는 취향차이이긴하지만, 성능에서도 약간의 차이가 있긴 하더라구요! 찾아보시면 좋을거같아요!

2024-08-18 10:25 UTC, MCprotein commented on login/login.js
> +  const emailMatch = USER_DATA.find(
@Seo-Yurim 요런 변수는 isEmailValid, isPasswordValid 요런식으로 많이 사용해요!

2024-08-18 10:26 UTC, MCprotein commented on login/login.js
> +}
제가 태영님 PR에 작성한 코멘트를 보시고 else 를 굳이 사용하지 않도록 변경해보시겠어요?

2024-08-18 10:35 UTC, Seo-Yurim commented on login/login.js
> +  if (emailFormat.test(inputEmail.value)) {
그렇다면 inputEmail.addEventListener('focusout', emailFormatChecker(inputEmail.value));로 수정한 후 inputEmail.value 값이 email 파라미터로 전달되는 형태로 변경하는 것이 좋다는 말씀일까요?! 제가 이렇게 수정을 하니 제대로 기능이 동작되지않아서 혹시나 잘못 이해한 것인지 궁금합니다 .. 
<수정 부분>
function emailFormatChecker(email) {
  if (emailFormat.test(email)) {
    formatErrorEmail.classList.add('hide');
    inputEmail.classList.remove('error');
  } else {
    formatErrorEmail.classList.remove('hide');
    inputEmail.classList.add('error');
  }
}

inputEmail.addEventListener('focusout', emailFormatChecker(inputEmail.value));

2024-08-18 11:12 UTC, Seo-Yurim commented on login/index.html
> +          id="useremail"
제가 default format 설정으로도 해놔서 그랬던 것 같습니다 ! 지금은 해결되었습니다 :) !!

2024-08-18 11:45 UTC, Seo-Yurim commented on login/login.js
> +}
수정 완료하여 커밋하였습니다 ~!

2024-08-18 12:34 UTC, MCprotein commented on login/index.html
> +          id="useremail"
@Seo-Yurim 넵 다행이네요!

2024-08-18 12:36 UTC, MCprotein commented on login/login.js
> +  if (emailFormat.test(inputEmail.value)) {
@Seo-Yurim querySelector 로 가져온 변수의 타입은 Element 라는 객체인데, 이 객체 안에 addEventListener 함수의모양이 아래처럼 생겼다는것을 추측할 수 있어요
```js
Element = {
  addEventListener: (eventName, callbackFunction) => {
    ...
    callbackFunction(event)
    ...
  }
}
```
기존에 작성했던 `inputEmail.addEventListener('focusout', emailFormatChecker);` 요거는 `emailFormatChecke`r 함수 자체를 넣었기때문에 정상적으로 작동을 했던거에요.

`inputEmail.addEventListener('focusout', emailFormatChecker(inputEmail.value));` 이렇게 하신거에서`emailFormatChecker(inputEmail.value)` 이거는 `emailFormatChecker` 함수를 실행한 후 반환값이기때문에 정상작동을 하지 않았던거구요

`inputEmail.addEventListener('focusout',() =>  emailFormatChecker(inputEmail.value));` 이렇게 하면 정상작동할텐데,
`() =>  emailFormatChecker(inputEmail.value)` 이거 자체가  아래와 같은 의미이기때문에 내부적으로 익명함수(event) 가 되어 정상작동하는거에요!
```js
function 익명함수() {
  emailFormatChecker(inputEmail.value)
}
```

2024-08-18 12:44 UTC, MCprotein commented
@Seo-Yurim 유림님! 아래 링크를 참조해서 커밋 단위를 더 작게 해주시면 좋을거같아요! 

- https://jaeheon.kr/257#google_vignette
- https://tech.10000lab.xyz/git/git-commit-discipline.html

2024-08-19 08:39 UTC, Seo-Yurim commented on login/login.js
> +  const emailMatch = USER_DATA.find(
수정 완료하였습니다 !!

2024-08-19 09:46 UTC, MCprotein commented on signup/signup.js
> +function noneNameChecker() {
@Seo-Yurim 여기도 인풋과 아웃풋이 명확하면 좋겠네요!

2024-08-19 09:59 UTC, MCprotein commented on signup/signup.js
> +}
@Seo-Yurim 이 함수는 조건이 단순해서 이렇게 해도 상관은 없지만, 아래 코드와 비교했을때 어떤게 더 나으신가요?
코드 변경하라는건 아니고 유림님 의견이 궁금해서요!
```js
function showPasswordRepeat() {
  if (inputPasswordRepeat.type !== 'password') return

  inputPasswordRepeat.type = 'text';
  showPasswordRepeatIcon.classList.remove('hide');
  hidePasswordRepeatIcon.classList.add('hide');
}
```

2024-08-19 09:59 UTC, MCprotein commented on signup/signup.js
> +  if (inputPasswordRepeat.type == 'password') {
@Seo-Yurim 앗 그런데 === 가 아니라 ==를 사용하신 이유가 있을까요?

2024-08-19 10:04 UTC, Seo-Yurim commented on signup/signup.js
> +function noneNameChecker() {
수정하였습니다 !!

2024-08-19 10:08 UTC, Seo-Yurim commented on signup/signup.js
> +}
저는 아무래도 위에 코드가 더 눈에 익숙한 것 같아요 ! 어떤 차이점이 있는지 설명해주실 수 있을까요 ?! ....

2024-08-19 10:10 UTC, Seo-Yurim commented on signup/signup.js
> +  if (inputPasswordRepeat.type == 'password') {
엇 오타같습니다 ㅠㅠ login.js 코드를 signup.js로 거의 복사해서 사용해가지고 그런 것 같네요 수정완료했습니다 !!

2024-08-19 10:10 UTC, MCprotein commented on signup/signup.js
> +}
@Seo-Yurim 지금상태에서는 딱히 차이가 없구요! 조건이 더 많아지면 코드의 depth가 깊어지고, 그러면 나중에 알아보기가 어려워서 로직을 진행하지 않는 조건은 미리 탈락시키는거에요!

2024-08-19 10:18 UTC, Seo-Yurim commented on signup/signup.js
> +  if (inputPasswordRepeat.type == 'password') {
멘토님 제가 이 비밀번호 표시/숨기기 부분에서 inputPassword.type 값을 아규먼트로 받아서 처리하는 방식으로 수정하였는데 변경 후 동작을 안하더라구요 .. 혹시 뭐가 문제일까요 ? type 속성은 아규먼트로 받을 수 없는 것인가요 ...?

2024-08-20 04:57 UTC, MCprotein commented on signup/signup.js
> +  if (inputPasswordRepeat.type == 'password') {
@Seo-Yurim 
아래 코드 말씀하시는걸까요??
```js
// 비밀번호 표시/숨기기 설정
hidePasswordIcon.addEventListener('click', () =>
  showPassword(inputPassword.type)
);
showPasswordIcon.addEventListener('click', hidePassword(inputPassword.type));
```

2024-08-20 08:12 UTC, Seo-Yurim commented on signup/signup.js
> +  if (inputPasswordRepeat.type == 'password') {
넵 맞습니다 !!

2024-08-20 09:34 UTC, MCprotein commented on signup/signup.js
> +  if (inputPasswordRepeat.type == 'password') {
@Seo-Yurim 유림님 시간 괜찮으실때 저거 원리를 알려드리면 좋을거같은데, 혹시 디코에서 다른분들 모집해도 괜찮을까요?

2024-08-20 09:44 UTC, Seo-Yurim commented on signup/signup.js
> +  if (inputPasswordRepeat.type == 'password') {
엇 좋습니다 !!

2024-08-20 09:46 UTC, MCprotein commented on signup/signup.js
> +  if (inputPasswordRepeat.type == 'password') {
@Seo-Yurim 넵 감사합니다! 디코에서 말씀나눠요!

2024-08-20 13:21 UTC, MCprotein commented on commonValidate.js
> +  /^([0-9a-zA-Z_\.-]+)@([0-9a-zA-Z_-]+)(\.[0-9a-zA-Z_-]+){1,2}$/;
@Seo-Yurim 유림님! 지원님 PR에 코멘트 남긴거 보고 개선해주시면 좋을거같아요! 
https://github.com/codeit-sprint-fullstack/2-Sprint-Mission-FE/pull/53#discussion_r1722668887

2024-08-20 13:22 UTC, MCprotein commented on commonValidate.js
> +  }
@Seo-Yurim 요렇게 되어있는부분들 좀전에 디코에서 설명드렸던대로 수정해보시겠어요??

2024-08-20 13:30 UTC, MCprotein commented on signup/signup.js
> +  ) {
@Seo-Yurim 지금은 괜찮지만, 혹시 조건이 더 많아지게 되면 아래와 같이 해도 괜찮아요! 

```suggestion
const isEmailValid = email && emailFormat.test(email)
const isPasswordValid = password && password.length >= 8
const isRePasswordValid = rePassword && password === rePassword
  if (
    name &&
    isEmailValid &&
    isPasswordValid &&
    isRePasswordValid
  ) {
```

2024-08-20 13:42 UTC, MCprotein commented on signup/signup.js
> +  if (inputPasswordRepeat.type == 'password') {
@Seo-Yurim 유림님! 요기 == 안바꼇네용!

2024-08-20 13:42 UTC, MCprotein commented on signup/signup.js
> +  if (inputPasswordRepeat.type == 'text') {
@Seo-Yurim 유림님! 여기도 == 안바꼈네용!

2024-08-21 04:12 UTC, Seo-Yurim commented on commonValidate.js
> +  /^([0-9a-zA-Z_\.-]+)@([0-9a-zA-Z_-]+)(\.[0-9a-zA-Z_-]+){1,2}$/;
로그인/회원가입 페이지에서 공통적으로 사용하는 코드들은 따로 commonValidate.js 파일로 설정해놓은 상태입니다. emailFormat 변수는 login.js / signup.js 에서 버튼 활성화 시 사용하기 때문에 알려주신 1번 방식으로는 설정하지 못했는데, 그렇다면 export 해서 가져오는 것이 좋은건가요?! 

현재는 html에서  로그인/회원가입 페이지 둘 다
<script src="../commonValidate.js" charset="utf-8"></script>
 <script src="signup.js" charset="utf-8"></script>
이런 식으로 설정해놓았습니다. 

이런 방식은 좋지 않은 방식일까요 ㅠㅠ?

2024-08-21 04:55 UTC, MCprotein commented on commonValidate.js
> +  /^([0-9a-zA-Z_\.-]+)@([0-9a-zA-Z_-]+)(\.[0-9a-zA-Z_-]+){1,2}$/;
@Seo-Yurim 유림님! 말씀해주신게 잘 이해가 안되는데, emailFormat 이게 여러 파일에서 공통으로 사용하고있고, 각 파일별로 선언하고 있으니까 만약 commonValidate.js 여기다가 한번 선언하면 login.js/signup.js에서 가져다가 쓸 수 있다는 얘기였어요!

2024-08-21 05:52 UTC, Seo-Yurim commented on commonValidate.js
> +  /^([0-9a-zA-Z_\.-]+)@([0-9a-zA-Z_-]+)(\.[0-9a-zA-Z_-]+){1,2}$/;
아하 저는 이미 그런 방식으로 되어있었는데 코멘트 남겨주셔서 혹시나 꼭 export를 사용해서 가져와야하는건지 여쭤보고싶어서 그랬습니다 !! 제가 잘못이해했나봐요 ㅠㅠ

2024-08-21 06:21 UTC, MCprotein commented on commonValidate.js
> +  /^([0-9a-zA-Z_\.-]+)@([0-9a-zA-Z_-]+)(\.[0-9a-zA-Z_-]+){1,2}$/;
@Seo-Yurim 아.. 지원님이랑 다른 경우였는데 제가 착각했어요!! 혼란드려서 죄송해요ㅠ 
저는 export/import 하는 코드만 명시한다는 점에서 module 사용하는게 좋을거같은데, 확실한 근거가 없어서 찾아보고 말씀드릴게요!

2024-08-21 08:24 UTC, MCprotein commented on commonValidate.js
> +  /^([0-9a-zA-Z_\.-]+)@([0-9a-zA-Z_-]+)(\.[0-9a-zA-Z_-]+){1,2}$/;
@Seo-Yurim 유림님! 검색해도 잘 안나와서 개인적인 생각 + chatgpt 의견 종합해봤는데요, 의아한 부분이 있으면 말씀부탁드려요! 

결론: ESM (export/import) 사용이 더 적합
이유
1. 각 js 파일에서 공통 코드를 사용하는것이므로 js 파일별로 module system을 사용하는것이 더 직관적임. script 태그를 사용한다면 js 끼리의 행위를 html로 확장하게 됨
2. export, import 하는 대상을 명시할 수 있음. script를 사용하게 되면 모든 코드를 불러오게 되지만, module system 사용시 외부로 노출할 코드와 그렇지 않은 코드를 구분할 수 있음. 해당 코드를 사용하는 파일에서도 외부 파일의 어떤 코드가 필요한지 명확하게 알 수 있음. 특히 프로젝트 규모가 커질수록 이 현상은 두드러질것으로 예상됨.
3. 지금은 프레임워크나 라이브러리를 사용하지 않고 html, css, js 만 사용하고 있어서 이런 상황이 발생하는것인데, 리액트와 같은 기술을 사용한다면 자연스럽게 이런 방식으로 개발을 하지 않게 될것임. 또한 클라이언트단 코드는 배포할때 빌드를 진행하는데 일반적으로 빌드 시간이 오래걸리는 편이고, 빌드 후 파일 용량을 많이 신경써야하기때문에 불필요한 코드는 제거하는게 맞음. script 태그를 사용하여 사용하지 않는 코드까지 불러온다면 시간과 용량 측면에서 불필요한 오버헤드가 발생하기때문에 피해야한다고 생각됨

2024-08-22 11:40 UTC, Seo-Yurim commented on commonValidate.js
> +  }
수정 완료하였습니다 !

2024-08-22 11:40 UTC, Seo-Yurim commented on login/login.js
> +  if (!(emailMatch && passwordMatch)) {
이 방법은 생각하지 못했네요 이 방법으로 수정해보았습니다 !

2024-08-22 11:40 UTC, Seo-Yurim commented on signup/signup.js
> +  if (inputPasswordRepeat.type == 'text') {
수정 완료했습니다 !!

2024-08-22 11:41 UTC, Seo-Yurim commented on signup/signup.js
> +  if (inputPasswordRepeat.type == 'password') {
수정 완료했습니다 !

2024-08-22 11:42 UTC, Seo-Yurim commented on signup/signup.js
> +  ) {
오 !! 이 방법이 저는 눈에 더 잘 들어오고 좋은 것 같습니다 ! 말씀해주신 부분이랑 login.js 에서도 버튼 활성화 함수 부분에 적용시켜보았습니다 !

2024-08-26 04:19 UTC, merged