Feat: email, pw type 체크 및 입력 체크 기능 추가
codeit-sprint-fullstack/2-Sprint-Mission-FE pull request #53
Opened 2024-08-18 10:59 UTC by shinji530

## 요구사항
## 기본 요구사항
### 공통
- [x] Github에 스프린트 미션 PR을 만들어 주세요.
### 로그인, 회원가입 페이지 공통
- [x] 로그인 및 회원가입 페이지의 이메일, 비밀번호, 비밀번호 확인 input에 필요한 유효성 검증 함수를 만들고 적용해 주세요.
- [x] 이메일 input에서 focus out 할 때, 값이 없을 경우 input에 빨강색 테두리와 아래에 “이메일을 입력해주세요.” 빨강색 에러 메세지를 보입니다.
- [x] 이메일 input에서 focus out 할 때, 이메일 형식에 맞지 않는 경우 input에 빨강색 테두리와 아래에 “잘못된 이메일 형식입니다” 빨강색 에러 메세지를 보입니다.
- [x] 비밀번호 input에서 focus out 할 때, 값이 없을 경우 아래에 “비밀번호를 입력해주세요.” 에러 메세지를 보입니다
- [x] 비밀번호 input에서 focus out 할 때, 값이 8자 미만일 경우 아래에 “비밀번호를 8자 이상 입력해주세요.” 에러 메세지를 보입니다.
- [ ] input 에 빈 값이 있거나 에러 메세지가 있으면 ‘로그인’ 버튼은 비활성화 됩니다.
- [ ] Input 에 유효한 값을 입력하면 ‘로그인' 버튼이 활성화 됩니다.
- [ ] 활성화된 ‘로그인’ 버튼을 누르면 “/items” 로 이동합니다
```
const USER_DATA = [
{ email: '[codeit1@codeit.com](mailto:codeit1@codeit.com)', password: "codeit101!" },
{ email: '[codeit2@codeit.com](mailto:codeit2@codeit.com)', password: "codeit202!" },
{ email: '[codeit3@codeit.com](mailto:codeit3@codeit.com)', password: "codeit303!" },
{ email: '[codeit4@codeit.com](mailto:codeit4@codeit.com)', password: "codeit404!" },
{ email: '[codeit5@codeit.com](mailto:codeit5@codeit.com)', password: "codeit505!" },
{ email: '[codeit6@codeit.com](mailto:codeit6@codeit.com)', password: "codeit606!" },
];

```
### 로그인 페이지
- [ ] 이메일과 비밀번호를 입력하고 로그인 버튼을 누른 후, 다음 조건을 참조하여 로그인 성공 여부를 alert 메시지로 출력합니다.
- [ ] 만약 입력한 이메일이 데이터베이스(USER_DATA)에 없거나, 이메일은 일치하지만 비밀번호가 틀린 경우, '비밀번호가 일치하지 않습니다.'라는 메시지를 alert로 표시합니다
- [ ] 만약 입력한 이메일이 데이터베이스에 존재하고, 비밀번호도 일치할 경우, “/items”로 이동합니다.
### 회원가입
- [ ] 회원가입을 위해 이메일, 닉네임, 비밀번호, 비밀번호 확인을 입력한 뒤, 회원가입 버튼을 클릭하세요. 그 후에는 다음 조건에 따라 회원가입 가능 여부를 alert로 알려주세요.
- [ ] 입력한 이메일이 이미 데이터베이스(USER_DATA)에 존재하는 경우, '사용 중인 이메일입니다'라는 메시지를 alert로 표시합니다.
- [ ] 입력한 이메일이 데이터베이스(USER_DATA)에 없는 경우, 회원가입이 성공적으로 처리되었으므로 로그인 페이지(”/login”)로 이동합니다.
## 심화 요구사항
### 공통
- [ ] 페이스북, 카카오톡, 디스코드, 트위터 등 SNS에서 판다마켓 랜딩 페이지(“/”) 공유 시 미리보기를 볼 수 있도록 랜딩 페이지 메타 태그를 설정합니다.
- [ ] 미리보기에서 제목은 “판다마켓”, 설명은 “일상에서 모든 물건을 거래해보세요”로 설정합니다.
- [ ] 주소와 이미지는 자유롭게 설정하세요.
- [ ] 로그인, 회원가입 페이지에 공통으로 사용하는 로직이 있다면, 반복하지 않고 공통된 로직을 모듈로 분리해 사용해 주세요.
### 랜딩 페이지
- [ ] 브라우저에 현재 보이는 화면의 영역(viewport) 너비를 기준으로 분기되는 반응형 디자인을 적용합니다.
- PC: 1200px 이상
- Tablet: 744px 이상 ~ 1199px 이하
- Mobile: 375px 이상 ~ 743px 이하
- 375px 미만 사이즈의 디자인은 고려하지 않습니다
- [ ] Tablet 사이즈로 작아질 때 최소 좌우 여백이 “판다마켓” 로고의 왼쪽에 여백 24px, “로그인” 버튼 오른쪽 여백 24px을 유지할 수 있도록 “판다마켓” 로고와 “로그인" 버튼의 간격이 가까워집니다.
- [ ] Mobile 사이즈로 작아질 때 최소 좌우 여백이 “판다마켓” 로고의 왼쪽에 여백 16px, “로그인” 버튼 오른쪽 여백 16px을 유지할 수 있도록 “판다마켓” 로고와 “로그인" 버튼의 간격이 가까워집니다.
- [ ] PC, Tablet 사이즈의 이미지 크기는 고정값을 사용합니다.
- [ ] Mobile 사이즈의 이미지는 좌우 여백 32px을 제외하고 이미지 영역이 꽉 차게 구현합니다. (이때 가로가 커지는 비율에 맞춰 세로도 커져야 합니다.)
- [ ] Mobile 사이즈 너비가 커지면, “Privacy Policy”, “FAQ”, “codeit-2023”이 있는 영역과 SNS 아이콘들이 있는 영역의 사이 간격이 커집니다.
### 로그인, 회원가입 페이지 공통
- [ ] Tablet 사이즈에서 내부 디자인은 PC사이즈와 동일합니다.
- [ ] Mobile 사이즈에서 좌우 여백 16px 제외하고 내부 요소들이 너비를 모두 차지합니다.
- [ ] Mobile 사이즈에서 내부 요소들의 너비는 기기의 너비가 커지는 만큼 커지지만 400px을 넘지 않습니다.
- [ ] 오류 메시지 모달을 구현합니다. 모달 내 내용은 alert 메시지와 동일합니다.
- [ ] 비밀번호 및 비밀번호 확인 입력란에 눈 모양 아이콘 클릭 시 비밀번호 표시/숨기기 토글이 가능합니다. 기본 상태는 비밀번호 숨김으로 설정합니다.
## Netlify 주소
https://pandamarket-sprint.netlify.app/

2024-08-18 12:55 UTC, MCprotein requested changes

2024-08-18 12:55 UTC, MCprotein commented on login.js
> +}
@shinji530 지원님도 유림님과 동일한 방식으로 함수를 작성하셨네요!
유림님 PR에 남긴 코멘트를 보고 고쳐보시겠어요?
https://github.com/codeit-sprint-fullstack/2-Sprint-Mission-FE/pull/52#discussion_r1720943351

2024-08-18 12:55 UTC, MCprotein commented on login.js
> +        if (checkEmail.value.trim() === '') {
@shinji530 혹시 typescript 전역으로 설치하셨나요? 하셨다면 input 태그를 querySelector 로 가져왔을때의 값의 타입이 HTMLInputElement 인것을 확인하실 수 있는데요, 이때 value는 무조건 string타입이라서 아래처럼 truthy, falsy 개념을 이용해 줄여쓸 수 있어요!

```js
  if (!checkEmail.value.trim())
```
그런데 이거보다는 emailType 함수를 개선해서 그 안에서 처리하는게 더 좋을거같아요! 실제로 조건문 안에서 하는 행동이 동일하네요!

2024-08-18 13:23 UTC, MCprotein commented on login.js
> +        if (checkPW.value.trim() === '' || checkPW.value.length < 8) {
@shinji530 여기도 하나의 validation 함수에서 처리하면 좋을거같아요! 
```js
function isValidPassword(password) {

}
```

2024-08-20 02:04 UTC, shinji530 commented on login.js
> +}
코드 수정했습니다\\

2024-08-20 02:05 UTC, shinji530 commented on login.js
> +        if (checkPW.value.trim() === '' || checkPW.value.length < 8) {
해당 부분 수정했는데 이런 식으로 작성하면 될까요

2024-08-20 02:06 UTC, shinji530 commented on login.js
> +        if (checkEmail.value.trim() === '') {
넵 수정하겠습니다

2024-08-20 04:21 UTC, MCprotein commented on login.js
> +        if (checkPW.value.trim() === '' || checkPW.value.length < 8) {
@shinji530 넵 고생하셨습니다!

2024-08-20 04:26 UTC, MCprotein commented on login.js
> +const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
@shinji530 보통 이런거는 여러 방식으로 선언할 수 있는데, 아래 방식 중 하나로 개선하면 좋을거같아요! 
1. 하나의 파일 안에서 emailPattern를 사용하는 함수는 하나뿐이므로, 그 함수 내에서 선언
```js
function isEmailValid(email) {
    const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return emailPattern.test(email);
}
```
2. 여러 파일에서 공통으로 사용하는 공통코드이므로 `util.js` 와 같은 파일을 만들어 선언하고, commonJS/EcmaScript Module로 가져와 사용
```js
// util.js
const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
module.exports = { emailPattern }

// login.js
const { emailPattern } = require('./util')

function isEmailValid(email) {
    return emailPattern.test(email);
}
```

2024-08-20 04:29 UTC, MCprotein commented
@shinji530 자바스크립트 환경에서는 tabWidth를 보통 2칸으로 사용합니다! 제가 알려드린 prettier 설정대로 안하셔도 상관은없지만 탭2칸으로는 지정해주세요!

2024-08-20 04:36 UTC, MCprotein commented on login.js
> +}
@shinji530 요기는 checkEmail을 인자로 받지 않고 직접 작성한 이유가 있나요?
checkEmail은 HTML ELEMENT 객체라서 `ELEMENT 객체를 인자로 받아 그에 대한 특정 작업을 처리하는 함수`라는 역할을 명확히 한다면 더 좋을거같아요! 요렇게 함수를 작성하면 프로젝트 크기가 커졌을때 재사용할수가없어요! 

그리고 addEventListener를 이 함수 내에 작성하신 이유가 있을까요?
이벤트 리스너는 한 번 선언하면 그 이벤트를 계속 처리하도록 등록이되어있는거라서 바깥에다가 작성하는게 좀더 깔끔해보이네요! 게다가 이렇게 함수안에 있으면 함수가 실행될때마다 리스너가 완전히 변경되는거라 개발자가 예상하지 못한 행동을 할 수도 있을거같아요!

2024-08-20 04:37 UTC, MCprotein commented on login.js
> +}
@shinji530 여기도 https://github.com/codeit-sprint-fullstack/2-Sprint-Mission-FE/pull/53/files#r1722674422 와 마찬가지 의견 드려요!

2024-08-20 04:42 UTC, MCprotein commented on login.js
> +    }
@shinji530 여기는 아래처럼 코드를 간단하게 할 수 있어요!
코드 양이 많아질수록 scope의 depth가 깊으면 유지보수가 어려워져서 가급적이면 depth를 신경쓰는게 좋아요! 
```suggestion
    if (loginBtn.classList.contains('disabled')) return
    if (!isUser(email, password)) return showModal();
    window.location.href = 'items.html';
```

2024-08-20 04:44 UTC, MCprotein commented on signin.js
이 파일은 login.js에서 남긴 코멘트와 동일한 의견 드릴게요!

2024-08-20 04:50 UTC, MCprotein commented on signin.js
> +    const isEmailValid = emailType() && checkEmail.value.trim() !== '';
trim() 함수를 많이 쓰고 있는데, isEmptyString(value) 와 같은 validation 함수를 만들어서 사용하는것도 좋아보이네요! 
```js
function isEmptyString(value) {
  // isEmptyString 함수 사용하는곳에서 에러 핸들링 필요
  if (typeof value !== 'string') return throw new Error('value is not string')

// 아래 모두 동일하게 작동
  return value.trim() === '' ? true : false
  return value.trim() ? true : false
  return value.trim().length ? false : true
}
```

2024-08-20 04:52 UTC, MCprotein commented on signin.js
> +}
@shinji530 비밀번호확인 체크하는 함수는 비밀번호체크 함수와 생긴게 거의 유사한데, 코드를 재사용할 방법은 없을까요?

2024-08-20 08:00 UTC, shinji530 commented on login.js
> +}
수정했습니다

2024-08-20 08:01 UTC, shinji530 commented on login.js
> +    }
넵 참고하겠습니다!!

2024-08-20 13:57 UTC, MCprotein commented on main.css
> +    .section3 {
@shinji530 앗 이걸 이제봤네요!! 
section이 10개로 늘어난다면 section4와 section6, section 8의 차이를 이름만 보고 알 수 있을까요?
요렇게된것들 모두 구역별로 명확한 이름으로 변경하는게 좋을거같아요!

2024-08-21 02:26 UTC, shinji530 commented on main.css
> +    .section3 {
넵!

2024-08-21 02:29 UTC, shinji530 commented on login.js
> +const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
1로 변경했습니다!

2024-08-21 02:30 UTC, shinji530 commented on signin.js
> +}
생각해보겠습니다

2024-08-23 06:44 UTC, shinji530 commented on signin.js
> +}
최근 커밋에 반영해봤습니다. 불필요한 코드나 오류가 있을까요?

2024-08-23 06:46 UTC, shinji530 commented on signin.js
> +    const isEmailValid = emailType() && checkEmail.value.trim() !== '';
trim 함수 사용 부분이 필요 없는 거 같아서 모두 제거 했습니다. 다음에 활용할 수 있으면 해보겠습니다!

2024-08-26 04:22 UTC, MCprotein commented on signin.js
> +}
@shinji530 
```js
    if (!passwordRepeat) {
        console.log('passwordRepeat is empty', password.length);
        return password.length >= 8;
    }
```
이부분이 약간 의아하긴 하지만, 일단은 넘어가도 괜찮을거같아요! 고생하셨습니다!

2024-08-26 04:22 UTC, merged

2024-08-27 14:53 UTC, MCprotein commented on login/login.mjs
> +    if (modal) modal.style.display = 'none';
@shinji530 지원님! 요기서 에러가 발생해서 모달이 안닫히네요!!

2024-08-27 14:55 UTC, MCprotein commented on login/login.html
> +                <a class="login-btn" href="/items.html">
@shinji530 지원님! 로그인 버튼 누르면 `https://pandamarket-sprint.netlify.app/login/items.html` 여기로 들어가지네요! 확인한번 해주세요!