Basic 양가현
codeit-sprint-fullstack/2-Sprint-Mission-FE pull request #62
Opened 2024-08-19 10:01 UTC by gahyeon-yang

## 요구사항

### Sprint mission 3

로그인, 회원가입 페이지 공통

- [x] 로그인 및 회원가입 페이지의 이메일, 비밀번호, 비밀번호 확인 input에 필요한 유효성 검증 함수를 만들고 적용해 주세요.
- [x] 이메일 input에서 focus out 할 때, 값이 없을 경우 input에 빨강색 테두리와 아래에 “이메일을 입력해주세요.” 빨강색 에러 메세지를 보입니다.
- [x] 이메일 input에서 focus out 할 때, 이메일 형식에 맞지 않는 경우 input에 빨강색 테두리와 아래에 “잘못된 이메일 형식입니다” 빨강색 에러 메세지를 보입니다.
- [x] 비밀번호 input에서 focus out 할 때, 값이 없을 경우 아래에 “비밀번호를 입력해주세요.” 에러 메세지를 보입니다
- [x] 비밀번호 input에서 focus out 할 때, 값이 8자 미만일 경우 아래에 “비밀번호를 8자 이상 입력해주세요.” 에러 메세지를 보입니다.
- [x] input 에 빈 값이 있거나 에러 메세지가 있으면 ‘로그인’ 버튼은 비활성화 됩니다.
- [x] Input 에 유효한 값을 입력하면 ‘로그인' 버튼이 활성화 됩니다.
- [x] 활성화된 ‘로그인’ 버튼을 누르면 “/items” 로 이동합니다

#### 로그인 페이지

- [ ] 이메일과 비밀번호를 입력하고 로그인 버튼을 누른 후, 다음 조건을 참조하여 로그인 성공 여부를 alert 메시지로 출력합니다.
만약 입력한 이메일이 데이터베이스(USER_DATA)에 없거나, 이메일은 일치하지만 비밀번호가 틀린 경우, '비밀번호가 일치하지 않습니다.'라는 메시지를 alert로 표시합니다
만약 입력한 이메일이 데이터베이스에 존재하고, 비밀번호도 일치할 경우, “/items”로 이동합니다.
회원가입

- [ ] 회원가입을 위해 이메일, 닉네임, 비밀번호, 비밀번호 확인을 입력한 뒤, 회원가입 버튼을 클릭하세요. 그 후에는 다음 조건에 따라 회원가입 가능 여부를 alert로 알려주세요.
입력한 이메일이 이미 데이터베이스(USER_DATA)에 존재하는 경우, '사용 중인 이메일입니다'라는 메시지를 alert로 표시합니다.
입력한 이메일이 데이터베이스(USER_DATA)에 없는 경우, 회원가입이 성공적으로 처리되었으므로 로그인 페이지(”/login”)로 이동합니다.

### 심화 요구사항

- [ ] 페이스북, 카카오톡, 디스코드, 트위터 등 SNS에서 판다마켓 랜딩 페이지(“/”) 공유 시 미리보기를 볼 수 있도록 랜딩 페이지 메타 태그를 설정합니다.
- [ ] 미리보기에서 제목은 “판다마켓”, 설명은 “일상에서 모든 물건을 거래해보세요”로 설정합니다.
- [ ] 주소와 이미지는 자유롭게 설정하세요.
- [ ] 로그인, 회원가입 페이지에 공통으로 사용하는 로직이 있다면, 반복하지 않고 공통된 로직을 모듈로 분리해 사용해 주세요.

#### 랜딩 페이지

- [x] 브라우저에 현재 보이는 화면의 영역(viewport) 너비를 기준으로 분기되는 반응형 디자인을 적용합니다.
PC: 1200px 이상
Tablet: 744px 이상 ~ 1199px 이하
Mobile: 375px 이상 ~ 743px 이하
375px 미만 사이즈의 디자인은 고려하지 않습니다
- [x] Tablet 사이즈로 작아질 때 최소 좌우 여백이 “판다마켓” 로고의 왼쪽에 여백 24px, “로그인” 버튼 오른쪽 여백 24px을 유지할 수 있도록 “판다마켓” 로고와 “로그인" 버튼의 간격이 가까워집니다.
- [x] Mobile 사이즈로 작아질 때 최소 좌우 여백이 “판다마켓” 로고의 왼쪽에 여백 16px, “로그인” 버튼 오른쪽 여백 16px을 유지할 수 있도록 “판다마켓” 로고와 “로그인" 버튼의 간격이 가까워집니다.
- [x] PC, Tablet 사이즈의 이미지 크기는 고정값을 사용합니다.
- [x] Mobile 사이즈의 이미지는 좌우 여백 32px을 제외하고 이미지 영역이 꽉 차게 구현합니다. (이때 가로가 커지는 비율에 맞춰 세로도 커져야 합니다.)
- [ ] Mobile 사이즈 너비가 커지면, “Privacy Policy”, “FAQ”, “codeit-2023”이 있는 영역과 SNS 아이콘들이 있는 영역의 사이 간격이 커집니다.

#### 로그인, 회원가입 페이지 공통

- [x] Tablet 사이즈에서 내부 디자인은 PC사이즈와 동일합니다.
- [x] Mobile 사이즈에서 좌우 여백 16px 제외하고 내부 요소들이 너비를 모두 차지합니다.
- [x] Mobile 사이즈에서 내부 요소들의 너비는 기기의 너비가 커지는 만큼 커지지만 400px을 넘지 않습니다.
- [ ] 오류 메시지 모달을 구현합니다. 모달 내 내용은 alert 메시지와 동일합니다.
- [ ] 비밀번호 및 비밀번호 확인 입력란에 눈 모양 아이콘 클릭 시 비밀번호 표시/숨기기 토글이 가능합니다. 기본 상태는 비밀번호 숨김으로 설정합니다.

## 주요 변경사항
### signup, login
  - login.js와 signup.js 파일이 추가되었습니다.
  - login signup html에 <span>이 추가되었습니다.
  - sign.css 마지막 부분에 error 부분이 추가되었습니다.

### 랜딩 페이지
  - features 부분인 css를 update 하였습니다.

## 스크린샷

#### 로그인 페이지
로그인 포커스 아웃됐을 때
![image](https://github.com/user-attachments/assets/17c96bd3-3808-4127-92f4-ab5b2aee5e07)

#### 로그인 버튼 활성화
![image](https://github.com/user-attachments/assets/d7a7e40d-3877-40bf-a077-a7ca36cc43cd)

#### 회원가입 페이지
회원가입 입력이 다 잘못됐을 때
![image](https://github.com/user-attachments/assets/9e11ca00-fc4f-47ed-9c8b-fd6f720dd09e)

#### 회원가입 버튼 활성화
![image](https://github.com/user-attachments/assets/f3f20177-a31a-449a-8c29-f3c29fb75654)

## 멘토에게

- 데이터베이스와 심화 부분은 아직 안했습니다!
- 회원가입과 로그인 html에서 js파일이 다르지만, span에서 id 이름이 같아도 되는건가요? i.e) errorEmail / errorPassword
- 랜딩 페이지에서 일상의 모든 물건을 거래 해보세요. 부분 띄어쓰기를 어떻게 하면 좋을까요? 일단 span으로 해결했습니다!

2024-08-19 10:22 UTC, junguksim requested changes
아직은 명명과 관련된 리뷰만 드립니다! 전체적으로 코드를 잘 짜신 것 같습니다.
이벤트도 잘 활용하셨구요! 

다음주도 기대하겠습니다! 화이팅입니다.

2024-08-19 10:22 UTC, junguksim commented on index.html
> +                <h1>일상의 모든 물건을 <span class="space"></span>거래 해보세요</h1>
질문이 잘 이해가 안되는데, 어떤점이 문제였나요?
이렇게 줄바꿈을 원하신 걸까요?
![image](https://github.com/user-attachments/assets/2df5e3de-e72f-4bc0-ac0d-b405e98d2bcc)

2024-08-19 10:22 UTC, junguksim commented on js/login.js
> +    const errorEmail = document.getElementById("errorEmail");
> 회원가입과 로그인 html에서 js파일이 다르지만, span에서 id 이름이 같아도 되는건가요? i.e) errorEmail / errorPassword

다른 JS 파일은 다른 걸로 취급돼서 상관없습니다!

2024-08-19 10:22 UTC, junguksim commented on js/login.js
> +    function validationEmail(){
함수는 동사형이 좋습니다!
validateEmail 이 좋을 것 같네요.

그와 별개로 단어 선택은 굉장히 좋습니다 :)

2024-08-19 10:22 UTC, junguksim commented on js/signup.js
> +    function ValidCheckInput(){
맨 앞글자가 대문자네요! 컨벤션을 지켜주세요

2024-08-20 04:28 UTC, gahyeon-yang commented on index.html
> +                <h1>일상의 모든 물건을 <span class="space"></span>거래 해보세요</h1>
pc버전
![image](https://github.com/user-attachments/assets/ae52ff47-b7bd-4af2-9841-8af846e78b28)
tablet 버전
![image](https://github.com/user-attachments/assets/9e962425-836a-4cc6-b40b-058fa57ceeee)
피그마를 보면 창크기에 따라 줄바꿈이 달라지는 데
![image](https://github.com/user-attachments/assets/d1e352c4-4dbf-4c53-9a71-d83aa012a3c7)
![image](https://github.com/user-attachments/assets/2c6272c8-04f6-4858-a9fb-83da54362113)

이렇게 해결했는데, 더 좋은 방법이 있을까요?

2024-08-27 00:13 UTC, gahyeon-yang commented on js/login.js
> +import { USER_DATA, validateEmail, validatePassword, togglePasswordVisibility} from 'js/sign.js';
./sign.js로 수정해야 합니다ㅠ

2024-08-27 15:48 UTC, junguksim approved these changes
너무 잘 완성하셨네요!
주석도 참 깔끔하게 잘 달아주셨고 로직구현, 모듈화도 좋습니다.
크게 터치할 부분이 없네요 👍

2024-08-27 15:48 UTC, junguksim commented on index.html
> +                <h1>일상의 모든 물건을 <span class="space"></span>거래 해보세요</h1>
<br> 을 넣으면 될 거 같은데 안넣으신 이유가 있나요?

2024-08-27 15:48 UTC, junguksim commented on js/login.js
> +    function validCheckInput(){
valid 보다는 validate 동사형이 좋겠네요!

2024-08-27 15:51 UTC, merged