Basic 이강수 sprint3
codeit-sprint-fullstack/2-Sprint-Mission-FE pull request #63
Opened 2024-08-19 22:46 UTC by kipid

# 스프린트 미션 3 시안 확인

아래 링크를 통해 강의 학습 후 만들어봐야 할 실습 과제 디자인을 확인해보세요

- [스프린트 미션 3 Figma 디자인 확인하러 바로가기](https://www.figma.com/design/EWfmnBJU3fdkeHKyYBQW6L/%5B%EC%88%98%EA%B0%95%EC%83%9D-%EA%B3%B5%EC%9C%A0%EC%9A%A9%5D-%ED%8C%90%EB%8B%A4%EB%A7%88%EC%BC%93?node-id=11-2033&t=c8vm35JLSW0PXCOP-0)

## 요구사항

### 기본 요구사항

#### 공통

- [x] Github에 스프린트 미션 PR을 만들어 주세요.

#### 로그인, 회원가입 페이지 공통

- [x] 로그인 및 회원가입 페이지의 이메일, 비밀번호, 비밀번호 확인 input에 필요한 유효성 검증 함수를 만들고 적용해 주세요.
- [x] 이메일 input에서 focus out 할 때, 값이 없을 경우 input에 빨강색 테두리와 아래에 “이메일을 입력해주세요.” 빨강색 에러 메세지를 보입니다.
// focusout 아니고 input 으로 구현했습니다. button disable/enable 이 쉽지 않아져서요.
- [x] 이메일 input에서 focus out 할 때, 이메일 형식에 맞지 않는 경우 input에 빨강색 테두리와 아래에 “잘못된 이메일 형식입니다” 빨강색 에러 메세지를 보입니다.
- [x] 비밀번호 input에서 focus out 할 때, 값이 없을 경우 아래에 “비밀번호를 입력해주세요.” 에러 메세지를 보입니다
- [x] 비밀번호 input에서 focus out 할 때, 값이 8자 미만일 경우 아래에 “비밀번호를 8자 이상 입력해주세요.” 에러 메세지를 보입니다.
- [x] input 에 빈 값이 있거나 에러 메세지가 있으면 ‘로그인’ 버튼은 비활성화 됩니다.
- [x] Input 에 유효한 값을 입력하면 ‘로그인' 버튼이 활성화 됩니다.
- [x] 활성화된 ‘로그인’ 버튼을 누르면 “/items” 로 이동합니다

```
const USER_DATA = [
    { email: 'codeit1@codeit.com', password: "codeit101!" },
    { email: 'codeit2@codeit.com', password: "codeit202!" },
    { email: 'codeit3@codeit.com', password: "codeit303!" },
    { email: 'codeit4@codeit.com', password: "codeit404!" },
    { email: 'codeit5@codeit.com', password: "codeit505!" },
    { email: 'codeit6@codeit.com', password: "codeit606!" },
];
```

#### 로그인 페이지

- [x] 이메일과 비밀번호를 입력하고 로그인 버튼을 누른 후, 다음 조건을 참조하여 로그인 성공 여부를 alert 메시지로 출력합니다.
만약 입력한 이메일이 데이터베이스(USER_DATA)에 없거나, 이메일은 일치하지만 비밀번호가 틀린 경우, '비밀번호가 일치하지 않습니다.'라는 메시지를 alert로 표시합니다
만약 입력한 이메일이 데이터베이스에 존재하고, 비밀번호도 일치할 경우, “/items”로 이동합니다.
회원가입

- [x] 회원가입을 위해 이메일, 닉네임, 비밀번호, 비밀번호 확인을 입력한 뒤, 회원가입 버튼을 클릭하세요. 그 후에는 다음 조건에 따라 회원가입 가능 여부를 alert로 알려주세요.
입력한 이메일이 이미 데이터베이스(USER_DATA)에 존재하는 경우, '사용 중인 이메일입니다'라는 메시지를 alert로 표시합니다.
입력한 이메일이 데이터베이스(USER_DATA)에 없는 경우, 회원가입이 성공적으로 처리되었으므로 로그인 페이지(”/login”)로 이동합니다.

### 심화 요구사항

#### 공통

- [x] 페이스북, 카카오톡, 디스코드, 트위터 등 SNS에서 판다마켓 랜딩 페이지(“/”) 공유 시 미리보기를 볼 수 있도록 랜딩 페이지 메타 태그를 설정합니다.
- [x] 미리보기에서 제목은 “판다마켓”, 설명은 “일상에서 모든 물건을 거래해보세요”로 설정합니다.
- [x] 주소와 이미지는 자유롭게 설정하세요.
- [x] 로그인, 회원가입 페이지에 공통으로 사용하는 로직이 있다면, 반복하지 않고 공통된 로직을 모듈로 분리해 사용해 주세요.
랜딩 페이지

- [x] 브라우저에 현재 보이는 화면의 영역(viewport) 너비를 기준으로 분기되는 반응형 디자인을 적용합니다.
PC: 1200px 이상
Tablet: 744px 이상 ~ 1199px 이하
Mobile: 375px 이상 ~ 743px 이하
375px 미만 사이즈의 디자인은 고려하지 않습니다
- [x] Tablet 사이즈로 작아질 때 최소 좌우 여백이 “판다마켓” 로고의 왼쪽에 여백 24px, “로그인” 버튼 오른쪽 여백 24px을 유지할 수 있도록 “판다마켓” 로고와 “로그인" 버튼의 간격이 가까워집니다.
- [x] Mobile 사이즈로 작아질 때 최소 좌우 여백이 “판다마켓” 로고의 왼쪽에 여백 16px, “로그인” 버튼 오른쪽 여백 16px을 유지할 수 있도록 “판다마켓” 로고와 “로그인" 버튼의 간격이 가까워집니다.
- [x] PC, Tablet 사이즈의 이미지 크기는 고정값을 사용합니다.
- [x] Mobile 사이즈의 이미지는 좌우 여백 32px을 제외하고 이미지 영역이 꽉 차게 구현합니다. (이때 가로가 커지는 비율에 맞춰 세로도 커져야 합니다.)
- [x] Mobile 사이즈 너비가 커지면, “Privacy Policy”, “FAQ”, “codeit-2023”이 있는 영역과 SNS 아이콘들이 있는 영역의 사이 간격이 커집니다.
로그인, 회원가입 페이지 공통

- [x] Tablet 사이즈에서 내부 디자인은 PC사이즈와 동일합니다.
- [x] Mobile 사이즈에서 좌우 여백 16px 제외하고 내부 요소들이 너비를 모두 차지합니다.
- [x] Mobile 사이즈에서 내부 요소들의 너비는 기기의 너비가 커지는 만큼 커지지만 400px을 넘지 않습니다.
- [x] 오류 메시지 모달을 구현합니다. 모달 내 내용은 alert 메시지와 동일합니다.
- [ ] 비밀번호 및 비밀번호 확인 입력란에 눈 모양 아이콘 클릭 시 비밀번호 표시/숨기기 토글이 가능합니다. 기본 상태는 비밀번호 숨김으로 설정합니다.

2024-08-20 14:28 UTC, json9512 requested changes

2024-08-20 14:28 UTC, json9512 commented on panda-market/login/script.js
> +let allCfmed=[false, false];
```js
let allCfmed = [false, false];
```

의 뜻이 전달되기는 하지만, 협업을 고려한다면 좀 더 명확한 변수명과 자료구조를 고려해보세요.

현재는 코드를 읽는 사람이 **`allCfmed`의 뜻을 유추해야 하고, 할당된 배열에서 index가 어떤 것을 의미하는지 코드를 전체 다 보기 전까지 파악하기 힘든 구조**입니다.

예시를 들자면,
```js
// 이렇게 선언할 수 있고
const validationState = {
  email: false,
  password: false,
};

// 이렇게 변경 가능합니다
validationState.email = true
```

2024-08-20 14:28 UTC, json9512 commented on panda-market/login/script.js
> +email.addEventListener("input", function (e) {
어떤 부분에서 focusout으로 구현하기 힘드셨나요?

2024-08-20 14:28 UTC, json9512 commented on panda-market/login/script.js
> +		popupText.innerHTML = `로그인 되었습니다.`;
성공한 케이스는 따로 popup으로 안띄워줘도 될 것 같습니다

2024-08-20 14:28 UTC, json9512 commented on panda-market/login/script.js
> +		popupText.innerHTML = `이메일 ${email.value} 은 가입되어 있지 않습니다.`;
현재 파일 구조상 이 script 내부에서는 popupText가 선언되지 않았습니다.
즉, popupText를 다른 스크립트에서 선언을 하셨다는 이야기가 되는데 만약 모종의 이유로 해당 스크립트를 불러오지 못하면 이 스크립트에 있는 popupText는 어떻게 될까요?

2024-08-20 14:28 UTC, json9512 commented on panda-market/signup/script.js
> +    pwdCfmError.innerHTML="비밀번호가 다릅니다. 다시 확인해주세요.";
피그마 기준으로 에러 문구 맞춰주세요!

2024-08-20 14:28 UTC, json9512 commented on panda-market/reset.css
> +@media (max-width:744px) {
모바일 화면에서 스타일이 맞지 않습니다!

iphone12 pro: 390x844

![image](https://github.com/user-attachments/assets/758f9bbb-cff5-455c-a007-541fb52a56fd)

2024-08-20 14:28 UTC, json9512 commented on panda-market/login/script.js
> +	if (!email.value) {
if문으로 여러 조건을 나누셨는데 좀 더 간소화 시킬 수 있는 방법은 없을까요? 🤔

2024-08-20 14:28 UTC, json9512 commented on panda-market/signup/script.js
> +const nickname = document.querySelector(`input#nickname`);
이 파일도 전반적으로 /login 쪽 script.js와 동일한 내용이라 수정 사항은 같습니다!

2024-08-20 14:28 UTC, json9512 commented on panda-market/signup/script.js
> +const visPwdCfm = pwdCfm.nextElementSibling;
nextElementSibiling 같은 경우 UI가 변경되면 로직이 깨질 수 있어서 사용 시 주의해야 합니다. 웬만하면 selector로 요소를 가져오는게 가장 예측 가능한 방법이긴 해요

2024-08-22 07:30 UTC, kipid commented on panda-market/login.css
> +  background-color: rgb(59, 92, 59);
gray 색이 비활성 버튼처럼 보여서 활성 버튼을 따로 green 쪽으로 설정했었는데, Figma 에 있었군요.
고치겠습니다.

2024-08-22 07:31 UTC, kipid commented on panda-market/login.css
> +  color: rgb(139, 47, 47);
넵.

2024-08-22 07:32 UTC, kipid commented on panda-market/login/script.js
> +let allCfmed=[false, false];
명시적으로 바꾸겠습니다.

2024-08-22 07:34 UTC, kipid commented on panda-market/login/script.js
> +email.addEventListener("input", function (e) {
하나의 validity check 가 끝나서 반영되면 button 이 활성화 될때도 있어서 input 으로 바꾼거긴 한데...
allValidityConfirmed 로 check 하면 될거 같으니 다시 focusout 으로 바꾸겠습니다.

특히 input 으로 하면 입력 중에도 에러가 있는지 바로 판단해서 사용자에게 보여줄 수 있단 점이 매력적으로 느껴져서 input 에 handler 를 넣었었습니다.

2024-08-22 07:35 UTC, kipid commented on panda-market/login/script.js
> +		popupText.innerHTML = `로그인 되었습니다.`;
넵.

2024-08-22 07:35 UTC, kipid commented on panda-market/signup/script.js
> +    pwdCfmError.innerHTML="비밀번호가 다릅니다. 다시 확인해주세요.";
넵.

2024-08-22 07:36 UTC, kipid commented on panda-market/reset.css
> +@media (max-width:744px) {
이건 어떻게 바꿔야 할지 당장 생각이 안나네요. 고민 좀 해보고 고치겠습니다.

2024-08-22 08:39 UTC, kipid commented on panda-market/login/script.js
> +email.addEventListener("input", function (e) {
제 느낌으론 input 으로 validity check 해주는게 비밀번호 자동완성이나 dropdown 으로 입력했을때도 대응이 되어서 focusout 보다 좋아보이긴 합니다.

2024-08-22 08:39 UTC, kipid commented on panda-market/login/script.js
> +email.addEventListener("input", function (e) {
Computing resource 를 많이 잡아먹는다는 느낌도 별로 없어서...

2024-08-23 22:11 UTC, kipid commented
수정 사항 반영했습니다.

2024-08-26 01:05 UTC, kipid commented
home /index.html CSS 수정 했습니다. grid 로 하니까 편히 되네요.
그리고 background 도 center 로 정렬되도록 @media query 해놨습니다.

2024-08-26 02:06 UTC, kipid commented
Netlify 올려놓았고, log img 바뀌는건 그냥 javascript 로 처리 했습니다. CSS 로도 될거 같긴한데, 귀차니즘에 =ㅇ=;;;

2024-08-26 02:11 UTC, kipid commented
sprint4 branch 에서 작업하고 있었네요;;; ㅎㄷㄷ. merge 해놨습니다.

2024-08-26 09:41 UTC, kipid commented
첫 화면에서 trigger 를 빼먹었었네요. 그리고 폰으로 볼땐 자유게시판, 중고마켓 글씨 크기가 매우 작게 나오던데...
PC Browser 에서 가로크기 줄일때랑 좀 다르네요. 뭐에 맞춰야 할지.. =ㅇ=;;

2024-08-27 14:43 UTC, json9512 commented on panda-market/login/script.js
> +email.addEventListener("input", function (e) {
현재는 부트캠프의 요구사항이 figma로 고정되어 변경의 여지가 없지만, 현업에서는 이런 부분은 프로덕트 디자이너, PM과 함께 적극적으로 논의해서 충분히 변경할 수 있는 부분입니다

2024-08-27 14:45 UTC, json9512 commented on panda-market/login/script.js
> +email.addEventListener("input", function (e) {
중요한건 지금 강수님이 하신 것처럼, 사용하는 유저 입장에서 더 나은 점을 계속 고민하는 것입니다! 😃

2024-08-27 16:00 UTC, json9512 approved these changes

2024-08-27 16:00 UTC, json9512 commented on panda-market/style.css
> +  font-size: var(--text-2xl);
피그마 기준 값으로 font-size 맞춰주세요!

2024-08-27 16:00 UTC, json9512 commented on panda-market/reset.css
> +@media (max-width:744px) {
반응형 웹 디자인을 할 때 보통 가장 작은 화면을 기준으로 작업을 하고 media 쿼리로 min-width 설정하면서 좀 더 큰 화면 디자인을 합니다.
(이상적인 디자인 순서:  작은 화면 -> 큰 화면 순)

현재 강수님은 반대로 작업이 되어있어서 모바일 화면으로 디자인을 맞추기 어려운 것 같아요 🤔 
(강수님 디자인 순서: 큰 화면 -> 작은 화면 순)

2024-08-27 16:00 UTC, merged

2024-08-27 21:10 UTC, kipid commented on panda-market/common-login.js
> +const emailRegEx = /^[a-zA-Zㄱ-ㅎㅏ-ㅣ가-힣0-9\-\_\.]+@[a-zA-Zㄱ-ㅎㅏ-ㅣ가-힣0-9\-\_\.]+\.[\w]{2,3}$/;
아주 가끔 한글 이메일 쓰시는 분들이 있어서...
지우겠습니다.

2024-08-27 21:11 UTC, kipid commented on sprint4-fetch-axios/README.md
네 이거 제가 실수로 =ㅂ=;; revert 를 하고 뭔가 병합을 해줬었어야 할거 같은데...
아직 git 에 익숙치가 않고 (살짝 귀차니즘도 생겨서 ㅠㅜㅋ) 죄송합니다. 담부턴 branch 관리 잘 하겠습니다.

2024-08-27 21:18 UTC, kipid commented on panda-market/style.css
> +  font-size: var(--text-2xl);
font-size 맞춘줄 알았는데, 실수했네요. 꼼꼼한 리뷰 감사합니다.

2024-08-27 21:19 UTC, kipid commented
친절한 리뷰 감사합니다. 꾸벅 ( _ _ )