[김태연] Sprint3
codeit-sprint-fullstack/2-Sprint-Mission-FE pull request #69
Opened 2024-08-25 07:05 UTC by taeyeonkim94

![PC](https://github.com/user-attachments/assets/df77e814-b05d-4d04-ae7b-2c530cec1946)
## 요구사항

### 기본
공통

- [x] Github에 스프린트 미션 PR을 만들어 주세요.
로그인, 회원가입 페이지 공통
- [x] 로그인 및 회원가입 페이지의 이메일, 비밀번호, 비밀번호 확인 input에 필요한 유효성 검증 함수를 만들고 적용해 주세요.
- [x] 이메일 input에서 focus out 할 때, 값이 없을 경우 input에 빨강색 테두리와 아래에 “이메일을 입력해주세요.” 빨강색 에러 메세지를 보입니다.
- [x] 이메일 input에서 focus out 할 때, 이메일 형식에 맞지 않는 경우 input에 빨강색 테두리와 아래에 “잘못된 이메일 형식입니다” 빨강색 에러 메세지를 보입니다.
- [x] 비밀번호 input에서 focus out 할 때, 값이 없을 경우 아래에 “비밀번호를 입력해주세요.” 에러 메세지를 보입니다
- [x] 비밀번호 input에서 focus out 할 때, 값이 8자 미만일 경우 아래에 “비밀번호를 8자 이상 입력해주세요.” 에러 메세지를 보입니다.
- [x] input 에 빈 값이 있거나 에러 메세지가 있으면 ‘로그인’ 버튼은 비활성화 됩니다.
- [x] Input 에 유효한 값을 입력하면 ‘로그인' 버튼이 활성화 됩니다.
- [x] 활성화된 ‘로그인’ 버튼을 누르면 “/items” 로 이동합니다

로그인 페이지
- [x] 이메일과 비밀번호를 입력하고 로그인 버튼을 누른 후, 다음 조건을 참조하여 로그인 성공 여부를 alert 메시지로 출력합니다.
1. 만약 입력한 이메일이 데이터베이스(USER_DATA)에 없거나, 이메일은 일치하지만 비밀번호가 틀린 경우, '비밀번호가 일치하지 않습니다.'라는 메시지를 alert로 표시합니다
2. 만약 입력한 이메일이 데이터베이스에 존재하고, 비밀번호도 일치할 경우, “/items”로 이동합니다.

- [x] 회원가입을 위해 이메일, 닉네임, 비밀번호, 비밀번호 확인을 입력한 뒤, 회원가입 버튼을 클릭하세요. 그 후에는 다음 조건에 따라 회원가입 가능 여부를 alert로 알려주세요.
1. 입력한 이메일이 이미 데이터베이스(USER_DATA)에 존재하는 경우, '사용 중인 이메일입니다'라는 메시지를 alert로 표시합니다.
2. 입력한 이메일이 데이터베이스(USER_DATA)에 없는 경우, 회원가입이 성공적으로 처리되었으므로 로그인 페이지(”/login”)로 이동합니다.

회원가입
- [x] 회원가입을 위해 이메일, 닉네임, 비밀번호, 비밀번호 확인을 입력한 뒤, 회원가입 버튼을 클릭하세요. 그 후에는 다음 조건에 따라 회원가입 가능 여부를 alert로 알려주세요.
1. 입력한 이메일이 이미 데이터베이스(USER_DATA)에 존재하는 경우, '사용 중인 이메일입니다'라는 메시지를 alert로 표시합니다.
2. 입력한 이메일이 데이터베이스(USER_DATA)에 없는 경우, 회원가입이 성공적으로 처리되었으므로 로그인 페이지(”/login”)로 이동합니다.

### 심화
공통
- [x] 페이스북, 카카오톡, 디스코드, 트위터 등 SNS에서 판다마켓 랜딩 페이지(“/”) 공유 시 미리보기를 볼 수 있도록 랜딩 페이지 메타 태그를 설정합니다.
- [x] 미리보기에서 제목은 “판다마켓”, 설명은 “일상에서 모든 물건을 거래해보세요”로 설정합니다.
- [x] 주소와 이미지는 자유롭게 설정하세요.
- [x] 로그인, 회원가입 페이지에 공통으로 사용하는 로직이 있다면, 반복하지 않고 공통된 로직을 모듈로 분리해 사용해 주세요.

랜딩페이지
 - [x] 브라우저에 현재 보이는 화면의 영역(viewport) 너비를 기준으로 분기되는 반응형 디자인을 적용합니다.
PC: 1200px 이상
Tablet: 744px 이상 ~ 1199px 이하
Mobile: 375px 이상 ~ 743px 이하
375px 미만 사이즈의 디자인은 고려하지 않습니다
- [x] Tablet 사이즈로 작아질 때 최소 좌우 여백이 “판다마켓” 로고의 왼쪽에 여백 24px, “로그인” 버튼 오른쪽 여백 24px을 유지할 수 있도록 “판다마켓” 로고와 “로그인" 버튼의 간격이 가까워집니다.
- [x] Mobile 사이즈로 작아질 때 최소 좌우 여백이 “판다마켓” 로고의 왼쪽에 여백 16px, “로그인” 버튼 오른쪽 여백 16px을 유지할 수 있도록 “판다마켓” 로고와 “로그인" 버튼의 간격이 가까워집니다.
- [x] PC, Tablet 사이즈의 이미지 크기는 고정값을 사용합니다.
- [x] Mobile 사이즈의 이미지는 좌우 여백 32px을 제외하고 이미지 영역이 꽉 차게 구현합니다. (이때 가로가 커지는 비율에 맞춰 세로도 커져야 합니다.)
- [x] Mobile 사이즈 너비가 커지면, “Privacy Policy”, “FAQ”, “codeit-2023”이 있는 영역과 SNS 아이콘들이 있는 영역의 사이 간격이 커집니다.

로그인, 회원가입 페이지 공통
- [x] Tablet 사이즈에서 내부 디자인은 PC사이즈와 동일합니다.
- [x] Mobile 사이즈에서 좌우 여백 16px 제외하고 내부 요소들이 너비를 모두 차지합니다.
- [x] Mobile 사이즈에서 내부 요소들의 너비는 기기의 너비가 커지는 만큼 커지지만 400px을 넘지 않습니다.
- [x] 오류 메시지 모달을 구현합니다. 모달 내 내용은 alert 메시지와 동일합니다.
- [x] 비밀번호 및 비밀번호 확인 입력란에 눈 모양 아이콘 클릭 시 비밀번호 표시/숨기기 토글이 가능합니다. 기본 상태는 비밀번호 숨김으로 설정합니다.

## 주요 변경사항

- 심화 요구 사항까지 완료
- netlify : https://66c1d9e94e54896c848ced0e--panda-markget94.netlify.app/
## 스크린샷

![image]

![미리보기](https://github.com/user-attachments/assets/0b55b7e2-0980-4680-bbeb-3b00c526cca9)
![PC](https://github.com/user-attachments/assets/13258a7c-e188-4f5d-9118-30107e1ab052)
![Tablet](https://github.com/user-attachments/assets/6d93d193-292e-47a6-b8e0-085e1212ac13)
![PC](https://github.com/user-attachments/assets/9aa03dd7-31e9-47ae-a8c1-f67be344a4cf)
![모바일모달](https://github.com/user-attachments/assets/2c9e737e-861a-49ad-aac1-1c736d8443dc)
![PC](https://github.com/user-attachments/assets/5bbc108d-8d41-4723-80e9-95372ceae805)
![모바일모달](https://github.com/user-attachments/assets/52205b10-febe-4ac0-8205-15d3ea9bd5f9)
![Mobile](https://github.com/user-attachments/assets/4e0154ac-930f-45c2-a7a7-eb864c60ec96)

멘토에게

-  Mobile 사이즈에서 내부 요소들의 너비는 기기의 너비가 커지는 만큼 커지지만 400px을 넘지 않습니다.
이부분이 생각보다 손이 너무 많이 갔는데 효율적인 방법이 있을까요?
- 미션이 진행될수록 코드들이 필요이상으로 복잡해지고 있는데 새로 한번 정리하는게 맞을까요?
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2024-08-27 09:53 UTC, junguksim requested changes
모듈화 + 객체화를 통해 코드 중복을 많이 줄이려고 하신 거 같아요.
코드는 정말 잘 짜셨습니다만, 변수명/함수명 작명들이 아쉬워서 가독성이 떨어집니다.
이것만 주의하시면 정말 잘하실 거 같습니다~

> Mobile 사이즈에서 내부 요소들의 너비는 기기의 너비가 커지는 만큼 커지지만 400px을 넘지 않습니다.

이거는 max-width 쓰라는 말 같은데 아닌가요??

2024-08-27 09:53 UTC, junguksim commented on login.js
> +const inputId = document.querySelector('#username');
`#username` 이라는 id 로 가져온 element 이기 때문에
inputId 보다는 usernameElem 같은 변수가 좋을 것 같습니다!

2024-08-27 09:53 UTC, junguksim commented on login.js
> +const userData = [
이 userData 도 모듈화 할 수 있어보이네요!

2024-08-27 09:53 UTC, junguksim commented on validation.js
> +function id(input, guide) {
id 보다는 email 인풋이므로 email 이 좋아보이네요!

2024-08-27 09:53 UTC, junguksim commented on signup.js
> +const inputData={
inputData 는 너무 모호한 이름 같습니다. elementsData 가 어떨까요?

2024-08-27 09:53 UTC, junguksim commented on validation.js
> +function pw(input, guide) {
validate.pw() 처럼 쓸 수 있지만, 이는 validate 객체의 메소드이므로 함수명도 동사형으로 변경해주세요.

readyBtn 처럼요!

2024-08-27 09:53 UTC, junguksim commented on validation.js
> +function id(input, guide) {
parameter 이름도 너무 애매모호한 거 같아요.
input 과 guide 가 HTML element 인지 이 코드만 봐서는 바로 와닿지가 않는 거 같습니다.

2024-08-28 15:34 UTC, taeyeonkim94 commented on validation.js
> +function pw(input, guide) {
이름 짓기가 제일 어렵네요 ㅠㅠ 말씀하신 부분 수정해보겠습니다.
Mobile 사이즈에서 내부 요소들의 너비는 기기의 너비가 커지는 만큼 커지지만 400px을 넘지 않습니다.
이부분은 max-width를 쓰고 자식요소들을 모두 너비를 100%로 채워주고 overflow 같은 설정을 해줬는데 특별히 다른 방법이 없을까 생각이 들어서 여쭤봤습니다

2024-09-03 08:04 UTC, merged