[신지원] Sprint4
codeit-sprint-fullstack/2-Sprint-Mission-FE pull request #78
Opened 2024-08-27 07:14 UTC by shinji530

## 스프린트 미션 4 요구사항 확인
스프린트 미션 4의 요구사항은 두 가지 주요 API(Article API와 Product API)를 사용하여 다양한 CRUD(생성, 읽기, 업데이트, 삭제) 기능을 구현하는 것입니다.

- [API 명세 확인하러 가기](https://sprint-mission-api.vercel.app/docs/)

위 명세를 참고해 아래 요구사항에 따라 함수들을 구현하세요.

## 요구사항
### 기본 요구사항
#### 공통

- [ ]  Github에 스프린트 미션 PR을 만들어 주세요.

- [ ]  'https://sprint-mission-api.vercel.app/articles' API를 이용하여 아래 함수들을 구현해 주세요.

- [ ] getArticleList() : GET 메서드를 사용해 주세요.
- [ ] page, pageSize, keyword 쿼리 파라미터를 이용해 주세요.
- [ ] getArticle() : GET 메서드를 사용해 주세요.
- [ ] createArticle() : POST 메서드를 사용해 주세요.
- [ ] request body에 title, content, image 를 포함해 주세요.
- [ ] patchArticle() : PATCH 메서드를 사용해 주세요.
- [ ] deleteArticle() : DELETE 메서드를 사용해 주세요.
- [ ]  fetch 혹은 axios 를 이용해 주세요.

- [ ] 응답의 상태 코드가 2XX가 아닐 경우, 에러메시지를 콘솔에 출력해 주세요.
- [ ]  .then() 메서드를 이용하여 비동기 처리를 해주세요.

- [ ]  .catch() 를 이용하여 오류 처리를 해주세요.

- [ ]  'https://sprint-mission-api.vercel.app/products' API를 이용하여 아래 함수들을 구현해 주세요.

- [ ] getProductList() : GET 메서드를 사용해 주세요.
- [ ] page, pageSize, keyword 쿼리 파라미터를 이용해 주세요.
- [ ] getProduct() : GET 메서드를 사용해 주세요.
- [ ] createProduct() : POST 메서드를 사용해 주세요.
- [ ] request body에 name, description, price, tags, images 를 포함-해 주세요.
- [ ] patchProduct() : PATCH 메서드를 사용해 주세요.
- [ ] deleteProduct() : DELETE 메서드를 사용해 주세요.
- [ ]  async/await 을 이용하여 비동기 처리를 해주세요.

- [ ]  try/catch 를 이용하여 오류 처리를 해주세요.

- [ ]  구현한 함수들을 아래와 같이 파일을 분리해 주세요.

- [ ] export를 활용해 주세요.
- [ ] ProductService.js 파일 Product API 관련 함수들을 작성해 주세요.
- [ ] ArticleService.js 파일에 Article API 관련 함수들을 작성해 주세요.
- [ ]  이외의 코드들은 모두 main.js 파일에 작성해 주세요.

- [ ] import를 활용해 주세요.
- [ ] 각 함수를 실행하는 코드를 작성하고, 제대로 동작하는지 확인해 주세요.

2024-08-27 13:11 UTC, MCprotein commented on api/ArticleService.js
> +    return response.data;
@shinji530 혹시 axios 추상화를 하지 않은 이유가 있을까요?

2024-08-27 13:15 UTC, MCprotein commented on main.js
> +    const patchArticleData = await patchArticle(createArticleData?.id, testPatchArticleData);
@shinji530 createArticleData?.id 여기서 만약 createArticleData가 없다면 patchArticle의 첫번째인자로 undefined가 입력될텐데, 그러면 patchArticle 내부에서 await instance.patch(`/articles/undefined`, articleData); 로 실행될거잖아요. 이러면 무조건 에러가 발생하거나 실패할텐데, 이렇게 무조건 성공하지 않는 상황에서는 차라리 앞에 validation 코드를 넣어서 걸러주는게 좋을거같아요. 클라이언트 입장에서 보면 불필요한 서버 요청, 서버요청에 의한 지연시간이 발생하고, 서버입장에서 보면 불필요한 서버 트래픽, 비용, 자원 낭비 등이 발생하기때문이에요

2024-08-27 13:16 UTC, MCprotein commented on .gitignore
> +package-lock.json
@shinji530 package-lock.json을 gitignore에 추가한 이유가 있을까요? 이건 gitignore에 추가하면 안되는데, 우선 이유를 들어보고 싶어서요!

2024-08-27 14:50 UTC, MCprotein requested changes
@shinji530 prettier tabWidth 4 로 사용하시는 이유가 있을까요?? 자바스크립트 생태계에서는 특별한 경우가 있지 않은 이상 2로 사용하기때문에 맞추는게 좋을거같아요!

2024-08-29 04:11 UTC, shinji530 commented on .gitignore
> +package-lock.json
수업 중에 package-lock.json도 .gitignore에 추가한다고 들었던 거 같은데 잘못 들었나 봅니다,,! 다시 수정해놓겠습니다

2024-08-29 04:15 UTC, shinji530 commented on api/ArticleService.js
> +    return response.data;
앗 어떤 추상화 말씀하시는 걸까요..? 전 
```javascript
const instance = axios.create({
    baseURL: 'https://sprint-mission-api.vercel.app',
    timeout: 3000,
});
```
여기서 추상화가 됐다고 생각했습니다

아니면 fetch를 axios처럼 추상화 하라는 말씀이실까요? 
axios랑 fetch 둘 중 하나만 사용하라 하셔서 더 익숙했던 axios로 사용한 거 였습니다.

둘 다 아니라면 추가적인 설명 부탁드립니다..!

2024-08-29 04:16 UTC, shinji530 commented on main.js
> +    const patchArticleData = await patchArticle(createArticleData?.id, testPatchArticleData);
아,, 생각 못했습니다. 참고해서 수정하겠습니다!

2024-08-29 04:42 UTC, MCprotein commented on api/ArticleService.js
> +    return response.data;
@shinji530 
넵 axios.create 는 axios 내부에서 인스턴스가 만들어지는거고, 제가 말씀드린것은 axios의 get, post, patch, etc. 와 같은 메소드를 getProduct() 이런 사용자 함수에서 사용하지 않도록 추상화하는것이였습니다! 
지금 작성하신대로 개발을 하신다면, 코드 양이 증가할수록 axios 자체의 메소드를 사용하는 코드가 많아지고, 가능성은 낮지만  get, post, patch, etc. 메소드 이름이나 명세가 변경되거나 axios가 아니라 다른 라이브러리로 교체를 하게 된다면 수정해야될 곳이 어마어마하게 많아집니다. 하지만 `requestGet(url) {return axios.get(url)}` 이렇게 추상화를 해서 `getProduct()` 이런 사용자 함수에다가 사용한다면 추후 앞서말씀드린 상황이 왔을때 requestGet 여기 내부만 바꾸면 되기때문에 유지보수가 훨씬 간단해집니다.
혹시 말씀드린부분에서 의아한 부분이 있으실까요?

2024-08-29 04:46 UTC, MCprotein commented on .gitignore
> +package-lock.json
@shinji530 package.json을 보시면 버전 앞에 대부분 ^가 붙은걸 보실 수 있는데, 이거는 메이저버전만 일치하면 된다는 의미에요. 그래서 예를들어 지금 1.0.0 버전을 설치해도 나중에 npm install을 다시하면 그때 기준 1버전의 최신버전으로 설치되어 1.0.10이 설치될수도 있는거죠. 
package-lock.json에는 1.0.0 이라는 정확한 버전이 명시되어있고, npm ci 명령어로 package-lock.json 을 참조하여 설치하면 패키지를 최초 설치했을때의 버전으로 설치돼요. 마이너버전이여도 패키지 내부의 API 명세가 변경될 수 있기때문에 이런 내용들을 기억해두셨다가 나중에는 npm ci 와같은 명령어를 사용하시는게 안전해요.
npm이 아니라 yarn 과 같은 다른 패키지매니저프로그램에도 해당 기능을 하는 명령어가 있으니 참고하시면 좋을거같아요.
혹시 의아한점이 있으면 말씀해주세요!

2024-08-29 04:50 UTC, MCprotein commented
> @shinji530 prettier tabWidth 4 로 사용하시는 이유가 있을까요?? 자바스크립트 생태계에서는 특별한 경우가 있지 않은 이상 2로 사용하기때문에 맞추는게 좋을거같아요!

@shinji530 수정해주신거 봤는데, 자바스크립트에서는 double quote 말고 single quote를 주로 사용합니다 ...

2024-08-29 06:07 UTC, shinji530 commented on api/ArticleService.js
> +    return response.data;
아 넵 이해했습니다 참고해서 수정하겠습니다!

2024-08-29 06:09 UTC, shinji530 commented on .gitignore
> +package-lock.json
넵 이해했습니다!

2024-08-29 11:50 UTC, MCprotein commented on main.js
> +  if (!data.title || typeof(data.title) !== 'string') {
@shinji530 지원님! typeof 사용할때 괄호 안에 인자 넘기듯이 써도 되지만, 일반적으로는 `typeof data.title === 'string'` 요렇게 사용합니다! 
MDN 문서에서 예시코드를 보시면 좋을거같아요!
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/typeof

2024-08-29 13:04 UTC, shinji530 commented on main.js
> +  if (!data.title || typeof(data.title) !== 'string') {
넵 수정하겠습니다!

2024-08-29 13:14 UTC, MCprotein commented
지원님 고생하셨습니다!!

2024-08-29 13:15 UTC, MCprotein approved these changes

2024-09-01 10:41 UTC, merged