[김영은] Sprint 4
codeit-sprint-fullstack/2-Sprint-Mission-FE pull request #79
Opened 2024-08-27 08:46 UTC by Maybeiley

## 요구사항

### 기본

`공통`

- [x] Github에 스프린트 미션 PR을 만들어 주세요.
- [x]  'https://sprint-mission-api.vercel.app/articles' API를 이용하여 아래 함수들을 구현해 주세요.**
  - [x] getArticleList() : GET 메서드를 사용해 주세요.
    - [x] page, pageSize, keyword 쿼리 파라미터를 이용해 주세요.
  - [x] getArticle() : GET 메서드를 사용해 주세요.
  - [x] createArticle() : POST 메서드를 사용해 주세요.
    - [x] request body에 title, content, image 를 포함해 주세요.
  - [x] patchArticle() : PATCH 메서드를 사용해 주세요.
  - [x] deleteArticle() : DELETE 메서드를 사용해 주세요.
- [x]  fetch 혹은 axios 를 이용해 주세요.
  - [x] 응답의 상태 코드가 2XX가 아닐 경우, 에러메시지를 콘솔에 출력해 주세요.
- [ ]  .then() 메서드를 이용하여 비동기 처리를 해주세요.
- [ ]  .catch() 를 이용하여 오류 처리를 해주세요.
- [x]  'https://sprint-mission-api.vercel.app/products' API를 이용하여 아래 함수들을 구현해 주세요.**
  - [x] getProductList() : GET 메서드를 사용해 주세요.
    - [x] page, pageSize, keyword 쿼리 파라미터를 이용해 주세요.
  - [x] getProduct() : GET 메서드를 사용해 주세요.
  - [x] createProduct() : POST 메서드를 사용해 주세요.
    - [x] request body에 name, description, price, tags, images 를 포함해 주세요.
  - [x] patchProduct() : PATCH 메서드를 사용해 주세요.
  - [x] deleteProduct() : DELETE 메서드를 사용해 주세요.
- [x]  async/await 을 이용하여 비동기 처리를 해주세요.
- [x]  try/catch 를 이용하여 오류 처리를 해주세요.
- [x]  구현한 함수들을 아래와 같이 파일을 분리해 주세요.
  - [x] export를 활용해 주세요.
  - [x] ProductService.js 파일 Product API 관련 함수들을 작성해 주세요.
  - [x] ArticleService.js 파일에 Article API 관련 함수들을 작성해 주세요.
- [x]  이외의 코드들은 모두 main.js 파일에 작성해 주세요.
  - [x] import를 활용해 주세요.
  - [x] 각 함수를 실행하는 코드를 작성하고, 제대로 동작하는지 확인해 주세요.

## 주요 변경사항

- 배포(Netlify) : https://go-panda-market.netlify.app/

## 스크린샷

-

## 멘토에게

- Product 쪽은 axios, Article 쪽은 fetch를 사용해서 작성했습니다.

2024-08-27 10:06 UTC, junguksim commented
> deleteArticle 함수 문제: 삭제 요청은 실행되는데 계속 "Unexpected end of JSON input" 에러가 떠서 확인해 보니 상태코드가 204 No Content 입니다. API 링크에서는 204 코드 때 "성공적으로 삭제됨"이라고 설명하는데, 오류가 나는 이유가 무엇인지 어떻게 해결해야 하는지 궁금합니다.

204는 잘 삭제되었다는 메시지라서, body 를 따로 담아서 리턴하지 않는 것 같습니다.
즉 `await response.json()` 을 해도, 가져올 body가 없으므로 에러가 나는 것 같아요.

삭제한 아티클의 데이터가 필요한 상황이라면, DELETE 전에 GET 을 해서 데이터를 변수에 저장해두고 그 다음 DELETE 를 한 후 해당 변수를 리턴해야할 거 같습니다.

이런 상황을 피하기 위해 저는 API 서버 구현 시 DELETE 메소드 이후 200과 삭제된 데이터를 리턴하도록 하는 걸 선호합니다.

2024-09-03 08:05 UTC, junguksim commented
Confilct 해결해주세요!

2024-09-03 10:09 UTC, Maybeiley commented
> Confilct 해결해주세요!

해결했습니다!

2024-09-03 15:21 UTC, junguksim requested changes
잘해주셨습니다!

POST 과정에서의 인풋 검증이 추가되면 좋을 것 같습니다~

2024-09-03 15:21 UTC, junguksim commented on api/ArticleService.js
> +    const url = new URL('https://sprint-mission-api.vercel.app/articles');
https://sprint-mission-api.vercel.app/articles 이 API 기본 주소로써 반복되므로,

전역 변수로 const url 로 설정해주고

사용할 때 ` fetch( ` ${url}/ ${id}` )` 이런식으로 쓰는 게 깔끔하겠습니다!

2024-09-03 15:21 UTC, junguksim commented on api/ArticleService.js
>      headers: {
header 또한 반복되므로 전역변수 선언 후 재사용해주세요~!

2024-09-03 15:21 UTC, junguksim commented on api/ProductService.js
> +    const products = await instance.post('/products', productData)
productData 는 값들을 담은 object 일텐데요,
create 의 경우는 인풋으로 들어갈 데이터들을 검증해주는 게 좋습니다.
서버가 핸들링을 제대로 못했을 경우, 예상치 못한 데이터가 들어가는 것을 막아줄 수 있습니다!

2024-09-03 15:21 UTC, junguksim commented on api/ProductService.js
> +    const products = await instance.post('/products', productData)
위의 createArticle 에도 적용해보세요.

2024-09-06 03:10 UTC, junguksim requested changes

2024-09-06 03:10 UTC, junguksim commented on api/ArticleService.js
> +  function ValidateData(key, type) {
이 함수 재사용할 수 있게 모듈화해보세요!

2024-09-06 03:10 UTC, junguksim commented on api/ArticleService.js
> +  function ValidateData(key, type) {
+ 함수니까 맨 앞을 소문자로 해주세요~

2024-09-11 08:59 UTC, junguksim approved these changes
Approve 로 리뷰를 끝내라고 하셔서 바꿉니다!

2024-09-12 01:03 UTC, merged