[서유림] Sprint 5
codeit-sprint-fullstack/2-Sprint-Mission-FE pull request #99
Opened 2024-09-03 04:42 UTC by Seo-Yurim

# 요구사항
## 기본 요구사항
### 공통

- - [ ] Github에 스프린트 미션 PR을 만들어 주세요.
- - [ ] React를 사용해 진행합니다.

### 중고마켓 페이지

- - [ ]  PC, Tablet, Mobile 디자인에 해당하는 중고마켓 페이지를 만들어 주세요.

- - [ ]  중고마켓 페이지 url path는 별도로 설정하지 않고, ‘/’에 보이도록 합니다.

- - [ ]  상품 데이터는 [https://panda-market-api.vercel.app/docs/](https://panda-market-api.vercel.app/docs/#/)에 명세된 GET 메소드 “/products” 를 사용해주세요.

- - [ ]  상단 네비게이션 바, 푸터는 랜딩 페이지와 동일한 스타일과 규칙으로 만들어주세요.

- - [ ]  상품 데이터는 [https://panda-market-api.vercel.app/docs/](https://panda-market-api.vercel.app/docs/#/)에 명세된 GET 메소드 “/products” 를 활용해주세요.

  - - [ ] 상품 목록 페이지네이션 기능을 구현합니다.
  - - [ ] 드롭 다운으로 “최신 순” 또는 “좋아요 순”을 선택해서 정렬을 구현하세요.
  - - [ ] 상품 목록 검색 기능을 구현합니다.
- - [ ]  베스트 상품 데이터는 [https://panda-market-api.vercel.app/docs/](https://panda-market-api.vercel.app/docs/#/)에 명세된 GET 메소드 “/products”의 정렬 기준 favorite을 사용해주세요.

## 심화 요구사항
### 공통

- - [ ] 커스텀 hook을 만들어 필요한 곳에 활용해 보세요.

### 중고마켓 페이지

- - [ ] 중고 마켓의 카드 컴포넌트 반응형 기준은 다음과 같습니다.
  - - 베스트 상품
    - - Desktop : 4열
    - - Tablet : 2열
    - - Mobile : 1열
  - - 전체 상품
    - - Desktop : 5열
    - - Tablet : 3열
    - - Mobile : 2열
- 반응형에 따른 페이지 네이션 기능을 구현합니다.
  - 반응형으로 보여지는 물품들의 개수를 다르게 설정할때 서버에 보내는 pageSize값을 적절하게 설정합니다.

2024-09-10 16:20 UTC, json9512 requested changes
# 총평
- 고군분투 하신 흔적이 보입니다 💪 
- 전체적으로 모바일 스타일 대응이 미흡해요!
  - 한 가지 팁을 드리자면, CSS를 짜실 때 모바일 우선으로 먼저 작업하고 media query를 활용해서 큰 사이즈 기기들에 대한 스타일을 짜는게 더 짜기 쉬울겁니다. (개인차 있긴 합니다)
- 처음 코드 짜실 때, 단순하게 `input` `output` 개념으로 생각해보시면 좋을 것 같습니다.
  - ex) `지금 만드는 함수는 parameter가 몇 개고 무엇을 하는 함수지?`, `이 컴포넌트는 props로 무엇을 몇 개나 받지?`
- React의 상태와 `useEffect`는 최소한으로 사용하는 게 좋습니다.
- 커밋을 작은 단위로 나누는 것은 아주 좋았어요! 👍

2024-09-10 16:20 UTC, json9512 commented on .gitignore
> +node_modules
`.vscode` 도 추가해주세요.

- [ ] `.vscode` 추가

2024-09-10 16:20 UTC, json9512 commented on .vscode/launch.json
이 파일은 git으로 트래킹 할 필요가 없어서 제거 부탁드려요!

기존에 트래킹 중이던 파일을 git에서 제거하려면 아래 작업을 해주시면 됩니다!
1. 프로젝트 root로 이동
2. `git rm --cached -r .vscode` 터미널에서 실행
3. `.gitignore`에 `.vscode` 줄 추가
4. `git add .`
5. `git commit -m ".vscode 제거"`
6. `git push`

2024-09-10 16:20 UTC, json9512 commented on .vscode/launch.json
- [x] 불필요한 파일 git에서 제거

2024-09-10 16:20 UTC, json9512 commented on Sprint4/ArticleService.js
> +instance.interceptors.response.use(
interceptor 사용 좋네요! 👍

2024-09-10 16:20 UTC, json9512 commented on privacy/indedx.html
파일 명에 오타가 있는 것 같아요!
`indedx` -> `index`

- [x] 파일명 확인

2024-09-10 16:20 UTC, json9512 commented on sprint5/package.json
> +    "@testing-library/jest-dom": "^5.17.0",
`axios` 가 빠진 것 같아요.

리액트를 사용한 sprint5의 경우, sprint 5 폴더 내에서 `npm install axios`를 한번 해주시어 `package.json`을 업데이트 시킬 수 있습니다. 

이후 `npm run start`를 하시면 sprint 5 폴더 내에 리액트로 작업된 내용을 확인해볼 수 있어요.

- [x] react 앱 dependency에 axios 추가

2024-09-10 16:20 UTC, json9512 commented on sprint5/src/api.js
> +  const res = await requestGet(`/products${id}`);
API url 오타 있는 것 같습니다!
`/products${id}` -> `/products/${id}`

2024-09-10 16:20 UTC, json9512 commented on sprint5/src/api.js
> +  const res = await requestPatch(`/products${id}`, product);
여기도 오타있어요!

2024-09-10 16:20 UTC, json9512 commented on sprint5/src/api.js
> +  const res = await requestDelete(`/products${id}`);
여기도요

2024-09-10 16:20 UTC, json9512 commented on sprint5/src/api.js
> +  const res = await requestGet(`/products${id}`);
- [x] api endpoint 오타 확인

2024-09-10 16:20 UTC, json9512 commented on sprint5/src/hooks/useAsync.js
> +export default function useAsync(asyncFunction) {
접근 방식은 나쁘지 않아요. 다만 더 발전 할 수 있을 것 같아요!
현재 `useAsync` 함수의 구조를 생각해보았을 때:

들어오는 값 (input) = `asyncFunction`
나가는 값 (output) = `[pending, error, wrappedFunction]` 인데요.

막상 `useAsync`를 사용하는 사용처를 생각해보면 wrappedFunction을 useEffect로 돌려서 데이터를 서버로부터 받고 각 컴포넌트에 상태 관리자로 전달 해주고 계시잖아요?

예시를 드리자면:

```ts
export default function BestProduct() {
  const [bestItems, setBestItems] = useState([]);
  const [isLoading, loadingError, getProductAsync] = useAsync(getProductList);
  const [bestPageSize, setBestPageSize] = useState(4);

  //... 생략
 
  const handleBestLoad = useCallback(
    async (params) => {
      const result = await getProductAsync(params);
      if (!result) return;

      const { list } = result;
      // 2. 서버로 부터 받은 값을 로컬 컴포넌트 상태에 저장
      setBestItems(list.sort((a, b) => b.favoriteCount - a.favoriteCount));
    },
    [getProductAsync]
  );

  // 1. useEffect로 서버 데이터 페칭
  useEffect(() => {
    handleBestLoad({ page: 1, pageSize: bestPageSize, orderBy: 'favorite' });
  }, [bestPageSize, handleBestLoad]);
```

이렇게 사용 중이신데, 좀만 더 생각해보시면 사실

Input = `비동기 서버 호출 함수`
output = `[data, isLoading, error]` (data 추가)

이렇게 변경하면 좀 더 범용적인 훅이 될 것 같아요!

각 컴포넌트에서 하던 useEffect 처리를 훅 안에서 처리하도록 하고, 해당 컴포넌트에서는 지역 상태 값을 삭제해도 괜찮을 것 같아요.

2024-09-10 16:20 UTC, json9512 commented on sprint5/src/hooks/useAsync.js
> +export default function useAsync(asyncFunction) {
코드로 예시를 좀 들어드리자면:

```ts
// useAsync를 살짝 변형한 훅
import { useState, useEffect } from "react";

export default function useQuery(asyncFunction) {
  const [data, setData] = useState(null);
  const [pending, setPending] = useState(false);
  const [error, setError] = useState(null);

  useEffect(() => {
    setPending(true);
    asyncFunction()
      .then((data) => setData(data))
      .catch((error) => setError(error))
      .finally(() => setPending(false));

    return () => setPending(false);
  }, [asyncFunction]);

  return [data, pending, error];
}
```

이렇게 좀 더 범용적인 훅을 만들어 놓으시면, 비동기 함수 콜에 대한 처리를 이 훅을 통해 할 수 있어요! (꼭 서버가 아니더라도 비동기 통신은 많으니까요 😄)

2024-09-10 16:20 UTC, json9512 commented on sprint5/src/hooks/useAsync.js
> +export default function useAsync(asyncFunction) {
이걸 어떻게 사용할 수 있는지 추가적으로 팁을 좀 드리자면,

```ts
export default function ProductList() {
  // 신규 훅 사용
  // 기존 불필요한 지역 상태 값 삭제
  const [data, isLoading, error] = useQuery(getProductList);
  const [pageSize, setPageSize] = useState(10);
  const [sortOrder, setSortOrder] = useState("recent");
  const [keyword, setKeyword] = useState("");
  const [currentPage, setCurrentPage] = useState(1);

  // 기존 useEffect에서 처리하던 로직을 단순하게 컴포넌트 render 전에 처리
  const sortedItems = data?.list.sort((a, b) => {
    if (sortOrder === "recent") {
      return b.createdAt - a.createdAt;
    }
    if (sortOrder === "favorite") {
      return b.favoriteCount - a.favoriteCount;
    }
    return 0;
  });

  const filteredItems = sortedItems?.filter((item) =>
    item.name.toLowerCase().includes(keyword.toLowerCase())
  );
  
  // 위에 로직을 담당하던 기존 useEffect 함수들 삭제

  // ... 생략 (다른 useEffect 콜 있는 자리)

 const totalPages = Math.ceil(filteredItems?.length / pageSize);
  const currentItems = filteredItems?.slice(
    (currentPage - 1) * pageSize,
    currentPage * pageSize
  );

  return (
    <section>
      <ProductListBar
        value={sortOrder}
        onChange={setSortOrder}
        keyword={keyword}
        onSearch={setKeyword}
      />
      <div className="products">
        <div className="product-list">
          {currentItems?.map((item) => (
            <div key={item.id}>
              <ProductListItem item={item} />
            </div>
          ))}
        </div>
      </div>
      <Pagination
        currentPage={currentPage}
        totalPages={totalPages}
        onPageChange={setCurrentPage}
      />
    </section>
  );
```

요런 식으로 짤 수 있어요.

2024-09-10 16:20 UTC, json9512 commented on sprint5/src/hooks/useAsync.js
> +export default function useAsync(asyncFunction) {
React에서 제공하는 useState, useEffect 등을 사용하실 때는 `이게 정말 필요한가?`를 다시 고민해보는게 좋아요. 웬만한 경우에 거의 필요 없어요.

2024-09-10 16:20 UTC, json9512 commented on sprint5/src/hooks/useAsync.js
> +export default function useAsync(asyncFunction) {
유림님이 작성하신 `useAsync`를 통한 비동기 함수 호출에 대한 처리는, React에서 비동기 통신을 다룰 때 꼭 한번 씩 추상화를 하는 훅이어서 직접 구현을 시도하신 것은 아주 좋았습니다 👍

사실 이런 기능은 React로 개발할 때 필수 요소여서 관련 라이브러리들이 많은데요. 해당 라이브러리들이 어떻게 구현했는지 참고하는 것도 좋아요!
- [tanstack-query](https://tanstack.com/query/latest/docs/framework/react/guides/queries)
- [swr hooks](https://swr.vercel.app/)

2024-09-10 16:20 UTC, json9512 commented on sprint5/src/components/BestProduct.js
> +  useEffect(() => {
이 useEffect도 자주 보이는데, 이것도 커스텀 훅으로 구성해봐도 좋을 것 같아요! 🤔 
- [ ] (제안) page size 처리 커스텀 훅 구현

2024-09-10 16:20 UTC, json9512 commented on sprint5/src/components/OrderMenu.js
> +const OrderMenu = ({ value, onChange }) => {
현재 `OrderMenu` 컴포넌트에서 사용할 값을 - 부모 컴포넌트에서부터 자식 컴포넌트까지 props로 전달해주시고 계신데요. 
ex)
```ts
ProductList (부모) 
  |
ProductListBar (자식)
  |
OrderMenu (자식의 자식) 
```

이를 `props`를 아래로 구멍 뚫듯이 쭉 내려준다고 해서 `props drilling` 현상이라고 합니다.
이는 React로 개발하다보면 마주하게 되는 자연스러운 현상인데요.

문제는 props drilling이 발생하면 코드가 유지 보수하기 상당히 어려워져요.

React에는 props drilling을 해소하는 여러가지 방법들이 있는데, 한번 찾아서 해소해보시면 좋을 것 같아요!

- [ ] React의 props drilling 해소해보기

2024-09-10 16:20 UTC, json9512 commented on sprint5/src/hooks/useAsync.js
> +export default function useAsync(asyncFunction) {
- [ ] useAsync 개선해보기

2024-09-10 16:20 UTC, json9512 commented on Sprint4/ArticleService.js
> +async function requestGet(url, params) {
보통 함수는 동사형 단어가 앞에 오긴 합니다!....만 `request` `get` 둘 다 동사군요 🤔 

이럴 땐 단순하게 `get, post, patch, delete`로 선언해도 무방할 것 같습니다.
API에서 처리하는 것이라 의미 전달이 잘 될 것 같아요.

ex) `requestGet` -> `get`
사용처) `requestGet(url, body)` -> `get(url, body)`

- [ ] 함수 명 수정

2024-09-10 16:47 UTC, json9512 commented on sprint5/src/components/BestProduct.js
> +  useEffect(() => {
참고: https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver

2024-09-11 00:13 UTC, Seo-Yurim commented on sprint5/src/api.js
> +  const res = await requestGet(`/products${id}`);
수정 완료하였습니다 !

2024-09-11 00:17 UTC, Seo-Yurim commented on .gitignore
> +node_modules
추가 하였습니다 !

2024-09-11 00:19 UTC, Seo-Yurim commented on Sprint4/ArticleService.js
> +async function requestGet(url, params) {
수정 완료하였습니다!

2024-09-11 00:30 UTC, Seo-Yurim commented on .vscode/launch.json
제거하였습니다 !

2024-09-11 00:30 UTC, Seo-Yurim commented on privacy/indedx.html
수정하였습니다 !

2024-09-11 06:16 UTC, Seo-Yurim commented on sprint5/src/hooks/useAsync.js
> +export default function useAsync(asyncFunction) {
수정하였습니다 !

2024-09-11 07:43 UTC, Seo-Yurim commented on sprint5/src/components/BestProduct.js
> +  useEffect(() => {
수정 완료하였습니다 !

2024-09-11 09:40 UTC, Seo-Yurim commented on sprint5/src/components/OrderMenu.js
> +const OrderMenu = ({ value, onChange }) => {
수정 완료하였습니다! context를 활용하여 해결해보았는데 맞게 한건지는 잘 모르겠네요 ㅠㅠ !

2024-09-12 14:21 UTC, json9512 approved these changes

2024-09-12 14:21 UTC, merged